lib/Notes/NoteRenderer.js

The NoteRenderer component will be used multiple times here so we need
to pass a unique dataKey element to the `connect()` call to be sure that
each instance recieves distinct data.

dataKey is required to de-dupe names. Fixes STSMACOM-20

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

The `notes` part of the query may be absent for no notes pane, `true`
to display it, or the UUID of a specific note.
Fixes STSMACOM-19.

Status of notes pane is now reflected in the URL

---

.eslintrc
CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Both these URL parameters are presently needed, as discussed in comments to UISE-13. This change will eventually be undone, moving to `query` alone: see STSMACOM-27.
Fixes STSMACOM-25.

`<SearchAndSort>` sets both `query` and `search`

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

We are also therefore able to remove the mysterious invisibly-coupled
`updateFilters` callback.
Fixes STSMACOM-35 and so resolves the filter-resetting problem of
STRIPES-493.

Upgrade <SearchAndSort> to use new filter-related APIs.

---

lib/SearchAndSort/SearchAndSort.js

Resolves UIREQ-38:
This places logic in the render method of search and sort which conditions the inclusion of the details pain on the absence of `this.props.onSelectRow`. Now, if an embedded instance of search and sort has had the behavior of onSelectRow overwritten, the detail pane will not be initialized, and therefore not incur the errors that have been reported.

Search and Sort: Conditional render of detail pain

---

lib/Notes/Notes.js
lib/SearchAndSort/SearchAndSort.js

In this pull request I have primarily been focusing on fitting the SearchAndSort component to use the new PaneHeader.
I also added a search icon in the results-pane which isn't active yet but should be in the future:
For now I have left the search bar in the PaneHeader but this will be deprecated in the future and replaced with a search field in the search/filter pane content like so:
(See http://ux.folio.org/prototype/en/inventory)

Updating search and sort component to fit PaneHeader changes

---

lib/SearchAndSort/SearchAndSort.js

Support optional "path" prop in addition to default `.../view/:id`.
This allows detail views to use parameters defined in the `<Route>`.

support optional path prop. Refs UIIN-34

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Part of the UISE-38 work.
Related to this, the recently-introduced `searchableFields` property is renamed `searchableIndexes`, as it should have been all along; and `onChangeField` is renamed `onChangeIndex`. This fixes up the work done for STSMACOM-41.

Pass new `selectedIndex` parameter through to <FilterPaneSearch>

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

It now leaves the filters and sort-order untouched.
Fixes STSMACOM-42.

`<SearchAndSort>`'s clear-search button clears only the query

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

When a results list is narrowed to a single item, show the details pane automatically. Fixes [UIIN-58](https://issues.folio.org/browse/UIIN-58).

show details pane for one-item search results. Fixes UIIN-58

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

- More work for [STCOM-164](https://issues.folio.org/browse/STCOM-164). 
- The magnifying glass in the header of the search results pane toggles the visibility of the filters/search pane. 
- When the pane is closed, a badge appears on the magnifying glass icon showing the number of active filters.
No animations on this pass per discussion on Slack.

SearchAndSort: Added ability to toggle visibility of Filters pane

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

The record-display area now displays one of several possible messages, depending on the status information in the records resource. There are five possible states, so to keep the code clean I extracted the relevant logic out into a new `noRecordsMessage` function.
Fixes STSMACOM-46.

Distinguish between loading, error and neither

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Allows callers to limit the number of sort-keys to 1 (or indeed increase it to 3 or more). The immediately use-case for this is that mod-ebsco-ekb can't accept multple sort-keys, so ui-search needs to avoid sending such queries (see  UISE-47).
Fixes STSMACOM-45.

<SearchAndSort> supports optional 'maxSortKeys' property

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

This is a function that is passed the filter state when it changes.
Fixes STSMACOM-47.

Support the optional `filterChangeCallback` property

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

The show-single-result behavior should be optional and default to false.
This restores the previous behavior by default and gives apps the
option of using it on request.
It causes problems in the ui-plugin-find-user context where winnowing a
search in a modal window causes the parent window to redirect to the
entry's detail record when, instead, we simply want to indicate that the
search returned a single record and the user should click it to select
it.
Fixes [STSMACOM-52](https://issues.folio.org/browse/STSMACOM-52). Refs [UIIN-58](https://issues.folio.org/browse/UIIN-58), [UIREQ-60](https://issues.folio.org/browse/UIREQ-60), [UICHKOUT-54](https://issues.folio.org/browse/UICHKOUT-54), [UIU-373](https://issues.folio.org/browse/UIU-373).

show-single-result should be optional.

---

lib/ControlledVocab/ControlledVocab.js

Prevents EditableListForm from re-rendering before confirming success from the backend

Prevents EditableListForm from re-rendering before confirming success

---

lib/Notes/NoteRenderer.js
lib/Notes/NotesForm.js
lib/SearchAndSort/SearchAndSort.js

Follow-up to https://github.com/folio-org/stripes-components/pull/209.
1. `transparent` is no longer an available button style; replaced with `link`
2. Now that `primary` is no longer the default button style (now `default` is), a couple of primary action buttons needed that style applied.

Improve button style consistency

---

lib/SearchAndSort/SearchAndSort.css
lib/SearchAndSort/SearchAndSort.js

- Moved the SearchField at the top of the Search & Filter pane into an accordion.
- The clear X by the accordion title resets the query index and the query.
- The clear X inside the SearchField resets just the query.
- Changed the top button's label back to "Reset all"
- Styling on that button has **not** been changed from the `link` styling. The various changes in the Button component re:styling have made getting back to the previous styling (grey with no border) not possible (AFAIK) without adding more CSS styles, which I thought we were trying to avoid. @JohnC-80 and @rasmuswoelk feel free to advise otherwise.

STCOM-164: Move SearchAndSort search field into an accordion

---

CHANGELOG.md
lib/Notes/AtMentionTextArea.js
lib/Notes/Notes.css
lib/Notes/Notes.js
lib/Notes/NotesForm.js
package.json

Fixes [STSMACOM-4](https://issues.folio.org/browse/STSMACOM-4). Provide autocompletion of usernames in `<Notes>` fields. 
This is more or less a replay #66 which was reverted in #79 due to build issues since resolved by https://github.com/folio-org/stripes-core/pull/161.

autocomplete @mentioned usernames. Fixes STSMACOM-4.

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
package.json

Many values used in SearchAndSort are derived from values in the calling
module's `package.json` file. This update adds support for passing in
those values (via `props.packageInfo`) and deriving them, rather than
repeating that code in every single module that calls SearchAndSort.
Refs [STSMACOM-64](https://issues.folio.org/browse/STSMACOM-64)

Optionally derive some props from props.packageInfo

---

lib/SearchAndSort/SearchAndSort.js

[This fixes STCOM-222 where the "Reset all" button was visible on initial load of Users.](https://issues.folio.org/browse/STCOM-222) 
The cause was a change in how the Users app provided and handled the intialFilters in ui-users/#262. SAS is now more permissive in handling the initialFilters.

STCOM-222 SearchAndSort: Handle undefined filters query param

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
package.json

Now that all packages using `<SearchAndSort>` pass it their `packageInfo` values, we can deprecate the old props that were just derived from `packageInfo` before passing them as props. 
Refs [STSMACOM-64](https://issues.folio.org/browse/STSMACOM-64).

require props.packageInfo. Refs STSMACOM-64

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
package.json

`props.browseOnly` prevents the create-object pane
For when you really only want search-and-sort, not search-and-sort-and-edit-and-create, e.g. when you are accessing this in the context of ui-plugin-find-user which wants to search for users but disallow creating or editing them.
Refs [UIPFU-6](https://issues.folio.org/browse/UIPFU-6).

props.browseOnly prevents the create-object pane. Refs UIPFU-6

---

lib/SearchAndSort/ResourcesAnalyzer.js
lib/SearchAndSort/SearchAndSort.js

Rather than poking around in the stripes-connect response structure, `<SearchAndSort>`'s `render` method now creates a `ResourcesAnalyzer` object on that structure and invokes methods on that object to obtains records, hit-counts, pending status, etc.
This fixes much of STSMACOM-65 and clears the way for STSMACOM-66 in which I will make the analyzer class smart enough to extract analogous information from GraphQL responses, thereby making SearchAndSort bilingual.
*Note 1* I will similarly need to convert the other `<SearchAndSort>` methods as well as `render`.
*Note 2* This only covers `<SearchAndSort>` itself: down the line, we will similarly need to convert the ViewRecord and EditComponent for each of the modules that use it.
So we have a ways to go yet.

Towards abstracting analysis of search responses

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Add optional `apolloResource` property to `<SearchAndSort>`, for use of resource analyzer

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
lib/UserLink/UserLink.js
lib/UserLink/index.js
lib/UserName/UserName.js
lib/UserName/index.js
package.json

Several settings pages were moving away from ControlledVocab and adding their own confirmation dialogs and custom renderers. This centralises that code into the ControlledVocab component.
- A default schema is expected but can be overridden.
- Updated metadata, when available, will be rendered as a date and a link to the user who made that update.
- Count columns can be shown and take a custom renderer from the parent. PatronGroupsSettings is currently the only user of this, though AddressTypesSettings will likely as well.
This will be used in forthcoming PRs in ui-users and ui-inventory to transition their CV settings pages to this.

STCOM-228: Add functionality to <ControlledVocab>

---

lib/ConfigManager/ConfigManager.js

redux-form can accept `validate` as a prop on the the FormComponent, or as a stand-alone function. To have access to `this.props.stripes`, it needs to be the former. This PR enables that.

pass validate() as prop

---

lib/ConfigManager/ConfigManager.js

Follow-on to https://github.com/folio-org/stripes-smart-components/pull/128; the FormComponent needs access to `this.props.stripes`.

pass stripes in props

---

lib/ControlledVocab/ControlledVocab.js

Making the error deletion failures a bit nicer. This'll eventually get tweaked with whatever we decide to do with the new mutator/stripes-connect v2/GraphQL API but I wanted to get it working now.

STCOM-237 ControlledVocab: Show modal when deletion fails

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

https://issues.folio.org/browse/STSMACOM-81
It looks like what was happening here is that `locallyChangedSearchTerm ` was fighting with `this.queryParam('query')`. Since setting `locallyChangedSearchTerm` is done outside of the `debounce` the local state would be cleaned up but the `this.queryParam('query')` would still hold the previous value.

Improve search field in SearchAndSort component. Fixes STSMACOM-81

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

I don't understand why the `successfulMutations` array would be empty after creating a user, and indeed I never see this condition on my development box -- which makes it very hard to debug -- but it does happen on folio-testing and snapshot. So I've added a guard, whose effect I can't observe on my own box, in the hope that it will make the public boxes work right when it gets uploaded.
Yeah, I know.
Should fix STSMACOM-83.

Guard against selecting row when no mutations available

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
package.json

Allow the rows of a `<ControlledVocab>` table to be filtered, e.g. so that only rows with an attribute matching the value of a `<select>` are displayed. 
Accept four new props: 
1. `rowFilter` a component to be rendered above the rows; used to provide the value to filter against.
1. `rowFilterFunction` a callback to handle row filtering; receives one row at a time and should return true IFF the row should be displayed and false otherwise. 
1. `preCreateHook` a callback that receives a row-object immediately before it is created; it should return a copy of the object. 
1. `preUpdateHook` a callback that receives a row-object immediately before it is updated; it should return a copy of the object. 
The calling component should put an `onChange` handler on the `rowFilter` component that …

Filters for ControlledVocab rows

---

lib/ControlledVocab/ControlledVocab.js
package.json

Use that fancy new STCON-67 functionality to catch errors thrown by mutator calls, rather than writing our own `fetch`.

ControlledVocab: Handle own mutator errors

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

This wasn't working consistently when using GraphQL, because Apollo briefly sets result-count to `null` while it's in the process of running a search, so we weren't seeing the expected transition between a hit-count of more than one and a hit-count of exactly one. (It was still working _sometimes_ because if the single-hit search is in the cache from earlier, Apollo leaps straight to it without going through an in-progress stage.)
This was fixed by remembering the last _non-null_ result-count, and showing the full record when _that_ goes from greater than one to exactly one.
Fixes STSMACOM-98.

Always display sole hit when narrowing down to one result

---

lib/ControlledVocab/ControlledVocab.css
lib/ControlledVocab/ControlledVocab.js
lib/UserLink/UserLink.css
lib/UserLink/UserLink.js
lib/UserName/UserName.js

Had to do some ✨ CSS ✨ here because we want to truncate the individual components of the name but still allow it to break onto multiple lines.
Keys are `fill-available` on the parent and `block` display on the `<a>`. Since we don't want to always `block` display on UserLink's I went ahead and made it an opt-in.

STSMACOM-99 ControlledVocab: Truncate username when it doesn't fit

---

lib/ControlledVocab/ControlledVocab.css

Just supporting the eventual value for the behaviour we want here. Doesn't really do anything currently, since only prefixed values are used by browsers.

ControlledVocab: Switched from fill-available to stretch

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
package.json

Will eventually be used by UIIN-150, UIIN-151 and UIIN-152 to prevent editing of the "Source" field. [UIIN-152's mockup](https://issues.folio.org/browse/UIIN-152) has been updated to show how it'll be used.

ControlledVocab: Added readOnlyFields prop

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
package.json

Some CV records are semi-permanently stored in Folio and shouldn't be edited by the user, even if they're a privileged user with access to the settings. Examples of these records would be RDA Content Types or RDA Carrier Types mentioned in [UIIN-150](https://issues.folio.org/browse/UIIN-150), -151, -152, etc.
A generic way of marking records as readonly is preferable to every settings page defining their own standard and their own action suppressors.
This action suppression is now implemented in CV via `defaultProps` so that it can be overridden if the component using `<ControlledVocab>` wants to.

STSMACOM-103 ControlledVocab: Prevent edit/delete on readOnly records

---

lib/ControlledVocab/ControlledVocab.css
lib/ControlledVocab/ControlledVocab.js
lib/UserLink/UserLink.css
lib/UserLink/UserLink.js

The background for this is [UIORG-76](https://issues.folio.org/browse/UIORG-76). I debated over a few ways of implementing this.
1. Putting the decision making in `<UserLink>`
👍: It's reusable everywhere and we won't accidentally render an unusable link. 
👎: UserLink doesn't render a link. That seems weird.
2. The solution I went with, putting the decision-making of rendering a UserLink vs UserName in ControlledVocab.
👍: Doesn't have the downside of the above solution.
👎: Doesn't have the upside of the above solution.
I went with what results in a more sane codebase that forces the programmer to be a bit more proactive in deciding whether they should be unconditionally rendering a UserLink and Link.

STSMACOM-106: UserLink should only render a Link when the user has perms to follow that link

---

lib/ControlledVocab/ControlledVocab.css
lib/ControlledVocab/ControlledVocab.js

[STSMACOM-102](https://issues.folio.org/browse/STSMACOM-102)
- autoprefixer adds the vendor labels for us and complained that we added them; figured it out from this [comment](https://github.com/postcss/autoprefixer/issues/1035#issuecomment-387247093)
- update component path ([STCOM-277](https://issues.folio.org/browse/STCOM-277))

fix autoprefixer console warning

---

lib/ChangeDueDateDialog/ChangeDueDate.js
lib/ChangeDueDateDialog/ChangeDueDateDialog.js
lib/ChangeDueDateDialog/ChangeDueDateSuccess.js

Getting all the components that use `ChangeDueDateDialog` to properly update their list of loans and always pass it down correctly is:
1. Pretty unwieldy. It was fine with `OpenLoans` and the Users code, but the structure of the Check Out module makes it a stretch. 
1. While the above is possible, it's also not intuitive _why_ the parent components are fetching and refreshing the loans list.
Because of that and since CDDD has the best hooks on _when_ to execute refreshes, it now does the fetching itself. Upcoming PRs to ui-users and ui-checkout to handle this new setup.

ChangeDueDateDialog now fetches its own loans list

---

lib/ChangeDueDateDialog/ChangeDueDate.js

The warnings rendering was being done inside a ternary expression when it shouldn't have. Pulled it out to render unconditionally.

CDD: Always render warnings

---

lib/ChangeDueDateDialog/ChangeDueDate.js

Previously, if the selected loan(s) due date was in the past, the current date was used as the default due date in the Date picker. Changed this to leave the date field blank initially if all the due dates are in the past. This also implicitly disables the **Save** button until a date is selected.

UIU-497: Tweaked ChangeDueDate default date selection

---

lib/SearchAndSort/ConnectedSource/ApolloConnectedSource.js

The GraphQL resolvers autogenerated from RAMLs do things slighly
differently from the ones we wrote by hand. This change allows for
that, so that the `graphql` branch of ui-inventory will be able to run
against the auto-generated resolvers instead of the old hand-crafted
ones.

Get records and totalCount from correct places

---

lib/ChangeDueDateDialog/DueDatePickerForm.js
package.json

Related to https://github.com/folio-org/stripes-components/pull/424
Overriding the context's `timeZone` should be a clearer pattern than `ignoreLocalOffset`.

Use Datepicker and Timepicker timeZone props

---

lib/ChangeDueDateDialog/ChangeDueDate.js
lib/ChangeDueDateDialog/ChangeDueDateDialog.css
lib/ChangeDueDateDialog/ChangeDueDateDialog.js
lib/ChangeDueDateDialog/ChangeDueDateSuccess.js
package.json

Depends on folio-org/stripes-components#427
Removes hard-coded colours that were previously necessary when colouring an `<Icon>`

CDDD: Use new "status" prop for <Icon>s

---

lib/LocationSelection/LocationInput.js

`Selection` doesn't [pass back the event, just the new value](https://github.com/folio-org/stripes-components/blob/master/lib/Selection/SingleSelect.js#L261).

LocationInput: Fix onChange signature

---

lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

The purpose of this PR is to introduce a way for namespacing params used by `<SearchAndSort>` component. 
The implementation follows the document written by @MikeTaylor here:
https://github.com/folio-org/stripes-components/blob/master/util/parameterizing-makeQueryFunction.md

Add support for param namespacing. Part of STCOM-300

---

lib/ViewMetaData/ViewMetaData.js
package.json

`MetaSection` can now construct names itself so giving it the full user object and moving that functionality out of this component. Bumping required version as a result.
The API of `ViewMetaData` does _not_ change as a result.

STCOM-305 ViewMetaData: Use new MetaSection functionality

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
package.json

Cache user metadata so we don't look up the same values over and over.
Instead of looking up the same values over and over, cache the user
metadata. In order to avoid doing the same lookups of user metadata
multiple times, the results is stored in a cache. By storing a map of
user-id to user-object, we can avoid repeated lookups. If the twisty maze
of user metadata is all alike, only look up each user once. 
Refs [STCOM-308](https://issues.folio.org/browse/STCOM-308)

cache user metadata

---

lib/LocationLookup/LocationForm.js
lib/LocationLookup/LocationModal.js

I ran into a problem with the location lookup when adding locations to service points. Right after location has been added the service point form would also submit. This looks like a bug in `redux-form`. This PR tries to resolve it by moving the `handleSubmit` from the form tag down to the button.

Refactor location form submission. Part of UIORG-90

---

lib/ChangeDueDateDialog/ChangeDueDate.js
lib/EntryManager/EntryForm.js
lib/LocationLookup/LocationForm.js
lib/LocationLookup/LocationLookup.js
lib/LocationLookup/LocationModal.js
lib/LocationSelection/LocationSelection.js
lib/ProxyManager/ProxyForm.js
lib/ProxyManager/ProxyModal.js
lib/SearchAndSort/SearchAndSort.js
translations/stripes-smart-components/en.json

https://issues.folio.org/browse/STCOR-208
- Use `stripes` prop if already available, otherwise get it with `withStripes`
- Two new translation strings (`"Date"`, `"Time"`)
- `<LocationLookup>` prop rename: `temporary` -> `isTemporaryLocation` to make it more obvious
https://github.com/folio-org/ui-inventory/pull/219 uses `isTemporaryLocation` to fix the label.

STCOR-208: Context API

---

lib/SearchAndSort/SearchAndSort.css
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/components/ResetButton/ResetButton.css
lib/SearchAndSort/components/ResetButton/ResetButton.js
lib/SearchAndSort/components/ResetButton/index.js

We have discussed how to make the reset button less annoying (can't come up with a better way of saying it).
A solution we came up with is to transition the button in and out but with a slight delay. This makes it possible to check/uncheck fast (or uncheck one checkbox and check another) without having the entire list shift position immediately which could cause misclicks and frustration for the user.
The component is a standalone component that could be used in other places in the application but for now, it lives within this repo.

Adding transitioning reset button to SearchAndSort

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
package.json

Generation of HTML element-IDs in `<ConfirmationModal>` changed in
https://github.com/folio-org/stripes-components/commit/ce3ba8c996463a389ae3c3aeb36069d9a785ed69
and that broke a bunch of tests that relied on the old style of element
IDs. Happily, we can restore this behavior by passing in an ID prop that
matches the old format.
Refs [STCOM-317](https://issues.folio.org/browse/STCOM-317)

pass id prop to ConfirmationModal

---

CHANGELOG.md
package.json

Bumping the package version so repos that depend on tags can request it
by version number.
Refs [STSMACOM-113](https://issues.folio.org/browse/STSMACOM-113)

bumping package version for dependent repos

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
package.json

This lets us do custom validation by supplying a `validate` prop.
E.g., to prevent creating multiple records with the same `group`, we could validate as below:
```
<ControlledVocab
...
validate={(item, index, items) => ({
group: items.find((i, idx) => (i.group === item.group) && (idx !== index)) ? 'Duplicate!' : undefined,
})}
/>
```
Bumped version to 1.4.25

STSMACOM-114 ControlledVocab: Support custom validation

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
package.json

Don't call `Object.keys(null)`; that's an error.
Refs [STSMACOM-114](https://issues.folio.org/browse/STSMACOM-114)

validate error object before checking its keys

---

CHANGELOG.md
package.json

react-bootstrap >0.32.1 introduces a dependency on babel-runtime
^7.0.0-beta.42 that is incompatible with other modules in our system and
breaks the build. Locking onto v0.32.1 resolves the issue. Mad props to
@marcjohnson-kint for diagnosing this.
Refs [FOLIO-1425](https://issues.folio.org/browse/FOLIO-1425)

lock react-bootstrap version to avoid buggy deps

---

lib/SearchAndSort/SearchAndSort.js

This PR is to allow UI apps to pass the `actionMenuItems` prop to the SearchAndSort results pane. The prop enables a dropdown in the Pane header. This dropdown is where the Export To CSV action goes.

pass actionMenuItems prop to Results Pane

---

CHANGELOG.md
lib/ConfigManager/ConfigManager.js
package.json

Previously, the form would render immediately upon invocation and then
rerender when the settings resource returned. If you are fast with the
mouse, and I mean real fast like faster than The Waco Kid fast, or
maybe if you are a Nightmare test, you could click the submit button
between the first (pre-resource results) and second (post-resource
results) renders. Without an existing record with an id to coalesce into
([line 59](/folio-org/stripes-smart-components/blob/43394b2eaf41b7f45fa4b223d0171e5efed58de2/lib/ConfigManager/ConfigManager.js#L59)) we'll get a POST request instead of a PUT ([line 65](/folio-org/stripes-smart-components/blob/43394b2eaf41b7f45fa4b223d0171e5efed58de2/lib/ConfigManager/ConfigManager.js#L75)) that will
blow up when Okapi rejects the duplicate record.
This solves …

wait for settings query before rendering form

---

lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/index.js
lib/SearchAndSort/makeQueryFunction.js
lib/SearchAndSort/nsQueryFunctions.js
lib/SearchAndSort/parameterizing-makeQueryFunction.md
lib/SearchAndSort/readme.md

`makeQueryFunction` doesn't meet the definition of a purely presentational component (https://issues.folio.org/browse/STCOM-298), since it's coupled to `stripes-connect` (and thus requires a redux store). Its most logical new home is in `stripes-smart-components`, with `SearchAndSort`. `makeQueryFunction`'s sibling `nsQueryFunctions` tagged along. Also includes readme and documentation moves.
https://issues.folio.org/browse/STCOM-332
Used `git-subtree` to preserve as much git history for these files as possible from `stripes-components`. The commit history didn't come out quite as clean on this one, since I had to grab the whole `stripes-components/util` directory and whittle it down.

STCOM-332 Move makeQueryFunction

---

lib/ControlledVocab/ControlledVocab.js
lib/EditableList/EditableItem.js
lib/EditableList/EditableList.css
lib/EditableList/EditableList.js
lib/EditableList/EditableListForm.js
lib/EditableList/ItemEdit.js
lib/EditableList/ItemView.js
lib/EditableList/index.js
lib/EditableList/readme.md

`EditableList` doesn't meet the definition of a purely presentational component (https://issues.folio.org/browse/STCOM-298), since it's dependent on a redux store. It's used by more than one `folio-org` repo, so its most logical new home is in `stripes-smart-components`.
https://issues.folio.org/browse/STCOM-328
Used `git-subtree` to preserve as much git history for these files as possible from `stripes-components`. `EditableList` was recently moved out of `lib/structures` - unfortunately `git-subtree` didn't preserve any history before that move.

STCOM-328 Move EditableList

---

lib/Settings/Settings.css
lib/Settings/Settings.js
lib/Settings/index.js
lib/Settings/readme.md

`Settings` doesn't meet the definition of a purely presentational component (https://issues.folio.org/browse/STCOM-298), since it's coupled to `stripes-connect`. Its most logical new home is in `stripes-smart-components`.
https://issues.folio.org/browse/STCOM-330
Used `git-subtree` to preserve as much git history for these files as possible from `stripes-components`.

STCOM-330 Move Settings

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Previously, the row URL created while on a page like `/finance/funds` or `/finance/ledgers` would be `/finance/view/123` for both of them and thus fail to render the correct thing when right-click-open-in-new-tabbing.
This uses the matched part of the path of the SAS's parent which should always be the full route to the app/subapp but it won't include the `/view/1234` part of the path because that's a nested child route.

Fixed SearchAndSort row URL creation for subapps

---

package.json

Should help cut down on these warnings:
```
warning "@folio/stripes-smart-components > @folio/stripes-form@0.8.2" has unmet peer dependency "stripes-core@^2.7.0".
warning "@folio/stripes-smart-components > @folio/stripes-form > @folio/stripes-components@2.0.0" has unmet peer dependency "stripes-core@^2.7.0".
warning "@folio/stripes-smart-components > @folio/stripes-form > @folio/stripes-components > @storybook/addon-knobs@3.4.10" has unmet peer dependency "@storybook/addons@^3.3.0".
warning "@folio/stripes-smart-components > @folio/stripes-form > @folio/stripes-components > @storybook/addon-actions@3.4.10" has unmet peer dependency "@storybook/addons@^3.3.0".
```
`stripes-form@0.8.2` was still requesting `stripes-components@2`.

Update to new stripes-components and stripes-form releases

---

CHANGELOG.md
translations/stripes-smart-components/en.json

Updated localized string 'searchResultsCountHeader' to use sentence casing.
Issue: https://issues.folio.org/browse/STCOM-339

STCOM-339: Update 'searchResultsCountHeader' to use sentence casing

---

lib/AddressFieldGroup/AddressEdit/AddressEdit.js
lib/AddressFieldGroup/AddressList/AddressList.js
lib/EditableList/EditableList.js
lib/EntryManager/EntryWrapper.js
lib/SearchAndSort/SearchAndSort.js

Lodash is notorious for delivering way more code to the bundle than might actually be needed.
We should avoid importing all of lodash. Both of these are better options:
```
import get from 'lodash/get';
```
or 
```
import { get } from 'lodash';
```
I haven't confirmed that the second option above appropriately tree-shakes. The first is optimal with our stack.
- https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark
- https://stackoverflow.com/questions/35250500/correct-way-to-import-lodash

Adjust lodash imports

---

package.json

Cleans up
```
warning " > @folio/stripes-smart-components@1.8.3" has incorrect peer dependency "@folio/stripes-logger@^0.0.2".
```

Update stripes-logger peer dependency to 1.0.0

---

lib/AddressFieldGroup/AddressList/AddressList.js
lib/AddressFieldGroup/AddressView/AddressView.js
lib/EditableList/EditableListForm.js
lib/ProxyManager/ProxyModal.js

The `stripes-components` [`injectIntl()`](https://github.com/folio-org/stripes-components/tree/master/lib/InjectIntl) was only intended to fix issues with React 16.3+ ref forwarding. It does not appear to be needed for any of these components - instead we can use the upstream `react-intl` version of `injectIntl()`.

Use upstream injectIntl()

---

.stylelintrc
lib/AddressFieldGroup/AddressEdit/AddressEdit.css
lib/PasswordStrength/PasswordSrength.css
package.json

Removes address field group delete hover state for now - it was a tricky `no-descending-specificity` violation with some `global` business that probably shouldn't happen.

Turn on stylelint in CI

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

https://issues.folio.org/browse/STSMACOM-131
This PR introduces a new prop called `getHelperResourcePath` which can be used to resolve helper's resource path dynamically. 
example usage:
````js
<SearchAndSort 
getHelperResourcePath={(helper, id) => `finance/ledger/${id}`} 
...
/>
````

Introduce getHelperResourcePath prop. Fixes STSMACOM-131 

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

`craftLayerUrl()` assists with `<SearchAndSort>`'s routing, and will be deprecated for any other use (modules should define their own routes, instead of relying on `<SearchAndSort>` to do it for them).

Copy craftLayerUrl into SearchAndSort

---

lib/AddressFieldGroup/AddressEdit/AddressEdit.css
lib/AddressFieldGroup/AddressView/AddressView.css
lib/Notes/Notes.css

`stripes-components` CSS variables are now all kebab-case, not camelCase.
Follow up to https://github.com/folio-org/stripes-smart-components/pull/300

Change css vars to kebab-case

---

lib/SearchAndSort/SearchAndSort.js

`Pane` and `PaneHeader` threw errors because they expect a React Component, which an empty string is not.

Changed null components to satisfy proptypes

---

lib/AddressFieldGroup/AddressEdit/AddressEdit.css
lib/PasswordStrength/PasswordSrength.css
lib/ProxyManager/ProxyForm.css
lib/SearchAndSort/components/NoResultsMessage/NoResultsMessage.css

Updates every `font-size` declaration to use the `font-size-*` variables defined in `stripes-components`.

Only use font-size variables

---

lib/LoanList/LoanList.js

We can use `react-intl`'s `formatTime()` with options to show a date instead of the soon-to-be-deprecated `formatDateTime()` on the `stripes` god object.

STCOR-267 Use react-intl formatTime instead of stripes.formatDateTime

---

CHANGELOG.md
lib/AddressFieldGroup/AddressList/AddressList.js
lib/AddressFieldGroup/AddressView/AddressView.js
lib/ChangeDueDateDialog/ChangeDueDate.js
lib/ChangeDueDateDialog/ChangeDueDateDialog.js
lib/ChangeDueDateDialog/ChangeDueDateSuccess.js
lib/ChangeDueDateDialog/DueDatePicker.js
lib/ConfigManager/ConfigManager.js
lib/ControlledVocab/ControlledVocab.js
lib/EditableList/EditableListForm.js
lib/EntryManager/EntryForm.js
lib/EntryManager/EntryWrapper.js
lib/LoanList/LoanList.js
lib/LocationLookup/LocationForm.js
lib/LocationLookup/LocationLookup.js
lib/LocationLookup/LocationModal.js
lib/LocationSelection/LocationSelection.js
lib/Notes/NoteRenderer.js
lib/Notes/Notes.js
lib/Notes/NotesForm.js
lib/ProxyManager/ProxyForm.js
lib/ProxyManager/ProxyModal.js
lib/SearchAndSort/SearchAndSort.js
lib/Tags/Tag.js
lib/Tags/Tags.js
lib/Tags/TagsForm.js

Retrieving the intl object from the `stripes` god object (`stripes.intl`) is a deprecated pattern.
Sets some repo-wide conventions:
- Don't use `stripes.intl`
- When using `injectIntl()` that injects an `intl` prop, destructure `intl`
- Don't try to alias `formatMessage()` and its siblings; instead use destructuring to achieve brevity
- Always specify what parts of `props.stripes` are being used in the prop type validation

STCOR-267 Use react-intl directly instead of stripes.intl

---

lib/SearchAndSort/SearchAndSort.js

This PR fixes the issue described in https://issues.folio.org/browse/UIPFU-11
by hiding the details pane in `SearchAndSort` when `browserOnly` mode is on (which is set to true in plugin-find-user).

Hide details pane in browser only mode. Part of UIPFU-11

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js

It used to be the case that if you tried to run a query with an index
that didn't exist the parser would realize this and just ignore the
index. Now, it throws a query validation exception. Probably, this is a
good thing; it's good to be strict about what we're running. But at this
late stage, when things were working forever, it feels like you're just
about to submit your problem set and along comes the TA who says, "You
know you have to compile with '-Wall', right?" <sigh>
Refs [MODUSERS-98](https://issues.folio.org/browse/MODUSERS-98)

don't sort ControlledVocabulary queries

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
package.json

I added `this.metadataCache` a long time ago but it never worked. I had
one of those face-palm moments: it didn't work because
`renderLastUpdated` uses `<UserLink>`, which calls connect. You
shouldn't call connect in render because it'll be called every single
time. Duh. Internalizing the `<UserLink>` logic eliminates that problem
and allows the cache to work correctly.
Fixes [STSMACOM-142](https://issues.folio.org/browse/STSMACOM-142)

internalize UserLink to enable caching

---

CHANGELOG.md
lib/Settings/Settings.js

Settings layouts can be difficult to compose with multiple layers of `<Paneset>`s.
Part of https://issues.folio.org/browse/STCOM-387
Move away from nested `<Paneset>`s.
[`UINavigationController`](https://developer.apple.com/documentation/uikit/uinavigationcontroller), which `<Paneset>` is inspired by, cannot be nested. A stack of UI screens can only be one-deep. 
This was the only instance left in the `folio-org` (besides the deprecated `ui-scan`) of a `<Paneset>` using a `nested` prop.
This change might affect percentage widths set by some panes, but it did not seem to have too much impact.

STCOM-387 Remove Paneset from Settings

---

lib/ConfigManager/ConfigForm.js
lib/EntryManager/EntryWrapper.js
lib/SearchAndSort/SearchAndSort.css
lib/SearchAndSort/SearchAndSort.js

Request from @filipjakobsen; moves the search button `0.5rem` closer to the search field, so their relationship is clearer. Removes the `<hr />`.

 Adjust search form styles

---

lib/SearchAndSort/SearchAndSort.js

It looks like the query resource (which sits in the redux store) was not cleaned up properly when `SearchAndSort` was unmounted. This PR cleans the query resource during `componentWillUnmount ` lifecycle.

Clear query resource on component unmount. Fixes STSMACOM-146

---

lib/SearchAndSort/SearchAndSort.js
package.json
translations/stripes-smart-components/ca.json
translations/stripes-smart-components/da.json
translations/stripes-smart-components/de.json
translations/stripes-smart-components/en.json
translations/stripes-smart-components/es.json
translations/stripes-smart-components/es_ES.json
translations/stripes-smart-components/fr.json
translations/stripes-smart-components/fr_FR.json
translations/stripes-smart-components/hu.json
translations/stripes-smart-components/it_IT.json
translations/stripes-smart-components/pt_BR.json
yarn.lock

Stops screen readers from announcing "plus": https://issues.folio.org/browse/STCOM-391

STCOM-391 Use plus-sign icon instead of + character

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

For `<SearchAndSort>`, uses the preferred (and future-friendly) `react-intl` API, `<FormattedMessage>`, since there was no reason to fall back to `intl.formatMessage()` with `injectIntl()`.

Replace formatMessage() with FormattedMessage in SearchAndSort

---

lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js
lib/AddressFieldGroup/AddressList/AddressList.js
lib/AddressFieldGroup/AddressView/AddressView.js
lib/ChangeDueDateDialog/ChangeDueDate.js
lib/ChangeDueDateDialog/ChangeDueDateDialog.js
lib/ChangeDueDateDialog/DueDatePicker.js
lib/ControlledVocab/ControlledVocab.js
lib/EditableList/EditableListForm.js
lib/EntryManager/EntryForm.js
lib/EntryManager/EntryWrapper.js
lib/LoanList/LoanList.js
lib/LocationLookup/LocationForm.js
lib/LocationLookup/LocationLookup.js
lib/LocationLookup/LocationModal.js
lib/LocationSelection/LocationSelection.js
lib/Notes/NoteRenderer.js
lib/Notes/Notes.js
lib/Notes/NotesForm.js
lib/ProxyManager/ProxyForm.js
lib/ProxyManager/ProxyModal.js
lib/Tags/Tag.js
lib/Tags/Tags.js
lib/Tags/TagsForm.js

Finishes the work from https://github.com/folio-org/stripes-smart-components/pull/329. Applied to `stripes-components` in https://github.com/folio-org/stripes-components/pull/696.
Aligns with `stripes` i18n documentation at https://github.com/folio-org/stripes/blob/master/doc/i18n.md, in preferring the `react-intl` component API instead of its functions with `injectIntl()`.
- Exclusively use `<FormattedMessage>`, `<FormattedDate>`, and `<FormattedTime>` from `react-intl`. 
- Discontinue using `intl.formatMessage()`, `intl.formatDate()`, and `intl.formatTime()`.
- I had to leave two `injectIntl()`s - one is in the deprecated `NoteRenderer`, and the other is in `DueDatePicker`. At some point, `DueDatePicker`'s date handling should be re-evaluated to see if can just use `<FormattedDate>`. …

Replace all formatMessage() with <FormattedMessage />

---

CHANGELOG.md
lib/EntryManager/EntryWrapper.js

`clickable-create-${foo}` was already used elsewhere. Now it's used
here, too.

use consistent create-new-button id attribute

---

lib/AddressFieldGroup/AddressEdit/AddressEditList.js
lib/AddressFieldGroup/AddressList/AddressList.js
lib/ConfigManager/ConfigForm.js
lib/ConfigManager/ConfigManager.js
lib/ControlledVocab/ControlledVocab.js
lib/EditableList/EditableListForm.js
lib/EntryManager/EntryForm.js
lib/EntryManager/EntryWrapper.js
lib/LocationLookup/LocationLookup.js
lib/SearchAndSort/SearchAndSort.js
lib/Settings/Settings.js

Props that are simply rendered like `label` or `paneTitle` should accept any renderable node, not just a string, so we can pass in `react-intl` `<FormattedMessage>`, etc.
Prevents warnings like:
```
Warning: Failed prop type: Invalid prop `sections[0].label` of type `object` supplied to `Settings`, expected `string`.
```

Update renderable props to type node

---

CHANGELOG.md
lib/EntryManager/EntryWrapper.js

Sometimes, Nightmare tests would blow up with the following error:
```
EntryWrapper.js:145 Uncaught (in promise) TypeError: Cannot read property 'sendCallout' of null
```
which is the result of the delete method being called before the whole
DOM renders, which causes the callout to fail because it relies on a ref
which isn't available yet because the DOM hasn't rendered. Got that?
Good.

validate callouts before calling them

---

lib/AddressFieldGroup/AddressEdit/AddressEdit.css
lib/AddressFieldGroup/AddressEdit/AddressEditList.js
lib/SearchAndSort/SearchAndSort.js
translations/stripes-smart-components/en.json

According to [this](https://issues.folio.org/browse/STSMACOM-145) story, "Add address" button should be aligned to the left so that the label text and position for this type of button follow the latest general FOLIO style guidelines:

STSMACOM-145: Update text and position of "+ Add address" button on User record

---

lib/ControlledVocab/ControlledVocab.js

While working on https://issues.folio.org/browse/UIU-679, @Godlevskyi noticed that passing in `<FormattedMessage>` nodes to some `<ControlledVocab>` props would cause incidents of `[Object object]` making their way to the outputted UI.
For `labelSingular` in particular, `<ControlledVocab>` would attempt to transform the given already-localized string to lower case. This probably will not scale to languages with different capitalization rules than English (like German). We shouldn't be doing any transformations of the strings provided by translators.
- Accept `node` prop type for `label`, `labelSingular`, and `objectLabel`
- Stop attempting to change capitalization of already-localized strings
- Change confirmation modal id to use `nameKey` prop instead of a transformed `labelSingular`
- …

UIU-679 Update label propTypes

---

CHANGELOG.md
lib/EntryManager/EntryForm.js
lib/EntryManager/EntryWrapper.js

`<EntryManager>` now uses `clickable-create-entry`,
`clickable-delete-entry`, and `clickable-edit-entry` for its buttons'
`id` attributes. That's consistent and not based on a prop which could
be based on a translated string.
Refs [UIU-679](https://issues.folio.org/browse/UIU-679)

use consistent id attributes for EntryManager

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

It looks like this was yet another weird issue with redux-form. The `onSubmit` handler in SearchAndSort form was also executing the UserForm `onSubmit` handler here:
https://github.com/folio-org/ui-users/blob/master/src/UserForm.js#L197
This PR just replaces the `onSubmit` with `onClick` since we don't really need to submit the SearchAndSort form. This seems to fix the issue in UserForm but it's still not clear why the UserForm `onSubmit` would execute.

Add stopPropagation to search form. Refs UIU-731

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

When user lookup (ui-plugin-find-user) was closed / unmounted the `SearchAndSort` was reseting the query resource completely including initial / default values (for example `sort` by name). This PR is trying to address that by reseting it to initial values. 
https://issues.folio.org/browse/UIU-733

Reset query resource to initial values on unmount. Refs UIU-733

---

lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/components/SearchButton/SearchButton.css
lib/SearchAndSort/components/SearchButton/SearchButton.js
lib/SearchAndSort/components/SearchButton/index.js

Regarding [STSMACOM-133](https://issues.folio.org/browse/STSMACOM-133), arrow icons should be applied to magnifying glass to indicate the state of the searching pane. The existence of badge should be taken into the account (when filters are applied). 
_Animation for pane will be applied later._
- Add arrow icons to stripes-components [STCOM-407](https://github.com/folio-org/stripes-components/pull/731).
- Create `<SearchButton> `component, where the icons are applied.
- Add animation for the icons.
Without animation
:

STSMACOM-133: Apply arrows for magnifying glass

---

lib/SearchAndSort/SearchAndSort.js

React component names must begin with capital letters (or alternatively they can be accessed via props).

Uppercase editRecordComponent

---

CHANGELOG.md
package.json

* Add stopPropagation to search from. Refs UIU-731.
* Reset query resource to initial values on unmount. Refs UIU-733.
* Move `<EntrySelector>` from `stripes-components`
* Removed deprecated actionMenuItems-prop. Fixes STSMACOM-147.

Release v1.12.0

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
lib/EditableList/EditableListForm.js
package.json

Labels may be strings or `<FormattedMessage>` components containing
translated strings. Accept either.

be less strict with label prop-types

---

lib/SearchAndSort/SearchAndSort.js
translations/stripes-smart-components/en.json

The search field was unlabled, so Axe was pinging us.
Previously, JAWS would only say "Edit, type-in text" when the search field was focused.
Applied aria-label "Search {moduleName}".

Add aria-label to SearchField

---

CHANGELOG.md
lib/EntryManager/EntrySelector.js

The `noOverflow` was causing scroll bars to disappear on the `EntryManager` setting pages.
https://issues.folio.org/browse/UIU-764

Remove noOverflow from EntrySelector list pane. Refs UIU-764.

---

package.json
yarn.lock

Dependency no longer in use by `stripes-smart-components`.

Remove react-intl-formatted-xml-message

---

CHANGELOG.md
lib/UserLink/UserLink.js

UserName should be deprecated too, but putting a `console` statement in
`render` for a component that isn't actually in use felt like overkill.
Refs [STRIPES-577](https://issues.folio.org/browse/STRIPES-577)

label UserLink as deprecated

---

lib/SearchAndSort/components/SearchButton/SearchButton.css
lib/SearchAndSort/components/SearchButton/SearchButton.js

**Ticket:** https://issues.folio.org/browse/STSMACOM-157
- Fixed over the edge bleed
- Added small opacity transition
- Changed sizing to match other pane header icons
- Replaced pixel for rem values and applied CSS variables

STSMACOM-157: Minor fixes for SearchButton

---

lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

https://issues.folio.org/browse/STSMACOM-160
Make SearchAndSort component more flexible in case of filters. This allows creating a specific set of filters for each UI module in a declarative way.
- add new props: `renderFilters` and `onFilterChange`
- add a condition to execute `renderFilters` when it exists or to render `FilterGroups` component as it was before. Is necessary to avoid breaking changes.
- update readme

STSMACOM-160: Add renderFilters support

---

index.js
lib/SearchAndSort/components/MultiSelectionFilter/MultiSelectionFilter.js
lib/SearchAndSort/components/MultiSelectionFilter/index.js
lib/SearchAndSort/components/MultiSelectionFilter/tests/MultiSelectionFilter-test.js
lib/SearchAndSort/readme.md

https://issues.folio.org/browse/STCOM-439
Create a reusable multiselection filter, based on MultiSelection component, to be used in SearchAndSort side panel.
- create `onChangeHandler` which will raise filter name and selected values after a filter change.
- add a couple of props
- add tests only specific for this component

STCOM-439: Add multiselection filter

---

index.js
lib/SearchAndSort/components/CheckboxFilter/CheckboxFilter.js
lib/SearchAndSort/components/CheckboxFilter/index.js
lib/SearchAndSort/components/CheckboxFilter/tests/CheckboxFilter-test.js
lib/SearchAndSort/components/CheckboxFilter/tests/interactor.js

https://issues.folio.org/browse/STCOM-440
Create a reusable checkbox filter, based on Checkbox component, to be used in SearchAndSort side panel. Presents a set of checkboxes working like one filter.
- create `onChangeHandler` which will raise filter name and selected values after a filter change.
- add a couple of props
- add tests only specific for this component

STCOM-440: Add checkbox filter

---

lib/EntryManager/EntryWrapper.js

This PR fixes an issue with the unsaved changes reported in https://issues.folio.org/browse/STCOM-302
It replaces a `mutator.query.update` with `history.push`. This plays well with react-router and stripes-form and it should fix an issue recorded by Ann-Marie:
https://issues.folio.org/secure/attachment/15610/Get%20Stuck%20trying%20to%20cancel%20Continue%20Editing.mp4
Ideally we should try to move away from managing routing via `mutator.query.update` and replace it with `history` and `<Link>`.

Replace mutator.query.update with history.push. Part of STCOM-302

---

lib/SearchAndSort/components/CheckboxFilter/CheckboxFilter.js

`Checkbox` passes its props down to the `<input type="checkbox">` and React complains when we tell it to render `dataOptions` and `selectedValues` to the DOM.
@Yurii-Danylenko, there may be a similar change needed for `MultiSelectionFilter` but I haven't looked yet and am just using `CheckboxFilter` right now. Feel free to look into it if you want, otherwise I'll find/fix it when I do get around to using those later this week or the week after next (am on vacation next week).

CheckboxFilter: Stopped rendering some props to DOM

---

lib/AddressFieldGroup/AddressEdit/AddressEdit.css

The font size of the radio button in AddressFieldGroup was incorrect
Relates to [STCOM-414](https://issues.folio.org/browse/STCOM-414), [STSMACOM-156](https://issues.folio.org/browse/STSMACOM-156)

STSMACOM-156: fix font size of radio button in AddressFieldGroup

---

CHANGELOG.md
lib/SearchAndSort/components/CheckboxFilter/CheckboxFilter.js

The refactoring in folio-org/ui-search/pull/128 inadvertently removed predictable id attributes
from checkboxes. This made it very difficult for Nightmare tests to
programmatically interact with filters. This PR restores predictable ids.
Refs [UISE-97](https://issues.folio.org/browse/UISE-97).

restore predictable ids to CheckboxFilter elements

---

index.js
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/buildUrl.js

This PR does something very similar to what was done in https://github.com/folio-org/stripes-smart-components/pull/394 but in SearchAndSort.
It should solve the issue reported in https://issues.folio.org/browse/STCOM-302
It also takes us one step closer to not rely on https://github.com/folio-org/stripes-core/blob/master/src/locationService.js#L53 for routing.  
@VictorSoroka1 would you mind giving it a try in your copy of SearchAndSort and see if you can reproduce the STCOM-302 issue?

Replace query resource with history push. Refs STCOM-302

---

lib/SearchAndSort/SearchAndSort.js

Unfortunately the previous PR #429 doesn't work well when SearchAndSort is used via plugin (for example when we perform users lookup from the checkout screen). This PR goes back to what we had previously (rely on query resource) for those case.

Fix search when SearchAndSort is used via plugin. Refs STCOM-302

---

lib/SearchAndSort/SearchAndSort.js

This is a follow-up ticket for:
https://github.com/folio-org/stripes-components/pull/894
Once the above STCOM-473 is merged we can merge this change in.

STSMACOM-167: Passing <AppIcon> component instead of an object to <Pane>

---

CHANGELOG.md
lib/SearchAndSort/components/NoResultsMessage/NoResultsMessage.js
translations/stripes-smart-components/en.json

`SearchAndSort` contained some untranslated, hard-coded strings.
Fixes [STSMACOM-169](https://issues.folio.org/browse/STSMACOM-169)

extract strings for translation

---

lib/SearchAndSort/SearchAndSort.js

The message is translatable and therefore will be provided as a
`<FormattedMessage>`, not a `string`.

correct PropType for notLoadedMessage

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

The previous implementation was replacing query resource with the initial query on `componentWillUnmount`. This is required when `SearchAndSort` is used via plugin in order to clean the filters when the plugin is reopened again. For example:
1. Open `find user plugin` and perform search
2. Choose user and close the plugin
3. Open `find user plugin` again 
4. The filters from `#1` should not be visible.
Unfortunately this also started causing issues in https://issues.folio.org/browse/ERM-72 when there are multiple instances of `SearchAndSort` being used in the same module.
This PR is an attempt to fix it.

Only clear resource query when SearchAndSort runs in a plugin mode. Refs ERM-72

---

CHANGELOG.md
lib/ViewMetaData/ViewMetaData.js
lib/ViewMetaData/readme.md
translations/stripes-smart-components/en.json

Make sure `ViewMetaData` component source fields for updated and created lines renders correctly for the record created by System
Check the passed id from metadata and if it contains only zeros then assume that this is System. In that case component will not make unnecessary http request and will render system user wich has a default value "System" or can be passed as a property.
Before:
After:

UIDATIMP-156: change ViewMetaData component

---

lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/components/ResetButton/ResetButton.css
lib/SearchAndSort/components/ResetButton/ResetButton.js

https://issues.folio.org/browse/STCOM-488
Disable reset button when search field is empty or there is no selected filters
- Add a condition to make the button disabled
- Delete animation wrapper with styles for the button

STCOM-488: Remove disappering of the reset button and animation. Reset button disables when search string is empty or at least one filter is choosen

---

index.js
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

The current helper components are hard coded in SearchAndSort. This worked fine for what we needed in the past but we are now running into a situation where a different implementation of the Tags component may be potentially used by the ERM team. 
This PR introduces a way to use a custom implementation of the given helper app without breaking our previous implementation (used in ui-users and ui-requests).

Add getHelperComponent to SearchAndSort

---

lib/SearchAndSort/SearchAndSortQuery.js
lib/SearchAndSort/SearchAndSortQuery.md

- Only apply whatever's passed into the function to the `filterFields` slice of state.
- Fixed documentation of `activeFilters` type.

SASQ: Scope filter/search state changes to their slices

---

lib/SearchAndSort/SearchAndSortQuery.js

`filterHandlers.clearGroup()` currently clears _all_ the `filterFields` because `setState` doesn't expand nested properties all the way down. By expanding the current `filterFields` we retain other filter groups.
I extended this to `onChangeSearchEvent` and `onChangeSearchValue` because it looked like they might suffer from the same quirks.
Also, `clearGroup` sets the filter group to an empty array but `buildFiltersString` doesn't handle empty arrays properly and tries to set filters like `undefined.value`. Added a `.filter` to skip empty filter groups.

SASQ: Only clear the filter group passed in

---

CHANGELOG.md
lib/EntryManager/EntrySelector.js

It's much easier to write integration tests when page elements have
unique attributes.
Refs [UICIRC-237](https://issues.folio.org/browse/UICIRC-237)

provide element ids to assist with tests

---

lib/SearchAndSort/SearchAndSort.js
translations/stripes-smart-components/en.json

The new-entry layer was missing the `contentLabel` prop, necessary for
adequate a11y labeling.

provide a11y props to Layer

---

CHANGELOG.md
package.json

- Fulfills STRIPES-564 and STRIPES-581. 
- Tested with sample "Hello World" UI app.
Before:
After:

STRIPES-581 Set sideEffects to false to enable tree-shaking

---

CHANGELOG.md
lib/LocationLookup/LocationForm.js

lodash's `sortBy` is case sensitive, so we gotta work around that.
Fixes [STSMACOM-192](https://issues.folio.org/browse/STSMACOM-192)

case insensitive sort

---

lib/ControlledVocab/ControlledVocab.js

The actual code already allows for the situation where no value is
passed in for `records`, i.e. the top level of the JSON returned from
the WSAPI is an array of records rather than an object containing a
member whose value is this array. Since this works correctly, a valid
invocation should not yield a console error.

Remove .isRequired from 'records' propType

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
package.json

A client may want to override the default behavior when closing a new
record. Now, they can.
Refs [UIREQ-244](https://issues.folio.org/browse/UIREQ-244)

accept props.onCloseNewRecord

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
package.json

When this is turned on, a caller can pass in a falsy value such as an empty string to modify the behaviour of stripes-connect, allowing the back-end module to provide the ID of newly created records. This allows `<ControlledVocab>` to work correctly with back-end modules such as mod-rs and mod-directory created using Knowledge Integration's toolkit.
The `clientGeneratePk` prop explicitly defaults to true, matching the previous implicit default.
Requires stripes-connect ^5.1.2.

Pass clientGeneratePk prop into manifest option

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
package.json

This parameter is called `limit` for RMB-based modules, but `perPage` for K-Int's ReShare modules. So when running against the lattr, we need to invoke `<ControlledVocab>` with `limitParam="perPage"`.
(The default behaviour is of course unchanged.)

Support optional `limitParam` prop

---

lib/EntryManager/EntrySelector.js

PR #494 introduced some new markup required for unit-tests that wrapped
the child element of a list in a `div`. This means we need to move the
`key` attribute up from the child to the wrapper.

lift key attribute up in markup

---

lib/EntryManager/EntryManager.js
lib/EntryManager/EntrySelector.js
package.json

Wrapping the `<EntryManager>` element in a `<div>` in order to provide a
`data-test-*` attribute caused CSS trouble in `<Paneset>`s. Now that
`<Paneset>` spreads the `data-*` props it receives to its top-level
element, we can pass that value directly on `<EntrySelector>` without
needing to wrap it.
Refs [STCOM-527](https://issues.folio.org/browse/STCOM-527), [UIORG-166](https://issues.folio.org/browse/UIORG-166)

pass data-* props directly, not in a wrapper

---

lib/Notes/NavigationModal/navigation-modal.js
lib/Notes/NoteForm/NoteForm.js

`NavigationModal` component has a button with `type=submit`. This makes it impossible to use the component inside forms. This small PR add `e.stopPropagation()` to the `NavigationModal` submit handler so that the modal can be used inside forms without risks to break things.
I also placed `NavigationModal` near the `form` element, because in this particular case there are no reasons to keep it inside `form`.

STSMACOM-200: make NavigationModal possible to use inside forms

---

lib/ControlledVocab/ControlledVocab.js

I noticed that we often pass `id` to `ControlledVocab` for example: 
https://github.com/folio-org/ui-tenant-settings/blob/master/src/settings/LocationLibraries.js#L185
but that id is never present. I needed it to finalize testing in:
https://issues.folio.org/browse/UIORG-163

Add id and data-test attributes to ControlledVocab. Part of UIORG-163

---

lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

https://issues.folio.org/browse/UIOR-27
purpose: we need a place to put navigation buttons in the first column
approach: new render prop
related https://github.com/folio-org/ui-orders/pull/405

UIOR-27 navigation for SearchAndSort

---

lib/ControlledVocab/ControlledVocab.js

**ticket**: https://issues.folio.org/browse/UINV-6
**purpose**: tenant addresses will work with `mod-configs` and this module supports only `value` field. In this case value will be a JSON of `name` and  `address` so we need a way to parse value to work with this component in right way
**approach**: new property to parse row
related to https://github.com/folio-org/ui-tenant-settings/pull/17

UIINV-6 support row parse

---

lib/Notes/NoteForm/NoteForm.js

This small PR adds forgotten `onToggle` function call to dropdown item click handler

Fix bug with unclosing note form dropdown

---

lib/Notes/components/NoteForm/NoteForm.js
lib/Notes/components/NoteForm/components/NoteFields/NoteFields.css
lib/Notes/components/NoteForm/components/NoteFields/NoteFields.js
translations/stripes-smart-components/en.json

On the note create page, when there are no note types created, a toast notification telling the user to create a note type will be displayed. Also the form fields and submit button will be disabled.

STSMACOM-211: fix NoteForm crashing when no note types exist

---

CHANGELOG.md
lib/SearchAndSort/makeQueryFunction.js

This PR allows for passing `queryTemplate` as a function to `makeQueryFunction`. This change is required to support work described in https://issues.folio.org/browse/UIU-1068 and https://github.com/folio-org/ui-users/pull/837

Allow for passing queryTemplate as a function to makeQueryFunction

---

lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

https://issues.folio.org/browse/UIOR-292
purpose: have an option to disable sorting for columns
approach: new property that defines list of columns that can be sorted

UIOR-292 disable sorting for columns in SearchAndSort

---

index.js
lib/Tags/Tags.js
lib/Tags/TagsAccordion.js
lib/Tags/TagsForm.js
lib/Tags/index.js

Jira ticket: https://issues.folio.org/browse/UIDATIMP-10
The purpose of this PR is to add `TagsAccordion` component to provide an ability to use tags in an accordion (like in `ui-eholdings` module).
The PR also includes:
1) a bug fix for displaying a toast when creating a new tag;
1) code refactoring for the `Tags` and `TagsForm` components.
1) a "render props" support for `Tags` component to provide a way to use tags independently of a markup.
Note: there is a "refreshRemote"-hack in the `componentDidUpdate` method in `Tags` component. It is needed to update resources when the `link` prop changes and it should be removed when https://issues.folio.org/browse/STCON-81 is done.

UIDATIMP-10: add TagsAccordion component

---

CHANGELOG.md
lib/ChangeDueDateDialog/ChangeDueDate.js
lib/ChangeDueDateDialog/ChangeDueDateDialog.js

This PR fixes `ChangeDueDateDialog` flickering right after due date is changed. 
https://issues.folio.org/browse/UIU-1065

Fix ChangeDueDateDialog flickering during due date change. Part of UIU-1065

---

lib/ControlledVocab/ControlledVocab.js

This is a double fix. First, I incorrectly specified it as type string
rather than arrayOf(string). But also, it seems that early in the
lifecycle it gets furnished to this component as an empty _object_
rather than array -- I suspect because this is stripes-connect's
default. So we use oneOfType to accept either.

*sigh* fix propTypes declaration for resources.updaterId

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
lib/ControlledVocab/actuators-refdata.js
lib/ControlledVocab/tests/ControlledVocab-test.js
lib/ControlledVocab/tests/actuators-refdata-test.js
package.json

Until now, the set of values maintained using `<ControlledVocab>` have all been CRUDable. But for the ReShare project immediately (and down the line for FOLIO's ERM modules) we need to also maintain controlled vocabularies using Knowledge Integration's Refdata API, documented at https://github.com/openlibraryenvironment/ui-directory/blob/master/doc/refdata-api.md
These changes make that possible. They abstract out the actual WSAPI operations performed by `<ControlledVocab>` into an "actuator", which is merely a set of three named functions (onCreate, onDelete and onUpdate). The existing functions are packaged into an anonymous actuator that behaves exactly as before. But if the new optional `actuatorType` prop is set to `'refdata'`, then a new actuator is used that works with the Refdata …

Changes required to handle the Refdata API

---

translations/stripes-smart-components/en.json

Per https://issues.folio.org/browse/STSMACOM-216 we need to fix plural handling for notes.found key
Made updates accordingly based on https://github.com/folio-org/stripes/blob/master/doc/i18n.md#details and other examples.
I did not find `notes.found` key in use yet when searching folio-org for `stripes-smart-components.notes.Found` - so possible alternative solution would be to remove this translation key.

STSMACOM-216 - Fix Plural handling in notes.found key

---

lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js

Accordion's `displayWhenOpen` prop is expected to be a react element. Currently, in some cases, `false` (which is not a react element) is passed to Accordion by NotesAssigningModal. In this PR, I've replaced `false` with `null`.

UIEH-742: change NotesAssigningModal to pass correct props to accordion

---

lib/EditableList/ItemEdit.js

When a duplicate term is entered in controlled vocab CRUD component in Settings, the addition silently fails. It's good that it fails, but there should be some messaging that it failed because it was not unique. This applies in e.g. Settings > Inventory > Holdings, Holdings type, and Settings > Inventory > Instance, Holdings, Item > Call number type and more (basically everywhere this component is used in both Inventory and User settings.

STSMACOM-165: Fix error display.

---

lib/Notes/NoteViewPage/components/NoteView/NoteView.js
lib/Notes/components/NoteForm/NoteForm.js

Per https://issues.folio.org/browse/STSMACOM-226 the assigned accordion section (on both note view and edit ) should be closed by default
Adjust accordion attributes to indicate `closedByDefault` and set sections state to reflect default closed
Manually tested change -- set up platform for test
`stripes workspace --modules ui-eholdings stripes-components stripes-smart-components stripes-sample-platform`
Add `ui-notes` to platform
https://github.com/folio-org/stripes/blob/master/doc/new-development-setup.md#platform-development-instructions
Gif shows manual test of accordion in platform
Added test coverage in eHoldings -- https://github.com/folio-org/ui-eholdings/pull/830 -- PR needs to wait until this change has been made.

STSMACOM-226 -Assigned accordion should be closed by default on note view/edit

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

It turned out that the `select` doesn't like the `undefined` value after rerender. Setting `selectedIndex` to an empty string instead correctly resets the `select` to the original value.
https://issues.folio.org/browse/UIIN-615

Set selectedIndex to empty string by default in order to correctly clear SearchField. Fixes UIIN-615

---

lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.css
lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js
lib/Notes/constants.js
translations/stripes-smart-components/en.json

This PR approaches the following UI updates in notes assignment modal:
- Fixed borders
- Added caution message (Notes with one assignment cannot be unassigned)
- Added the # of assignments column on the results list
- Place Cancel and Save buttons in the order as outlined on the mockup

STSMACOM-218: Notes modal UI updates

---

lib/ChangeDueDateDialog/ChangeDueDateDialog.js
translations/stripes-smart-components/en.json

Fix "Item has been recalled" message display in the change due date modal and data fetching on modal state handling.
It was agreed to move the data fetching process from the manifest object to the static method to provide data refreshing between modal state transitions. 
The previous version #572

UIU-1070: Fix alert display for recalled items in change due date modal

---

CHANGELOG.md
lib/ViewMetaData/ViewMetaData.js
lib/ViewMetaData/tests/ViewMetaData-test.js
lib/ViewMetaData/tests/interactor.js

Under some circumstances, `<ViewMetaData>` would get stuck in a loop and
React would eventually throw a Maximum Update Depth Exceeded error.
Debugging showed that it was receiving new props for creator-id and
updater-id but that, somehow, only the creator-id was being copied into
the `updaterIds` local resource. This meant the comparison of the props
to the resource always returned false and the query ran on each
iteration. Yuck.
Fixes [STSMACOM-230](https://issues.folio.org/browse/STSMACOM-230)

STSMACOM-230 ViewMetaData shouldn't fetch constantly

---

package.json

New features in stripes dependencies mean we need to bump the minor
versions of everything in the stripes dependency chain.

bump stripes deps

---

lib/SearchAndSort/components/CheckboxFilter/CheckboxFilter.js

- Some Ids that are passed to a CheckBox filter have spaces in between them and this is due to the fact that the _name_ here (which is the filter name) is sometimes of the form _In progress_ or _`Thesis and dissertation`_ and we would have an id eventually such as _clickable-select-filter-In Progress_ which is not selectable in our tests.
- Using Kebab case here would change it to _clickable-select-filter-in-progress_. This PR fixes this for a checkBox filter. But this also means that existing tests might break which are already using these filter Ids as selectors.

Use kebab case for the ids passed to a checkBox

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

It looks like the `locallyChangedSearchTerm` can be also an empty string (not just `undefined`). This PR adjusts couple conditions to make sure the issue in  STSMACOM-232 is solved.
https://issues.folio.org/browse/STSMACOM-232

Retain search query when returning to search and sort app. Part of STSMACOM-232.

---

CHANGELOG.md
lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js
lib/Notes/components/NotesAccordion/NotesAccordion.js

In some cases, libraries may want to hide to assign button on the notes accordion. I've added a `hideAssignButton` prop to NotesSmartAccordion which makes it possible to do it.

STSMACOM-236: add possibility to hide assign button on notes accordion

---

lib/EditableList/EditableListForm.js

`Settings` component uses `ControlledVocab`, which uses `EditableListForm`. We need to disable button `New`, so I've implemented similar behavior as for Edit and Delete row buttons - to pass attributes to the button. (`disabled` in this case).

UIORGS-79 disable button New similar to Edit and Delete

---

lib/SearchAndSort/SearchAndSort.js

Per https://issues.folio.org/browse/UIORGS-79 we need to hide route under Create permission, I think it's the only way to do it in SearchAndSort.
Any comments are welcome, thanks.

UIORGS-79 Hide route for New record if no permission

---

lib/SearchAndSort/SearchAndSort.js

A better UX, if no permissions for create - we just shouldn't render create form.
Basically, it's a fix of previous PR, when user has banner "no permission" all the time if he has no Create permission. https://github.com/folio-org/stripes-smart-components/pull/598

UIORGS-79 remove "no perm" banner on Create

---

CHANGELOG.md
lib/EntryManager/EntrySelector.js

Whoops; one-of-type (for arg-types) is not the same as one-of (for
arg-values). Look, ma! No crap in the console!

correctly define EntryManager's PropTypes

---

lib/Notes/NotesSmartAccordion/tests/interactors/index.js
lib/Notes/NotesSmartAccordion/tests/interactors/notes-accordion.js
lib/Notes/NotesSmartAccordion/tests/interactors/notes-modal.js
lib/Notes/NotesSmartAccordion/tests/notes-smart-accordion-test.js
lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js
tests/helpers.js
tests/network/config.js
tests/network/factories/note-type.js
tests/network/factories/note.js
tests/network/models/note-type.js
tests/network/models/note.js
tests/network/scenarios/create-notes-with-note-types.js
tests/network/serializers/note-type.js
tests/network/serializers/note.js

For now testing for Notes is implemented in each app using it. Adding new functionality causes adding the same tests in every application. In this PR, tests for internal Notes accordion stuff is extracted and placed near NotesSmartAccordion component.
Clean up tests in ui-eholdings, ui-users, ui-agreements apps. Leave only stuff for testing integration of the notes accordion into an app.

STSMACOM-241: Add tests for notes-smart-accordion

---

lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js

Remove width default params defined in percents to adjust columns width according to content
before
after

STSMACOM-252: Remove width params from notes list

---

lib/Notes/NoteViewPage/components/NoteView/NoteView.js

https://issues.folio.org/browse/STCOM-605
Apply style global class to remove margins between lines for Notes description section on preview mode

STCOM-605: Add editor preview style class to Notes

---

lib/SearchAndSort/SearchAndSort.js

purpose:
https://issues.folio.org/browse/UIF-115
search box should be autofocused
approach:
`autoFocus` prop for `SearchField` component

UIF-115 When you access the app the focus should be in the Search box

---

lib/SearchAndSort/SearchAndSortQuery.js

SASQ uses a debounced call to update the search query in its `componentDidMount` lifecycle. This can be problematic in unit-tests as it could cause the correct url for filter/search/etc to be overwritten by the default URL once the debounce lands.
console before: 
```
componentDidMount - submitAll()
push url: https://localhost:3000/users?filters=active.inactive   // test clicks a filter
push url: https://localhost:3000/users?sort=Name    //default url applies when debounce lands. test fails!
```
console after:
```
componentDidMount - submitAll()
push url: https://localhost:3000/users?sort=Name
push url: https://localhost:3000/users?filters=active.inactive   // test success since filter stays put.
```
Additionally, mild cleanup work within the component... renamed internal methods …

Don't debounce on mount.

---

lib/EditableList/EditableList.css

To fix scaling issue for EditableList smart component
https://issues.folio.org/browse/STSMACOM-256
Remove flex-wrap property to prevent moving data to another position

STSMACOM-256 - The Settings component does not scale. The result is data are jumping around

---

lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js

Context changes happen. In a blink, redux-form context will go from a containing a fully populated user to merely `sponsors` or some other less important field than the very important `values.personal`... 
If no `values.personal` field is available on context, simply use an empty array rather than error out on trying to reach `values.personal.addresses`.

EAF passes through on lack of values.personal.

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

I noticed this issue when switching between different search segments in ui-inventory and ui-orders. After performing search on the first segment and switching to another segment the search field would get repopulated with the value form the previous segment.
When a query resource is defined (it's configured via manifest) on multiple components (in the same ui package) its values get cached and are accessible between the components.
This PR doesn't populate locallyChangedSearchTerm if the query value from the query resource doesn't match the current query param in the url.

Fix locallyChangedSearchTerm. Refs UIIN-758

---

CHANGELOG.md
lib/ChangeDueDateDialog/ChangeDueDateDialog.js

Retrieve up to 100k of requested user loans instead of 10 in change due date dialog to fix the [issue](https://issues.folio.org/browse/UIU-1293).

UIU-1293: Retrieve up to 100k of requested user loans instead of 10 in change due date dialog

---

translations/stripes-smart-components/en.json

This PR is to fix translation for the Assigned accordion on notes create page

STSMACOM-262: Add translation for notes assigned accordion

---

lib/Notes/components/NoteForm/NoteForm.js

The `NoteForm` markup was slightly adjusted to make the quill URL pop-up always fully visible

STSMACOM-245: fix hidden quill tooltip on note form

---

lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js

Currently, when a user doesn't have the permission to GET note types, a request for note types is still made.  In this PR, I'm GETting note types only if the user has `ui-notes.item.view` permission, which has `note.types.collection.get` as a child permission.

STSMACOM-260: avoid fetching note types when user has no corresponding permissions

---

package.json

Handle the issue with tests upon the loading of translations by downgrading the [fake-xml-http-request](https://github.com/pretenderjs/FakeXMLHttpRequest) which updated [recently](https://github.com/pretenderjs/FakeXMLHttpRequest/releases/tag/v2.1.1) in the scope of [FOLIO-2369](https://issues.folio.org/browse/FOLIO-2369).
See: related issue merged PR in  [stripes-core](https://github.com/folio-org/stripes-core/pull/759)

FOLIO-2369: Handle the issue with tests upon the loading of translations

---

lib/Notes/components/NoteForm/NoteForm.js
package.json

Move Save button to the bottom of form and display a cancel button
Fo this the new paneFooter component should be applied.
The change in the notes form will require changing tests in the modules where notes functionality is integrated and tested, namely: ui-eholdings and ui-users.

STSMACOM-270: Refactor notes form to use paneFooter component

---

lib/SearchAndSort/SearchAndSort.js

This prevents warnings from displaying in the console for modules that have not opted in to the new "load more" workflow for result lists.

Corrected resultOffset to be defined as optional in propTypes

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js

Increase the `<ControlledVocab>` fetch limit from 500 to 2000 because
people want to have lots of things.
Refs [STSMACOM-296](https://issues.folio.org/browse/STSMACOM-296), [UIIN-819](https://issues.folio.org/browse/UIIN-819)

STSMACOM-296 bump ControlledVocab limit to 2000

---

CHANGELOG.md
lib/EntryManager/tests/interactor.js
lib/SearchAndSort/SearchAndSortQuery.js

Sometimes you _really_ want to be able to use dots in your filter values. This may come about because you have these [complex filters you want to build](https://issues.folio.org/browse/ERM-684), so you spend a day and a half figuring out the best way to write your own `filtersToString` and `filterParamsMapping` functions just so you can store a filter value that looks like `customProperties.foo.value>=15||customProperties.foo.value<=10`.
And then after nicely tidying everything up, you realise that the only difference between your implementation of those functions and the SASQ version is that you use `==` instead of `.` as a demarcator and rejoin the RHS after the `split()`.
Which makes you feel pretty annoyed, because you spent all this time and this little PR could've been enough from …

Added support for periods in filter values

---

package.json

`stripes-util` was inadvertenly omitted from the original round of PRs
updating stripes-* libraries in preparation for `@folio/stripes`
`v3.0.0`. This PR simply brings in that update.

bump stripes-util to v2

---

lib/Tags/TagsForm.js

Disabled regex search in TagsForm to free up the ability to use square brackets and parens.

STSMACOM-257 STSMACOM-294: Disable regex search

---

lib/SearchAndSort/SearchAndSort.js

We made a change in the `<MultiColumnList>`-component that removes the horizontal margin by default, making the component span from edge to edge.
This works for most implementations but MCL's used in the result panes must have the `hasMargin`-prop applied to enable proper spacing and alignment.
This PR adds that prop for the MCL in `<SearchAndSort>`.

Added hasMargin-prop for SearchAndSort MCL.

---

lib/Settings/Settings.css
lib/Settings/Settings.js

Removed margin from NavListSection because it's now added by default when stacking NavListSection's.

Removed margin from NavListSection

---

CHANGELOG.md
lib/SearchAndSort/ConnectedSource/StripesConnectedSource.js
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/tests/SearchAndSort-test.js
lib/SearchAndSort/tests/record-count-test.js

Accept the `pageAmount` and `pagingType` props from an app so it may opt-in to the "Load more" features of [stripes-components](https://github.com/folio-org/stripes-components/pull/1117) and [stripes-connect](https://github.com/folio-org/stripes-connect/pull/117).
It's a cherry-pick of the commits in #684 onto a patch branch in order to make that feature, and that feature alone, available as a patch to the [2019-q4 stripes release](https://github.com/folio-org/stripes/releases/tag/v2.12.1).

STSMACOM-269 load more

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

Add `hasNewButton` prop to `SearchAndSort` component. 
- By default `New` button of the pane appears and  `hasNewButton` sets to `true`.
- If  `hasNewButton` sets to `false` - `New` button of the pane does not appear.
https://issues.folio.org/browse/UIREQ-415
**hasNewButton = true (by default)**
**hasNewButton = false**

UIREQ-415: Add prop hasNewButton to SearchAndSort component

---

lib/SearchAndSort/SearchAndSort.js

The previous version contained what looks like a straight-up bug where
the rendering no-opped only if the helper _name_ was undefined. This
meant you could invoke a URL with, say, `helper=noSuchThing`, and
`<SearchAndSort>` would fail to find that helper but still try to
render the component that implements it, even though it was undefined.
Thanks to @EthanFreestone for helping me spot this.
--
NB. I nominated @VictorSoroka1 to review this because the original test is in code he added, and I want to be sure I've not misunderstood his intent.

Helper-app rendering no-ops if the helper is undefined

---

CHANGELOG.md
lib/Tags/Tags.js

Provide default props `getEntity` and `getEntityTags` to `<Tags>` to allow implementors
to set other paths to the tags resource.
Refs [STSMACOM-332](https://issues.folio.org/browse/STSMACOM-332) (formerly [UIDATIMP-461](https://issues.folio.org/browse/UIDATIMP-461))

STSMACOM-332 getEntity and getEntityTags props for Tags

---

package.json

Within the `@folio/stripes` namespace, packages must depend on each
other with `~` instead of `^`. Some details at STRIPES-588 and
STRIPES-612. This loose dependency was inadvertently introduced in #740.

bug fix: use tilde deps on stripes-* libs

---

CHANGELOG.md
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js

It looks like we ran into a case where the type defined on the server (`SINGLE_SELECT_DROPDOWN`) was not defined in: 
https://github.com/folio-org/stripes-smart-components/blob/master/lib/CustomFields/constants.js
which caused the ui-users to explode.
This PR adds an extra check to make sure there is a corresponding component for the given type. 
I think there should be another story created to actually register `SINGLE_SELECT_DROPDOWN` as a valid type.
https://issues.folio.org/browse/STSMACOM-333

STSMACOM-333: Check if the component exists for given customField.type

---

lib/EntryManager/EntrySelector.js

A `<Button>` can have an `aria-label` but not an `ariaLabel`.

pass correct aria props to Button

---

lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js

- Fix note type values in `<NotesList>` component being cut off by providing default column widths to MCL component

STSMACOM-334: Notes list: Refreshing Detail record causes the Note type value to be cut off

---

CHANGELOG.md
lib/EntryManager/EntrySelector.js
translations/stripes-smart-components/en.json

Do not use translation keys from `ui-circulation`. Only repositories
below this one in the stripes hierarchy may be used because only those
are guaranteed to be present.

do not use translations from ui repositories

---

CHANGELOG.md
lib/CustomFields/components/CustomFieldsForm/CustomFieldsForm.js
lib/CustomFields/components/FieldAccordion/FieldAccordion.js
lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/OptionsField.js
lib/CustomFields/components/FieldAccordion/view-sections/shared-values/Options.js
lib/CustomFields/constants.js
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.css
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
lib/CustomFields/pages/EditCustomFieldsSettings/EditCustomFieldsSettings.js
lib/CustomFields/readme.md
translations/stripes-smart-components/en.json

Requires https://github.com/folio-org/ui-users/pull/1295
To be able to edit and see values of custom fields of type "Radio button set" on entity records
Some custom fields can have default values (like select and radio button set). It's not possible to pass these default values to a form, since `<Form initialValues={...} />` doesn't live in `stripes-smart-components`. That's why, in order to populate fields with default values, I imperatively change their values after there are rendered.
To imperatively change the value of a field it's necessary to know if its a part of `final-form` or `redux-form`. For this purpose, a couple of props were added:
* `isReduxForm` - used to tell custom fields if they are being rendered inside `redux-form`. If `isReduxForm` is `true`, then custom fields will …

UIU-1514: add radio button set view and edit functionality

---

lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js

- Increase space for `date` column to fit all digits in one row

STSMACOM-334: Increased space for notes date column

---

CHANGELOG.md
lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js

After looking up how the aria-labelledby attribute is supposed to be used,
I decided to remove this attribute entirely from the radio button. This
attribute is supposed to tell assistive technologies what label is associated
with this form control.  But the label in question already wraps around the
control, making it clear from context what form control it's associated with.
The label/control shouldn't need any attribute to associate the two.
Refs: https://issues.folio.org/browse/UIU-1641

UIU-1641: New/Edit User Record: Primary address toggle uses invalid ARIA

---

CHANGELOG.md
lib/CustomFields/components/CustomFieldsForm/CustomFieldsForm.js
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
lib/CustomFields/pages/ViewCustomFieldsRecord/ViewCustomFieldsRecord.js

The purpose of this pr is to fix a couple of minor CF-related issues: 
* Remove asterisk from radio button custom field label (UIU-1700)
* Apply correct styling to the save button on the edit custom fields page (STSMACOM-368)
* Make checkbox custom field correctly reflect the form state when saving a record for the first time (UIU-1690)

UIU-1700, UIU-1690, STSMACOM-368: fix custom fields issues

---

CHANGELOG.md
lib/CustomFields/utils/useCustomFieldsFetch.js

- Apply limit to `/custom-fields` request to allow loading more than 10 Custom Fields

STSMACOM-370: Settings > Users > Custom Fields: Only 10 custom fields display

---

lib/CustomFields/pages/ViewCustomFieldsSettings/ViewCustomFieldsSettings.js

When no custom field has been created OR Accordion title has not been updated then the button label should be New

STSMACOM-355: Fix bug with New button

---

CHANGELOG.md
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
lib/CustomFields/pages/EditCustomFieldsRecord/tests/EditCustomFieldsRecord-test.js
lib/CustomFields/pages/EditCustomFieldsRecord/tests/interactor.js
lib/CustomFields/pages/ViewCustomFieldsRecord/ViewCustomFieldsRecord.js

To show custom fields accordion with the loading icon until the data is loaded.

UIU-1702: make custom fields accordion visible while data is being loaded

---

CHANGELOG.md
lib/Notes/NoteCreatePage/NoteCreatePage.js
lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js
lib/Notes/components/NoteForm/NoteForm.js
lib/Notes/components/NotesAccordion/NotesAccordion.js

Add possibility to change Notes accordion label. In scope of [UIREQ-457](https://issues.folio.org/browse/UIREQ-457) we need to show `Staff notes` instead of `Notes` accordion name

UIREQ-457: Add 'label' prop to '<NotesSmartAccordion>'

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/buildUrl.js
lib/SearchAndSort/readme.md
package.json

This PR adds a new prop to `SearchAndSort` called `basePath` which can be used to control which path should be used after search is performed.
https://issues.folio.org/browse/STSMACOM-378
This should help with addressing issue described in https://issues.folio.org/browse/UIIN-1074

STSMACOM-378: Add ability to customize path used after search is performed

---

lib/Notes/NotesSmartAccordion/tests/interactors/notes-accordion.js

- Extend `<NotesSmartAccordion>` interactor to support testing navigating back

UIREQ-459: Extend NotesSmartAccordion interactor

---

karma.conf.js
lib/CustomFields/components/CustomFieldsForm/tests/CustomFieldsForm-test.js
lib/CustomFields/components/CustomFieldsForm/tests/DraggableAccordionInteractor.js
lib/CustomFields/components/CustomFieldsForm/tests/interactor.js

https://issues.folio.org/browse/STSMACOM-351
* cover custom fields drag and drop with tests
* make karma ignore console messages. react-beautiful-dnd prints the builder emoji 👷 in the console. that's why xmlbuilder throws and karma exits with code 1.
👷🤛

STSMACOM-351: cover custom fields drag and drop with tests

---

CHANGELOG.md
lib/CustomFields/components/CustomFieldsForm/components/AddButton/tests/interactor.js
lib/CustomFields/components/FieldAccordion/edit-fields/components/AddOptionButton/AddOptionButton.js
lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/HelpTextField/HelpTextField.js
lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/HiddenField/HiddenField.js
lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/NameField/NameField.js
lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/RequiredField/RequiredField.js
lib/CustomFields/pages/EditCustomFieldsSettings/EditCustomFieldsSettings.js
lib/CustomFields/pages/EditCustomFieldsSettings/tests/EditCustomFieldsSettings-test.js
lib/CustomFields/pages/EditCustomFieldsSettings/tests/interactor.js

* Add alphabetical sorting of Custom Fields options when saving Custom Fields
[STSMACOM-379](https://issues.folio.org/browse/STSMACOM-379)

STSMACOM-379: Settings > Custom Fields > Saved Options display in alphabetical order

---

CHANGELOG.md
lib/Notes/NoteCreatePage/NoteCreatePage.js
lib/Notes/NoteEditPage/NoteEditPage.js
lib/Notes/NoteViewPage/NoteViewPage.js
lib/Notes/NoteViewPage/components/NoteView/NoteView.js
lib/Notes/NoteViewPage/components/NoteView/tests/interactor.js
lib/Notes/NoteViewPage/components/NoteView/tests/note-view-test.js
lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js
lib/Notes/components/NoteForm/NoteForm.js
lib/Notes/components/NoteForm/tests/interactor.js
lib/Notes/components/NoteForm/tests/note-form-test.js
lib/Notes/components/ReferredRecord/tests/interactor.js
lib/Notes/components/ReferredRecord/tests/referred-record-test.js

Add changeable content to NotesView and NotesForm components to show it in Assigned accordion. Part of [UIREQ-467](https://issues.folio.org/browse/UIREQ-467)

UIREQ-467: Add changeable content to assigned accordion to Notes

---

CHANGELOG.md
lib/CustomFields/components/CustomFieldsForm/CustomFieldsForm.js
translations/stripes-smart-components/en.json

Change `Save` button label to `Save & close`
[STSMACOM-380](https://issues.folio.org/browse/STSMACOM-380)

STSMACOM-380: Settings > Edit Custom Fields > change Save button label to Save & close

---

CHANGELOG.md
lib/CustomFields/components/CustomFieldsForm/CustomFieldsForm.js
lib/CustomFields/pages/EditCustomFieldsSettings/EditCustomFieldsSettings.js

After drop custom field on new place EditCustomFieldSettings sends request to set Accordion title. It must be prevent because drag'n'drop doesn't change accordion title.
[STSMACOM-382](https://issues.folio.org/browse/STSMACOM-382)

STSMACOM-382: Prevent PUT request for accordion title during drag'n'drop custom field

---

lib/EntryManager/EntrySelector.js

When using the normal Edit button, the `nameKey` prop is used to render the delete confirmation modal. However, when using the actions dropdown, it just always uses `.name`.

Pull record name from nameKey

---

CHANGELOG.md
lib/Tags/Tags.js
lib/Tags/TagsAccordion.js

Provide `entityTagsPath` prop to `<Tags>` to allow implementors to set custom entity tags path. (See the usage of it [here](https://github.com/folio-org/ui-data-import/blob/UIDATIMP-499/src/settings/JobProfiles/ViewJobProfile.js#L421))
Add `entityTagsPath` prop to `<Tags>`
Set tags to an entity by the provided path.
Set `entityTagsPath` = "tags" by default
[STSMACOM-385](https://issues.folio.org/browse/STSMACOM-385)
[UIDATIMP-499](https://issues.folio.org/browse/UIDATIMP-499)

STSMACOM-385: Add `entityTagsPath` to `Tags`

---

CHANGELOG.md
lib/ChangeDueDateDialog/LoanList.js

https://issues.folio.org/browse/UIU-1731
This fixes a bug in the ChangeDueDateDialog loan list, wherein the loan policy name was not appearing. Thanks to @mkuklis  for pointing out the problem!

UIU-1731: Increase record limit in ChangeDueDate loan policy lookups

---

CHANGELOG.md
lib/ChangeDueDateDialog/LoanList.js

Adjust column widths for `ChangeDueDateDialog` to remove horizontal scrollbar.
https://issues.folio.org/browse/STSMACOM-402
**Before**
**After**

STSMACOM-402: Remove horizontal scrollbar from ChangeDueDateDialog

---

CHANGELOG.md
lib/ControlledVocab/tests/actuators-refdata-test.js
lib/Notes/NoteViewPage/tests/NoteViewPage-test.js
lib/SearchAndSort/SearchAndSort.js
tests/helpers.js

Use search term when filter is applied via `SearchAndSort`. 
This approach is using a resource query in order to keep track of the current search term. 
https://issues.folio.org/browse/STSMACOM-365

STSMACOM-365: Use search term when filter is applied

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

https://issues.folio.org/browse/STSMACOM-194
Achieve that when clicking the "Reset all" button the search terms are cleared and the sort terms returned to default.

STSMACOM-194: Fix reset the sort terms when clicking 'Reset all'

---

CHANGELOG.md
lib/Notes/constants.js

- Extend Note title character limit to 255 characters

STSMACOM-335: Extend Note title character limit to 255 characters

---

CHANGELOG.md
lib/ChangeDueDateDialog/ChangeDueDateDialog.js

https://issues.folio.org/browse/STSMACOM-404
This fixes a bug in the ChangeDueDateDialog loan list, wherein an item with an open request on it would not be identified as such.

STSMACOM-404: Increase record limit for open request lookups in <ChangeDueDateDialog>

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
lib/CustomFields/components/CustomFieldsForm/tests/CustomFieldsForm-test.js
lib/CustomFields/pages/EditCustomFieldsRecord/tests/EditCustomFieldsRecord-test.js
lib/CustomFields/pages/EditCustomFieldsSettings/tests/DeleteCustomFieldsOptions-test.js

https://issues.folio.org/browse/STSMACOM-384
Remove the 'no data' message displayed when saving a record.
**Before**
**Approach**
Added display of `Loader` while the records are not loaded yet.
Problems with passing tests in the `CustomFields` component have also been fixed. Achieved by mounting the component directly when using `setupApplication` instead of `mount` later on.

STSMACOM-384: Remove the 'no data' message displayed when saving a record

---

lib/CustomFields/components/FieldAccordion/FieldAccordion.js

- Remove repeated IDs of Custom Fields drag-and-drop tooltips

STSMACOM-410: Fix same IDs of CustomFields drag-and-drop tooltip

---

CHANGELOG.md
lib/EntryManager/EntrySelector.js
lib/SearchAndSort/SearchAndSort.js
lib/Settings/Settings.js

Handle react-router-dom deprecation warnings
```
Chrome 84.0.4147 (Mac OS X 10.15.6) ERROR: 'Warning: Please use `require("react-router-dom").Route` instead of `require("react-router-dom/Route")`. Support for the latter will be removed in the next major release.'
Chrome 84.0.4147 (Mac OS X 10.15.6) ERROR: 'Warning: Please use `require("react-router-dom").Link` instead of `require("react-router-dom/Link")`. Support for the latter will be removed in the next major release.'
Chrome 84.0.4147 (Mac OS X 10.15.6) ERROR: 'Warning: Please use `require("react-router-dom").Switch` instead of `require("react-router-dom/Switch")`. Support for the latter will be removed in the next major release.'
```

STSMACOM-421: Handle react-router-dom deprecation warnings

---

CHANGELOG.md
lib/ChangeDueDateDialog/ChangeDueDate.js
lib/ChangeDueDateDialog/ChangeDueDateDialog.js
lib/ChangeDueDateDialog/constants.js
translations/stripes-smart-components/en.json

https://issues.folio.org/browse/UIU-1495
This adds support for Aged to lost items in <ChangeDueDateDialog>. It also addresses a bug I encountered, wherein the "x items selected" text at the top of the dialog box would not change when items were selected or deselected.

UIU-1495: Handle Aged to lost items in ChangeDueDateDialog

---

CHANGELOG.md
lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js

[[STSMACOM-419]](https://issues.folio.org/browse/STSMACOM-419) NotesList: Fix 'Show more' button
While clicking on `Show more` button in Note list, every note that was collapsed  did expand. This PR is fixing the wrong behavior of `Show more` button, so now it works as expected and expand/collapse only corresponding note.

[STSMACOM-419] NotesList: Fix 'Show more' button

---

CHANGELOG.md
lib/ChangeDueDateDialog/ChangeDueDate.js

https://issues.folio.org/browse/STSMACOM-432
This fixes a bug wherein changing the due date of an item would add an entry to the action history with the comment of the _previous_ action, not the due date change. Turns out that the _previous action_ is saved as part of the loan record, and this code was somewhat blindly copying and modifying the existing record to change the due date, perpetuating the old action comment.

STSMACOM-432: Fix bug in ChangeDueDateDialog saving unwanted actionComment

---

CHANGELOG.md
lib/ClipCopy/ClipCopy.js

component was introduced in https://github.com/folio-org/stripes-smart-components/pull/858 but with wrong message id :)

Fix `ClipCopy` success message

---

CHANGELOG.md
lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js
lib/Notes/components/NotesAccordion/NotesAccordion.js

Related to [UIEH-923](https://issues.folio.org/browse/UIEH-923)
Added `headerProps` property to `NotesSmartAccordion` and `NotesAccordion` in order to pass it down to `Accordion`

STSMACOM-439: added headerProps property to NotesSmartAccordion

---

CHANGELOG.md
lib/EditableList/ItemEdit.js
lib/EditableList/ItemView.js
lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js

1. Remove unneeded `role="row"` attribute in `<EditableList>` item wrappers. It is unnecessary to add this attribute in `<EditableList>`, because `<MultiColumnList>` already adds `role="row"` to a wrapper element of each row
2. Add id to note type select header to be referenced as a label

UIEH-963: Fix invalid ARIA attribute order in EditableList

---

CHANGELOG.md
lib/CustomFields/pages/EditCustomFieldsSettings/tests/DeleteCustomFieldsOptions-test.js
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/tests/SearchAndSort-test.js
lib/SearchAndSort/tests/interactor.js

Given a search type (e.g. Keyword search in Inventory) is selected AND a search for search string "XYZ" has been conducted
When the search type is changed (e.g. from Keyword to Contributors in Inventory) Then:
* The search term "XYZ" should be retained
* The Contributor search for "XYZ" would not be automatically executed (user would need to click "Search" button or hit enter to execute new search or change the filters (once we've fixed this bug: STSMACOM-365))
https://issues.folio.org/browse/STSMACOM-350
This is not a breaking change but the modules which still use `SearchAndSort` will need to remove or adjust `onChangeIndex` if they want to follow the functionality described  STSMACOM-365 for example:
https://github.com/folio-org/ui-inventory/pull/1200/files
Another approach here would …

STSMACOM-350: Do not execute search automatically when query index changes

---

CHANGELOG.md
lib/SearchAndSort/components/CollapseFilterPaneButton/CollapseFilterPaneButton.js

`<CollapseFilterPaneButton>` used `<FormattedMessage>` with renderprops
to derive the value to pass to `<ToolTip>`, but as of `react-intl` `v5`
that results in an array instead of a string, which sucks, and which
generates this console warning:
```
Warning: Failed prop type: Invalid prop `text` supplied to `Tooltip`.
```
Refs [STSMACOM-447](https://issues.folio.org/browse/STSMACOM-447)

STSMACOM-447 correctly pass props.text to ToolTip

---

CHANGELOG.md
lib/SearchAndSort/makeQueryFunction.js

`makeQueryFunction` now accepts another argument, `escape` (default:
`true`) to allow callers to turn off escaping of quote and backslash
values in CQL queries. This is necessary for features like
ui-inventory's "Query search" search-type that submits a fully-formed
CQL query.
Refs [STSMACOM-454](https://issues.folio.org/browse/STSMACOM-454), [UIIN-1319](https://issues.folio.org/browse/UIIN-1319).

STSMACOM-454 allow escaping to be disabled

---

CHANGELOG.md
lib/EntryManager/EntryWrapper.js
translations/stripes-smart-components/en.json

`Callout` does not show up any more on pages where `EntryManager` is used (circulation forms). 
https://issues.folio.org/browse/STSMACOM-456

STSMACOM-456: Show callout in EntryManager

---

CHANGELOG.md
lib/Tags/Tags.js

https://issues.folio.org/browse/STSMACOM-457
The 100 limit started causing some issues in `bugfest-honeysuckle` were there are currently over 100 added tags.
The problem happens when only first 100 tags are fetched. When the new tag is being added which already exists in the db but it's not prefetched the frontend will treat it as a brand `new` tag and the POST request will be issued in order to create it.

STSMACOM-457: Increase record limit for tags query

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

https://issues.folio.org/browse/STCOM-782
It looks like ui-inventory is doing a correct thing already while submitting a form by checking the `submitting` flag:
https://github.com/folio-org/ui-inventory/blob/24a9d2cc4ad1a5156e9f9c0c21472008a98be053/src/edit/InstanceForm.js#L231
https://final-form.org/docs/final-form/types/FormState#submitting
The problem is that the `submitting` is always set to `false` because the submission handler doesn't currently receive a promise. 
This is causing "double submission" problems with instance form in ui-inventory:
https://issues.folio.org/browse/UIIN-1339
https://issues.folio.org/browse/UIIN-1340
There is some additional work which was also required to address it in ui-inventory
https://github.com/folio-org/ui-inventory/pull/1219
This PR takes care of …

STCOM-782: Return promise from createRecord in SearchAndSort

---

CHANGELOG.md
lib/Tags/Tags.js
lib/Tags/TagsForm.js

https://issues.folio.org/browse/STSMACOM-459
This PR is doing couple things:
1. While switching between different entities (users, requests) the tags from the previous record were still visible for a while before the new tags were loaded. This should be now addressed by using `resourceShouldRefresh`.
2. It takes couple seconds before the tags are loaded for a given user in ui-users. This is due to the fact that when a new user record is opened there are 65 requests firing and the request associated with tags usually finishes last. The `<Loading />` indicator was added to provide some sort of feedback. (We probably should spend some time and think how we could refactor it in order to improve it. For example the entity we work with is usually already preloaded before we open the tags pane …

STSMACOM-459: Improve Tags loading experience

---

CHANGELOG.md
lib/ClipCopy/ClipCopy.js

There was a bad interaction between `<FormattedMessage>` and
`useCallback` in `<ClipCopy>`, likely because `<FormattedMessage>`
implicitly relies on the `<IntlProvider>` context being available, but
this is not passed into `useCallback`.
Refactoring with `useIntl`, allowing the `intl` object to become an
explicit dependency of the `useCallback` hook, resolves this issue.
We moved the `CalloutContext` up a level in the component hierarchy in
STCOR-481, which is probably the root cause of this.
Refs [STSMACOM-463](https://issues.folio.org/browse/STSMACOM-463), [UIIN-1357](https://issues.folio.org/browse/UIIN-1357), [UIOR-635](https://issues.folio.org/browse/UIOR-635), [STCOR-481](https://issues.folio.org/browse/STCOR-481)

STSMACOM-463 refactor ClipCopy with useIntl

---

CHANGELOG.md
lib/Tags/Tags.js
lib/Tags/TagsForm.js

first we show items that start with filtered text, sort them, and then we show items that contain filtered text but don't start with it.
https://issues.folio.org/browse/UITAG-37

UITAG-37 fix filtered tags sorting

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/tests/SearchAndSort-test.js
lib/SearchAndSort/tests/interactor.js

Extend `SearchAndSort` with the functionality to execute a callback on reset search and filter button in the scope of the [STSMACOM-465](https://issues.folio.org/browse/STSMACOM-465).
In order to comply with scenario 5 from [UIIN-1350](https://issues.folio.org/browse/UIIN-1350), SearchAndSort should be extended to execute callback upon reset button clicked.
> *  Given: the results list is populated and at least one checkbox is selected
> *  When: the user selects Reset all button  and the result list clears out
> *  Then: the previously selected records are unselected and the records count label is hidden as well.

STSMACOM-465: Extend `SearchAndSort` with the functionality to execute callback on reset search and filter button

---

lib/SearchAndSort/tests/SearchAndSort-test.js
lib/SearchAndSort/tests/interactor.js

In the scope of the [STSMACOM-465](https://issues.folio.org/browse/STSMACOM-465).
- Make `searchField` to use `SearchFieldInteractor` in `SearchAndSortInteractor`;
- Use `ButtonInteractor` for `resetAll` in `SearchAndSortInteractor` so props like `isPresent` and `idDisabled` can be used;

STSMACOM-465: Make `searchField` to use `SearchFieldInteractor` in `SearchAndSortInteractor`

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.css
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/tests/SearchAndSort-test.js
lib/SearchAndSort/tests/interactor.js
lib/SearchAndSort/tests/record-count-test.js

In scope of [STSMACOM-467](https://issues.folio.org/browse/STSMACOM-467).
In order to comply with [UIDEXP-168](https://issues.folio.org/browse/UIDEXP-168), where there search results pane subheader should display the number of selected items the `SearchAndSort` should be extended to support this.

STSMACOM-467: Extend SearchAndSort with customPaneSub prop to display additional element in paneSub

---

lib/CustomFields/selectors/selectModuleId.js

`discovery` may not exist. It's [removed during a `DESTROY_STORE` action](https://github.com/folio-org/stripes-core/blob/629c92769d62aacf41dc5af830332a0de127714e/src/enhanceReducer.js#L16-L19) when Stripes is being unmounted.
@skomorokh, this is the other unrelated fix during my react-redux work.

Conditionally access `discovery` in redux store

---

CHANGELOG.md
lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js
lib/AddressFieldGroup/AddressEdit/withReduxFormContext.js

https://issues.folio.org/browse/STSMACOM-473
The previous way of accessing reduxForm via `contextTypes` was not supported any more so this uses `ReduxFormContext` instead.

STSMACOM-473: Refactor redux-form context in EmbeddedAddressForm

---

CHANGELOG.md
lib/ChangeDueDateDialog/ChangeDueDateDialog.js
lib/ConfigManager/ConfigManager.js

Use `==` instead of `=` when querying by ID.
I found an earlier version of this fix from June 2020 when cleaning up
some old branches. I don't know why it was never PR-ified then. :shrug:
Refs [PERF-62](https://issues.folio.org/browse/PERF-62)

PERF-62 use more efficient query clauses

---

CHANGELOG.md
lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js

Fix axe error with aria-label on Assign/Unassign modal (NotesAssigningModal)
Related issue: [STSMACOM-475](https://issues.folio.org/browse/STSMACOM-475)
(only color related errors left)

STSMACOM-475: Fix axe error with aria-label on Assign/Unassign modal

---

CHANGELOG.md
lib/ViewMetaData/ViewMetaData.js
lib/ViewMetaData/tests/ViewMetaData-test.js

https://issues.folio.org/browse/STSMACOM-480
basically, we should ask back-end permission for the API call, since it's a common component.

STSMACOM-480 fix permission for View Metadata

---

CHANGELOG.md
package.json

Build with `@folio/stripes-cli` `v2`.
Refs [STSMACOM-481](https://issues.folio.org/browse/STSMACOM-481)

STSMACOM-481 increment @folio/stripes-cli to v2

---

lib/ConfigManager/ConfigFinalForm.js
lib/ConfigManager/ConfigForm.js
lib/ConfigManager/ConfigManager.js
lib/ConfigManager/ConfigReduxForm.js
lib/ControlledVocab/ControlledVocab.js
lib/EditableList/EditableList.js
lib/EditableList/EditableListFinalForm.js
lib/EditableList/EditableListForm.js
lib/EditableList/EditableListReduxForm.js
lib/EditableList/ItemEdit.js

This PR introduces a new prop called `formType` (which by default is set to `redux-form`) which can be used to switch `ControlledVocab` to use `final-form`.
https://issues.folio.org/browse/STSMACOM-482
There are couple other alternative approaches we could take here:
1. Expose a new component via `stripes-smart-components` called `ControlledVocabFF` or something similar.
2. Do not provide  backwards compatibility and just switch completely to final-form and bump a major version of stripes-smart-components.
I'm not sure which one is the best. The current approach allows us to move gradually. For example update ui-users, check if everything works, etc.

STSMACOM-482: Upgrade ControlledVocab to final form

---

CHANGELOG.md
lib/CustomFields/pages/ViewCustomFieldsSettings/ViewCustomFieldsSettings.js

Focus Custom Fields pane title after Custom Fields are saved and when View Custom Fields are first opened
[STSMACOM-476](https://issues.folio.org/browse/STSMACOM-476)
[STSMACOM-477](https://issues.folio.org/browse/STSMACOM-477)

STSMACOM-476: Settings > Users > Custom Fields | Saving a record's focus is confusing

---

CHANGELOG.md
lib/AddressFieldGroup/AddressEdit/AddressEdit.js
lib/AddressFieldGroup/AddressEdit/AddressEditList.js
lib/AddressFieldGroup/AddressEdit/EmbeddedAddressFinalForm.js
lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js
lib/AddressFieldGroup/AddressEdit/EmbeddedAddressReduxForm.js
lib/AddressFieldGroup/AddressEdit/withReduxFormContext.js

This approach is very similar to the one in: https://github.com/folio-org/stripes-smart-components/pull/1003
`formType` prop (with `refux-form` or `final-form` options) can be used to choose the form implementation. 
https://issues.folio.org/browse/STSMACOM-484

 STSMACOM-484: Upgrade AddressFieldGroup to final form

---

CHANGELOG.md
lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/OptionsField/tests/OptionsField-test.js
lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js
tests/network/config.js

Apply default sorting of Notes by updated date when component is first loaded
[STSMACOM-487](https://issues.folio.org/browse/STSMACOM-487)

STSMACOM-487: Notes list - Default descending date sort is not working 

---

CHANGELOG.md
index.js
lib/ConfigManager/index.js

`ConfigForm` was replaced with `ConfigReduxForm` (and a parallel
component `ConfigFinalForm`) but (a) neither was exported and (b)
`ConfigForm` continued to be exported but now is an entirely different
component.
Rather than try to restore things as they were since use of `ConfigForm`
appears to be confined to a couple of pages in ui-developer, this PR
simply exports `ConfigReduxForm` and `ConfigFinalForm`, restoring the
old behavior but under a new name. That's good enough, and small enough,
and gosh darn it, people should like it.
Refs [STSMACOM-490](https://issues.folio.org/browse/STSMACOM-490), [UID-72](https://issues.folio.org/browse/UID-72)

STSMACOM-490 export missing ConfigManager components

---

CHANGELOG.md
lib/CustomFields/components/CustomFieldsForm/CustomFieldsForm.js
lib/CustomFields/components/CustomFieldsForm/components/CustomFieldsAccordions/CustomFieldsAccordions.js
lib/CustomFields/components/CustomFieldsForm/tests/CustomFieldsForm-test.js
lib/CustomFields/components/FieldAccordion/FieldAccordion.js

Adding a new custom field focus (Settings > Users > Custom Fields)
Related task: [STSMACOM-479](https://issues.folio.org/browse/STSMACOM-479)

STSMACOM-479: Adding a new custom field focus

---

CHANGELOG.md
lib/CustomFields/components/CustomFieldsForm/tests/interactor.js
lib/CustomFields/components/FieldAccordion/FieldAccordion.js
package.json

- Make Custom Fields drag and drop icon a button to improve accessibility
- Bump version of `react-beautiful-dnd` to `13.1.0`. This is needed because new version includes some bugfixes and accessibility improvements that we need.
There were no breaking changes that could affect our existing implementation so we can safely do the update. Here's the changelog of the library https://github.com/atlassian/react-beautiful-dnd/releases
[STSMACOM-478](https://issues.folio.org/browse/STSMACOM-478)

STSMACOM-478: Make the move custom field icon a button.

---

translations/stripes-smart-components/ar.json
translations/stripes-smart-components/ber.json
translations/stripes-smart-components/ca.json
translations/stripes-smart-components/da.json
translations/stripes-smart-components/de.json
translations/stripes-smart-components/en_GB.json
translations/stripes-smart-components/en_SE.json
translations/stripes-smart-components/en_US.json
translations/stripes-smart-components/es.json
translations/stripes-smart-components/es_419.json
translations/stripes-smart-components/es_ES.json
translations/stripes-smart-components/fr.json
translations/stripes-smart-components/fr_FR.json
translations/stripes-smart-components/he.json
translations/stripes-smart-components/hi_IN.json
translations/stripes-smart-components/hu.json
translations/stripes-smart-components/it_IT.json
translations/stripes-smart-components/ja.json
translations/stripes-smart-components/ko.json
translations/stripes-smart-components/nb.json
translations/stripes-smart-components/nn.json
translations/stripes-smart-components/pl.json
translations/stripes-smart-components/pt_BR.json
translations/stripes-smart-components/pt_PT.json
translations/stripes-smart-components/ru.json
translations/stripes-smart-components/sv.json
translations/stripes-smart-components/ur.json
translations/stripes-smart-components/zh_CN.json
translations/stripes-smart-components/zh_TW.json

Ordinarily we would wait for this typo to be fixed in the next push from
Lokalise but given we need it to be included in the upcoming patch
release I'm just gonna make the change directly here. (All we're doing
is removing whitespace from from a key.)
Refs [STSMACOM-497](https://issues.folio.org/browse/STSMACOM-497)

STSMACOM-497 remove typo across locale files

---

CHANGELOG.md
package.json

Lock onto `2.4.0` to avoid https://github.com/rehooks/local-storage/issues/77
Refs [STSMACOM-501](https://issues.folio.org/browse/STSMACOM-501)

STSMACOM-501 avoid @rehooks/local-storage 2.4.1

---

CHANGELOG.md
index.js
lib/ColumnManager/ColumnManager.js
lib/ColumnManager/ColumnManagerMenu.js
lib/ColumnManager/index.js
lib/ColumnManager/readme.md
lib/ColumnManager/useColumnManager.js
lib/SearchAndSort/SearchAndSort.js

purpose:
https://issues.folio.org/browse/STSMACOM-502
many modules are built with hooks, it would be nice to have one more way to configure columns manager
approach:
move visibility control to hook, define ColumnsMenu as a separate component, expose them + reuse in ColumnManager to support composition approach
initial tests are passed
documentation is updated

STSMACOM-502 hooks approach for ColumnManager

---

CHANGELOG.md
lib/CustomFields/utils/useCustomFieldsFetch.js
lib/CustomFields/utils/useOptionsStatsFetch.js
lib/CustomFields/utils/useSectionTitleFetch.js

A Promise may return after a component has unmounted. If it does so, it
must not call `setState()`, which is a memory leak reported in the
console.
Refs [STSMACOM-506](https://issues.folio.org/browse/STSMACOM-506)

STSMACOM-506 avoid calling setState after unmount

---

lib/Notes/NotePopupModal/NotePopupModal.js

`PropTypes.oneOf()` takes an array of values; `PropTypes.oneOfType()`
takes an array of value-types. Thus, the previous implementation always
threw a warning.

Use correct PropTypes

---

lib/Notes/NotePopupModal/NotePopupModal.js
translations/stripes-smart-components/en.json

Fix Popup Note not showing up on users by clearing session storage when note was just created and loaded. Also, prevented sending multiple requests to notes endpoint
[STSMACOM-509](https://issues.folio.org/browse/STSMACOM-509)

STSMACOM-509 Fix Note popup not showing up after creation

---

lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

This PR exposes the `virtualize`, `onMarkPosition`, `onMarkReset`, `ItemToView`, `key`,  props for the internally rendered `<MultiColumnList>` component.
The props are exposed as follows:
- resultsVirtualize = virtualize
- resultsOnMarkPosition = onMarkPosition
- resultsOnResetMarkedPosition = onMarkReset
- resultsCachedPosition = ItemToView
- resultsKey = key

STSMACOM-508 - Expose props for MCL scrollItemToView functionality

---

CHANGELOG.md
lib/Notes/NoteCreatePage/NoteCreatePage.js
lib/Notes/NotePopupModal/NotePopupModal.js
lib/Notes/NotePopupModal/tests/NotePopupModal-test.js
lib/Notes/constants.js

Always show NotePopupModal when popup notes exist.
`<NotePopupModal>` breaks tests in modules that aren't yet using new jsx transforms. This PR adds import React to this component
@zburke Do we want to create tickets for all UI modules to use new jsx transforms for the next release?

STSMACOM-515: Users/Checkout pop-up note: Change logic for when to display pop-up

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

https://issues.folio.org/browse/STSMACOM-516
The purpose of this PR is to give ui module developers control over the autofocus prop of SearchAndSort's rendered SearchField component. This will allow modules to implement their own focus management.

STSMACOM-516 SearchAndSort autofocus handling

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

After editing and saving a record, returning to the results list will not have the currently seleted item highlighted.
Make use of MultiColumnList's `isSelected` prop so that objects containing a subset of like values can be used for criteria.

STSMACOM-518 results list not reflecting selection on return from edit.

---

CHANGELOG.md
lib/EditableList/EditableListForm.js

Added default value for not required `validate` prop in `<EditableListForm>`. We're using `<EditableList>` in eHoldings and don't need to validate rows before sending because validate happens on field blur.
[STSMACOM-525](https://issues.folio.org/browse/STSMACOM-525)

STSMACOM-525: Cannot add access status types

---

CHANGELOG.md
lib/Notes/components/NoteForm/NoteForm.js

It's needed to set initial boolean values for `popUpOnCheckOut` and `popUpOnUser` instead of default `undefined`
[STSMACOM-522](https://issues.folio.org/browse/STSMACOM-522)

STSMACOM-522: Disable save button for <NoteForm> when form were no changes.

---

CHANGELOG.md
lib/Notes/NoteViewPage/components/NoteView/NoteView.js

Add proper styles for Note details element to display details as they were saved
[STSMACOM-527](https://issues.folio.org/browse/STSMACOM-527)

STSMACOM-527 View Notes Record: List indentations are not retained

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Use `selectedIndex` when `locallyChangedQueryIndex` is not present during search. 
https://issues.folio.org/browse/STSMACOM-526

STSMACOM-526: Use selectedIndex when locallyChangedQueryIndex is not present

---

lib/LocationLookup/LocationForm.js

I screwed up in https://github.com/folio-org/stripes-smart-components/pull/1084 and removed the `value` by accident.
Thank you @zburke for catching this!

STSMACOM-523: Add missing value to locationOpts

---

CHANGELOG.md
lib/CustomFields/pages/ViewCustomFieldsRecord/ViewCustomFieldsRecord.js
translations/stripes-smart-components/en.json

`ViewCustomFieldsRecord` doesn't disappear even if no custom-fields are present.
If an accordion contains no content, the closed accordion shows a 0 badge.
If an accordion contains no content, the opened accordion shows a "No custom fields found" message.
[STSMACOM-470](https://issues.folio.org/browse/STSMACOM-470)
Also, change in ui-users was required ([UIU-2210](https://issues.folio.org/browse/UIU-2210))

STSMACOM-470: ViewCustomFieldsRecord must never return an empty element (<>)

---

CHANGELOG.md
lib/CustomFields/pages/ViewCustomFieldsRecord/ViewCustomFieldsRecord.js

If the section-title fetch returns before the custom-fields fetch, then
`visibleCustomFields` will be undefined, not an array. Thus, the
`...Loaded` properties of both `sectionTitle` and `customFields` need to
be tested, not just `sectionTitle`.
I believe this bug was introduced in #1093.
Refs [STSMACOM-531](https://issues.folio.org/browse/STSMACOM-531)

STSMACOM-531 validate array before accessing its length

---

lib/EditableList/readme.md

It is in fact possible to disable record creation on this component, but that functionality was undocumented... until now.

Document canCreate prop of EditableList

---

CHANGELOG.md
lib/CustomFields/utils/validateCustomFields.js
translations/stripes-smart-components/en.json

Add validation message for custom fields with whitespace values
[STSMACOM-532](https://issues.folio.org/browse/STSMACOM-532)

STSMACOM-532: Add validation for custom fields whitespace values

---

CHANGELOG.md
lib/CustomFields/utils/validateCustomFields.js

Fix edit a user record with a custom field.
This bug happened because of the `trim()` function on the custom fields value, and in case when custom field was not the text field, but radio buttons/multi-select/checkbox etc., the `trim()` function gave error when applied to an array or boolean.
[STSMACOM-535](https://issues.folio.org/browse/STSMACOM-535)

STSMACOM-535: Can't edit a user record with a custom field in Snapshot

---

CHANGELOG.md
lib/AddressFieldGroup/tests/AddressEdit-test.js
lib/ControlledVocab/tests/ControlledVocab-test.js
lib/CustomFields/components/CustomFieldsForm/tests/CustomFieldsForm-test.js
lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/HelpTextField/tests/HelpTextField-test.js
lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/OptionsField/tests/OptionsField-test.js
lib/Notes/NoteCreatePage/tests/NoteCreatePage-test.js
lib/Notes/NoteEditPage/tests/NoteEditPage-test.js
lib/Notes/NoteViewPage/components/NoteView/tests/note-view-test.js
lib/Notes/components/NoteForm/tests/note-form-test.js
lib/PasswordValidationField/tests/PasswordValidationField-test.js

As with [STCOM-880](https://issues.folio.org/browse/STCOM-880) (folio-org/stripes-components/pull/1620), since the
`react` `17` merge (#1123) PRs, some focus- and accordion-related tests
began failing. IRL, these components work just fine and the problem
appears to be a compatibility issue in BigTest OG itself.
[Event delegation changes in react
17](https://reactjs.org/blog/2020/08/10/react-v17-rc.html).
Refs [STSMACOM-541](https://issues.folio.org/browse/STSMACOM-541), [STSMACOM-474](https://issues.folio.org/browse/STSMACOM-474)

STSMACOM-541 skip flaky focus tests

---

CHANGELOG.md
lib/LocationLookup/LocationLookup.js

Issue: [STSMACOM-542](https://issues.folio.org/browse/STSMACOM-542)
Need to story [UIIN-1639](https://issues.folio.org/browse/UIIN-1639)
Related [PR](https://github.com/folio-org/ui-inventory/pull/1468)

STSMACOM-542: Add disabled prop for LocationLookup component

---

CHANGELOG.md
package.json

Change future release version to `7.1.0` so that no one thinks that these changes require release for Kiwi Bugfix

Change next release version from 7.0.1 to 7.1.0 to avoid confusion

---

CHANGELOG.md
lib/Notes/NoteViewPage/NoteViewPage.js
lib/Notes/NoteViewPage/components/NoteView/NoteView.js
lib/Notes/components/NoteForm/components/NoteFields/NoteFields.js

Add `id` to some elements to make it's easier to query them in e2e tests
[STSMACOM-606](https://issues.folio.org/browse/STSMACOM-606)

STSMACOM-606: Add id attribute to Note elements that are used in e2e tests

---

CHANGELOG.md
lib/ProxyManager/proxyUtil.js

As a staff user,
I want to see the patron's preferred first name in the Proxy Modal
so that I might address the patron properly.
condition, included preferredFirstName has been added to the getFullName function
https://issues.folio.org/browse/STSMACOM-615

STSMACOM-615 - Add preferred name to the Proxy Modal

---

lib/EntryManager/tests/entry-manager-test.js

Upgrading these to new interactors exported from `@folio/stripes-testing`.
I can imagine that we could find a way to *still make an entry manager interactor work for those entry manager that are rolled from scratch at the ui-module level...
A nav list, a button, callout are mostly the built-in interactors that are needed, along with some special ones to cover your `[data-test-whatever]` (or possibly better) containing elements.
Require a merge request on stripes-testing.

Upgrade entry manager tests

---

lib/AddressFieldGroup/AddressEdit/AddressEdit.js
lib/AddressFieldGroup/AddressEdit/AddressEditList.js
lib/AddressFieldGroup/AddressList/AddressList.js
lib/AddressFieldGroup/tests/interactor.js

React assumes DOM attributes with mixed case are react props and issues
a console warning about those it doesn't recognize:
> Warning: React does not recognize the `data-test-addressList-container`
> prop on a DOM element. If you intentionally want it to appear in the
> DOM as a custom attribute, spell it as lowercase `data-test-addresslist-container`
> instead. If you accidentally passed it from a parent component,
> remove it from the DOM element.
This must be merged after https://github.com/folio-org/stripes-testing/pull/171
Refs [UITEST-87](https://issues.folio.org/browse/UITEST-87), [STSMACOM-618](https://issues.folio.org/browse/STSMACOM-618)

STSMACOM-618 lower-case all data-test-... attributes

---

CHANGELOG.md
index.js
lib/CustomFields/utils/index.js
lib/CustomFields/utils/useCustomFields.js

https://issues.folio.org/browse/STSMACOM-622
In order to accomplish the work described in  https://issues.folio.org/browse/UIU-2170 we need a way to fetch custom fields for a specific module. The retrieval of custom fields is a bit exotic since it attaches a special header to the request but the good news is that there are already helpers which can be utilized to create a reusable hook. This PR just does that.

STSMACOM-622: Introduce useCustomFields hook

---

lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

https://issues.folio.org/browse/STSMACOM-620
*Problem*
We need to have the ability to change paneSubTitle when props change and change the text in the button in SearchFiled. All that needs to be done in the scope of the Browse call numbers feature.
*Solution*
Simple add additional props in SearchAndSort components.

STSMACOM-620: Add additional prop in SearchAndSort

---

lib/SearchAndSort/ConnectedSource/StripesConnectedSource.js
lib/SearchAndSort/SearchAndSort.js

In scope of 
https://issues.folio.org/browse/UIIN-1890
https://issues.folio.org/browse/UIIN-1897
issues,  we should be able to override the onNeedMore method and set new props for prev-next pagination.
Pagination was extended in https://issues.folio.org/browse/STCOM-923

STSMACOM-626 Add the ability to override onNeedMore method and add missing props

---

CHANGELOG.md
lib/EditableList/EditableListForm.js

If no initial values were provided, the lifecycle for syncing items would bomb out since `isEqual` doesn't do well at handling `undefined` parameters (just returns false in those cases) and so the underlying logic would attempt to access a property of the undefined value.
`EditableList` uses an internal array to track the editing state of items that has to be kept in sync with its props.
Sure, we could have just done a check for the existence of `props.initialValues` and called it a day... but no, them UNSAFE lifecycles gotta go. Moved the `buildStatusArray` function outside of the component, set up the old gDSFP function to handle async initial values, and made sure to sync things appropriately when items were edited, re-building the status array where necessary.
2 birds with one stone: …

STSMACOM-549 UI-Users bombs out when adding new loan owner.

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
lib/EntryManager/EntrySelector.js
lib/Settings/Settings.js

https://issues.folio.org/browse/STSMACOM-617
In the current implementation, when you click on the link in the "settings" panel, the focus does not switch to the newly opened one. 
- Add an focus to first focusable element in Pane

STSMACOM-628 Settings : Move focus to second pane

---

CHANGELOG.md
lib/LocationLookup/LocationModal.js

https://issues.folio.org/browse/STSMACOM-629
Believe it or not, some library systems have more than 2,000 libraries. Let's hope there aren't any with more than 5,000. This is the "dead-simple/deal-with-it-later fix", as Zak put it.

STSMACOM-629: Bump location query limits to 5000

---

lib/AddressFieldGroup/tests/AddressEditList-test.js

The two disabled blocks fail reliably in CI:
```
FAILED TESTS:
Address List
expanding the list
✖ "before each" hook for "displays two addresses"
Chrome 98.0.4758.80 (Linux x86_64)
NoSuchElementError: did not find address list
[...]
adding a new address
✖ "before each" hook for "displays the edit form"
Chrome 98.0.4758.80 (Linux x86_64)
NoSuchElementError: did not find address list
[...]
```

disable tests that fail reliably

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml

Compile translations before running tests in order to keep formatjs from
complaining, leading to a quieter console.

compile translations before running tests

---

CHANGELOG.md
lib/LocationSelection/LocationInput.js

https://issues.folio.org/browse/STSMACOM-629
This is followup to https://github.com/folio-org/stripes-smart-components/pull/1185 -- I missed one spot where the limit needed to be increased.

STSMACOM-629: Increase limit for locations

---

CHANGELOG.md
lib/CustomFields/pages/ViewCustomFieldsRecord/tests/ViewCustomFieldsRecord-test.js
lib/CustomFields/pages/ViewCustomFieldsRecord/tests/interactor.js
lib/Notes/NoteViewPage/components/NoteView/tests/interactor.js
lib/Notes/NoteViewPage/components/NoteView/tests/note-view-test.js

How a component renders in the DOM is considered private and thus is
subject to change without warning. Nonetheless, some tests inspected
the DOM to assess whether a `<NoValue>` component had been rendered, and
when its internal state changed these tests began to fail.
Assess the presence of `<NoValue>` via its interactor.
Refs [STSMACOM-638](https://issues.folio.org/browse/STSMACOM-638), [STCOM-936](https://issues.folio.org/browse/STCOM-936)

STSMACOM-638 tests must not inspect NoValue's DOM structure

---

lib/Notes/NoteViewPage/components/NoteView/tests/interactor.js
lib/Notes/NoteViewPage/components/NoteView/tests/note-view-test.js

Nicer test ergonomics from the NoteView tests that I inadvertently missed in #1201. 
Refs [STSMACOM-638](https://issues.folio.org/browse/STSMACOM-638), [STCOM-936](https://issues.folio.org/browse/STCOM-936)[](https://github.com/zburke)

STSMACOM-638 nicer test ergonomics

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSortQuery.js

https://issues.folio.org/browse/STSMACOM-637
I noticed this bug when working on lazy loading. The ui-courses would just go into an infinite loop and keep re-rendering and reloading all resources. This happens because `SearchAndSortQuery` execs `history.push` for the same url as the current location url.

STSMACOM-637: Do not push to history if the url did not change

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js

As noted by helpful comments from @miketaylor in this file, react-redux
does not receive defaultProps values, and hence can't pass them onto
stripes-connect for substitution in a manifest. T
The situation we ended up in was that our default value was being
ignored, causing evaluation of the manifest to fail and thus the query
would never fire.
CC: @andrewish
Refs [STSMACOM-639](https://issues.folio.org/browse/STSMACOM-639)

STSMACOM-639 correctly provide default sortby value

---

CHANGELOG.md
lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js

https://issues.folio.org/browse/STSMACOM-640
`DateRangeFilter` component uses `React.memo` and check equality of only `selectedValues` prop. But we are passing a `onChange` callback to the `DateRangeFilter` component, which may depend on other parameters and, accordingly, the reference to the actual `onChange` callback may change. As a result, when the `applyFilter` function is called, `onChange` is used from the previous render, it causes problems in some applications.
- Check `onChange` prop equality on `React.memo` comparison function;
- Replace `applyFilter` function from `useEffect` hook to prevent infinite rerenders;

STSMACOM-640 Applying a date range filter clears other filters

---

CHANGELOG.md
lib/Notes/NotePopupModal/NotePopupModal.css
lib/Notes/NotePopupModal/NotePopupModal.js
lib/Notes/NoteViewPage/components/NoteView/NoteView.css
lib/Notes/NoteViewPage/components/NoteView/NoteView.js
lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js

Purpose: https://issues.folio.org/browse/STSMACOM-642
Approach: `<div>` usage instead of `<span>` for note details container, add rigth paddings.
Screenshot:

STSMACOM-642 Users pop -up note has slight overwrite in "Details:"

---

lib/CustomFields/utils/useCustomFieldsFetch.js
lib/CustomFields/utils/useOptionsStatsFetch.js
lib/CustomFields/utils/useSectionTitleFetch.js

The memory leak  was because of the async action(response transformation into json format) after component unmounted in next hooks:
- useCustomFieldsFetch.js
- useOptionsStatsFetch.js
- useSectionTitleFetch.js
[STSMACOM-505](https://issues.folio.org/browse/STSMACOM-505)

STSMACOM-505 memory leak in EditCustomFieldsRecord

---

CHANGELOG.md
lib/Notes/NotesSmartAccordion/tests/interactors/notes-accordion.js

Added toggleAccordion method to NotesAccordion 
[STSMACOM-645](https://issues.folio.org/browse/STSMACOM-645)

STSMACOM-645: Notes Accordion is Not Closed After Deleting a Note

---

CHANGELOG.md
lib/LocationLookup/LocationModal.js

Like other institutions, libraries, and locations, campuses also need a
`limit` clause in order to overwrite the default limit of 10.
Refs [STSMACOM-647](https://issues.folio.org/browse/STSMACOM-647)

STSMACOM-647 include missing limit clause for campuses

---

CHANGELOG.md
package.json

Un-pin axe-core from "4.3.3", moving back to "^4.3.5".
[STSMACOM-546](https://issues.folio.org/browse/STSMACOM-546)

STSMACOM-546: Un-pin axe-core from 4.3.3

---

CHANGELOG.md
lib/EditableList/EditableListForm.js
translations/stripes-smart-components/en.json

Added translation for 'Actions' column.
[STSMACOM-519](https://issues.folio.org/browse/STSMACOM-519)

STSMACOM-519: EditableList: `actions` column title should be capitalized and translated

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Search results with a single hit should automatically open the detail view
Added a condition which will open the detail view when there's a single hit
[STSMACOM-661](https://issues.folio.org/browse/STSMACOM-661)
https://user-images.githubusercontent.com/101391438/166885084-fa398fca-734b-4c98-9603-66950948b7ff.mp4

STSMACOM-661 Search results with a single hit should automatically open the detail view

---

CHANGELOG.md
lib/ColumnManager/ColumnManager.js
lib/ColumnManager/readme.md
lib/ColumnManager/useColumnManager.js

If present and true, this persists the selection of columns into subsequent sessions.
Fixes STSMACOM-662.
(I can't wait around for the Grand Unified Theory in STCOR-601, I need to get this done ASAP and with minimal disruption.)

STSMACOM-662 Add optional `persist` prop to <ColumnManager>

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml

You gotta authenticate against the repository you publish to. The intial
commit authenticated against the production repo but published to the CI
repo. Whoops.
Refs [STSMACOM-664](https://issues.folio.org/browse/STSMACOM-664)

STSMACOM-664 correctly set auth URL

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Add pagingCanGoNext and pagingCanGoPrevious props to SearchAndSort component instead of paginationBoundaries.
This will allow us to disable pagination buttons separately, and not all at once

STSMACOM-665 Add pagingCanGoNext and pagingCanGoPrevious props to SearchAndSort component

---

CHANGELOG.md
lib/EditableList/EditableList.css
lib/EditableList/EditableListForm.js
lib/EditableList/ItemEdit.js
lib/EditableList/ItemView.js
lib/ViewMetaData/tests/ViewMetaData-test.js

https://issues.folio.org/browse/STSMACOM-670
At the moment, the `<EditableListForm >` component has a number of problems related to displaying on small screens:
- When changing the "isEditing" state of a row, it becomes difficult or even impossible to get to the desired action button. 
- When scrolling, column headers do not move with their respective columns.
How it looks now:
How it looks after changes:
NB: Requires https://github.com/folio-org/stripes-components/pull/1820 first
---
<details>
<summary>Places, where "EditableListForm" used:</summary>'
**Settings**:
- Agreements:
- Supplementary property pick list setup
- Pick lists
- Pick lists values
- Circulation:
- Requests:
- Request cancellation reasons
- Courses:
- Terms
- Course Types
- Cource Departments
- Processing Statuses
- …

STSMACOM-670 Unable to scroll to action buttons in <EditableListForm> on small screens

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

To enhance accessibility 
[UIDATIMP-1162](https://issues.folio.org/browse/UIDATIMP-1162)
[STSMACOM-669](https://issues.folio.org/browse/STSMACOM-669)

STSMACOM-669: Enable nonInteractiveHeaders prop to be passed to MCL via SearchAndSort

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

- In `ui-data-import`, We are saving `searchTerm` to `sessionStorage` and pass it to `<SearchAndSort />` as `query` property of `parentResources` prop. But the problem is that `search box` is getting its initial value from local state `locallyChangedSearchTerm`. The logic is comparing it with `undefined` which is always false because `locallyChangedSearchTerm` has initial value of `""` and never gets initial value from `props`.
- Also when refresh the page `searchTerm` will be lost but searched results are persisted because of url query string.
- https://issues.folio.org/browse/STSMACOM-671

STSMACOM-671: Search term isn't persisted in SearchAndSort

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/tests/SearchAndSort-test.js

Fixed the issue, where `Search/Filter` pane is not in a collapsed state when we are on the **Data import/View all log** page AND collapse the `Search/Filter` pane by clicking the arrow at the top of the pane AND go to another app or Settings area and then return to **Data import/View all**.
The `Search/Filter` pane **being in a collapsed state should persist**
These changes also impact on **ui-inventory** and **ui-requests**
Link:
[STSMACOM-677](https://issues.folio.org/browse/STSMACOM-677)
https://user-images.githubusercontent.com/85172747/175303114-1c681704-3e2c-4971-a947-52f82f2d5df4.mp4

STSMACOM-677: Search/Filter pane is not in a collapsed state

---

lib/SearchAndSort/SearchAndSortQuery.js
lib/SearchAndSort/SearchAndSortQuery.md

provide a boolean prop `setQueryOnMount` - false by default - that can be used to call the querySetter, so that any initial query state can be applied to the application's query.

STSMACOM-678 - SASQ should provide way to apply initial query on mount.

---

CHANGELOG.md
lib/LocationLookup/LocationForm.js
lib/LocationLookup/LocationModal.js

https://issues.folio.org/browse/STSMACOM-679
Even though initial values change, the form is not re-rendered. This should be happening with `enableReinitialize` set to `true`.
This looks like a legit issue in redux-form:
https://github.com/redux-form/redux-form/issues/2572#issuecomment-754261512
The correct way to fix it would be to get rid of the redux-form and replace it with the final-form (which we should do in the future).

STSMACOM-679:  Mark initialValues as immutable in LocationForm

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

Fix issue when `<SearchAndSort>` query doesn't return to old value, when you go back in browser history
Component's `locallyChangedSearchTerm` state value is prioritized over query parameter in url, so we need to update it when url value changes
https://user-images.githubusercontent.com/19309423/174809563-e0ebd28f-f65e-4ed2-9583-70021aab912a.mp4
[STSMACOM-676](https://issues.folio.org/browse/STSMACOM-676)

STSMACOM-676 Reset SearchAndSort query going back in history

---

CHANGELOG.md
package.json

`mod-notes` module was updated with breaking changes to `/note-types` endpoint and updated interface version to `3.0`
However, these changes don't affect `/notes` endpoint so `stripes-smart-components` can safely use either `2.0` or `3.0`

STSMACOM-686 Support notes interface version 3.0

---

CHANGELOG.md
lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js

https://issues.folio.org/browse/STSMACOM-705
Based on the work in https://issues.folio.org/browse/MODUSERS-212 `addressType` is now a required field.
This PR marks it as a required field.

STSMACOM-705: Mark addressType as require

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js

For tickets:
https://issues.folio.org/browse/UITEN-225
https://issues.folio.org/browse/UITEN-226
https://issues.folio.org/browse/UITEN-227
https://issues.folio.org/browse/UITEN-228
It's required to hide/disable create button in "View only" mode.
Solution: add `canCreate` prop to `ControlledVocab.js` component.

STSMACOM-704 Add props to ControlledVocab components

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/tests/SearchAndSort-test.js

Problem:
If the user entered a search term and then modified the `qindex`, the search term would be lost or changed to whatever was currently in the query parameters.
Approach:
Check if there is a locally changed search term before syncing to the query parameter value.

STSMACOM-707 retain locallyChangedSearchTerm when syncing to query parameters

---

CHANGELOG.md
lib/Settings/Settings.js

[STSMACOM-709](https://issues.folio.org/browse/STSMACOM-709)
[UIDATIMP-1321](https://issues.folio.org/browse/UIDATIMP-1321)
https://user-images.githubusercontent.com/85172747/204260269-af72a0ae-4766-4083-8f0d-b77fde15fe3d.mp4
https://user-images.githubusercontent.com/85172747/204260291-6f0cacf5-5ad0-4561-97a5-702d03f377b1.mp4

STSMACOM-709: Disabled sorting after double click on the settings link

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

Feature merged in stripes-components in https://github.com/folio-org/stripes-components/pull/1915 This PR exposes the props to apps that use SearchAndSort.

Expose MCL sticky columns props through SearchAndSort

---

CHANGELOG.md
lib/PasswordValidationField/PasswordValidationField.js

This PR relates to [STSMACOM-706](https://issues.folio.org/browse/STSMACOM-706)
The query was removed as it was invalid and not used by BE

STSMACOM-706 PasswordValidationField swallows error messages from API queries

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

`<SearchAndSort>` no longer accepts `paginationBoundaries`, a long-deprecated prop that it passed along to `<MCL>`, where it was also deprecated and where, finally in v11, it is being removed.
Refs [STSMACOM-717](https://issues.folio.org/browse/STSMACOM-717), [STCOM-1067](https://issues.folio.org/browse/STCOM-1067)

STSMACOM-717 SearchAndSort no longer accepts paginationBoundaries

---

CHANGELOG.md
package.json
yarn.lock

`@rehooks/local-storage` is no longer broken so we can once again depend on the latest version of it, allowing us to remove `resolutions` entries for it that are scattered about.
Refs [STSMACOM-723](https://issues.folio.org/browse/STSMACOM-723)

STSMACOM-723 unpin @rehooks/local-storage

---

yarn.lock

Update yarn.lock to address CVE-2022-25860.

update yarn.lock to avoid CVE-2022-25860

---

lib/ConfigManager/ConfigManager.js

fix: Nullish coalescing
Added null coalescing back to component (also brought previous null safety in line for code consistency)
refs STSMACOM-720
Coversation on the previous PR: https://github.com/folio-org/stripes-smart-components/pull/1313#issuecomment-1415522670

STSMACOM-720: Update <ConfigManager> to work with mod-settings (Small fix)

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

When we make request with the query index `Title (all)` in the `Instance` segment and then switch to `Holdings` and make request here, but we don't have the `Title (all)` in the `Holdings` segment, we will see an [error](https://issues.folio.org/secure/attachment/58884/2023-03-09_15h31_41.mp4). Therefore, we need to check if the selected segment has previously picked the query index or not.
[STSMACOM-735](https://issues.folio.org/browse/STSMACOM-735)
https://user-images.githubusercontent.com/77053927/224097687-198067ff-1c51-4218-8a8a-492decab032e.mp4

STSMACOM-735: Reset the previously selected query index when there is none in the next selected segment.

---

CHANGELOG.md
lib/ColumnManager/useColumnManager.js

https://issues.folio.org/browse/STSMACOM-719
`useColumnManager` hook contains a variable that is a dependency in other hooks:
```
const defaultColumnKeys = Object.keys(columnMapping);
```
```
const orderedVisibleColumns = useMemo(() => {
const visibleColumnsSet = new Set(visibleColumns);
return defaultColumnKeys.filter(key => visibleColumnsSet.has(key));
}, [defaultColumnKeys, visibleColumns]);
```
Since each re-render creates a new array of keys, changing the value of the reference of this variable will entail a number of redundant renders of dependent components.
<details>
<summary>Preview</summary>
</details>
---
Memoization in this case is a more profitable operation than calling an additional rerender of an MCL with a hundred elements.
<details>
<summary>Preview</summary>
</details>

STSMACOM-719 Optimize `useColumnManager` to reduce redundant renders

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Fix a page crush if `searchableIndexes` prop is missing. This is related to the previous [PR](https://github.com/folio-org/stripes-smart-components/pull/1328).
[STSMACOM-735](https://issues.folio.org/browse/STSMACOM-735)

STSMACOM-735: Fix a page crush if `searchableIndexes` prop is missing. 

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

* Reset the previously selected query index when there is none in the next selected segment.
* Fix a page crash if `searchableIndexes` prop is missing.
Refs STSMACOM-735

STSMACOM-735 Reset query index when there is none in the next selected segment

---

CHANGELOG.md
lib/Notes/NotePopupModal/NotePopupModal.js

Reset `isNotesLoading` flag when handling load notes request
https://user-images.githubusercontent.com/19309423/229775237-7db89272-f933-4873-a6cd-253b6695ad8e.mp4
[STSMACOM-741](https://issues.folio.org/browse/STSMACOM-741)

STSMACOM-741 Fix notes pop-up didn't appear in Checkout app when first checked out user didn't have notes

---

lib/SearchAndSort/makeQueryFunction.js
lib/SearchAndSort/readme.md

More configurable makeQueryFunction
The boolean `escape` parameter is replaced by a `config` object, which can contain multiple configuration options. These at present include:
* `escape` (boolean) — as before, specifies whether to escape quote and backslash values in the query [default: `true`]
* `rightTrunc` (boolean) — whether to append `*` to query terms [default: `true`].
And of course it will be easy to add other such entries later if we need them.
This version of the function is 100% backwards-compatible with the previous version: a boolean can be passed in place of the config object, and is interpreted as the value of `config.escape`. As before, this defaults to true if not specified.

More configurable makeQueryFunction

---

CHANGELOG.md
lib/EntryManager/ConnectedDetail.js
lib/EntryManager/ConnectedWrapper.js
lib/EntryManager/EntrySelector.js
lib/EntryManager/EntryWrapper.js
lib/EntryManager/readme.md

The `<EntryList>` component was created on the assumption that the records it manages are returned in full when a list is requested: so, for example, the list of records returned from `/path/to/endpoint` are each the same shape as the individual ones obtained by ID at paths like `/path/to/endpoint/12335`. This pattern is generally followed by most web-service endpoints provided by most FOLIO modules.
Some modules, however, return a list of summary records (for example, just ID and title), so that it's necessary to fetch each full record separately by ID. When `<EntryList>` is used to manage records on such an endpoint, the path to that service should be passed in as the `resourcePath` prop. When this is done, the full record is fetched each time a user views or edits a record.
This is …

Optional `resourcePath` prop for `<EntryManager>`

---

lib/EntryManager/EntryWrapper.js

Previously, if the back-end reported an error, it would never be extracted from the response body and an empty error toast would be displayed. Now we extract the response body and display that.

Report error-messages when saving a record in <EntryManager>

---

CHANGELOG.md
index.js
lib/Settings/Settings.js

https://issues.folio.org/browse/STSMACOM-759
In order to implement consortium-related components, it would be useful not to write all from scratch, but use existing ones.

STSMACOM-759 Expose `<EntryForm>` and `<EntrySelector>` components for reuse

---

CHANGELOG.md
lib/EntryManager/EntrySelector.js
lib/EntryManager/EntryWrapper.js
lib/EntryManager/readme.md

The `parseInitialValues` function is now applied correctly when
`resourcePath` is defined (see STSMACOM-757) so that full records are
loaded from a WSAPI.
Previously, the transformation would be applied to the brief version
of the record before the full record was loaded, so that fields that
occur only in the full version of the record were not transformed.
Also, I have documented these previously undocumented props.
Fixes STSMACOM-761.

`<EntryManager>`: `parseInitialValues` prop works with `resourcePath`

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Update `locallyChangedSearchTerm` when `query` changes, but keep value when `qindex` changes
This can happen when user is switching between Search modes, and there are saved `query` values for previous searches
https://github.com/folio-org/stripes-smart-components/assets/19309423/ba58b0e9-3a00-473d-8ac6-dcc22aa81e7a
[STSMACOM-758](https://issues.folio.org/browse/STSMACOM-758)
https://github.com/folio-org/ui-inventory/pull/2177

STSMACOM-758 Update `locallyChangedSearchTerm` when `query` changes, but keep value when `qindex` changes

---

CHANGELOG.md
lib/EntryManager/EntrySelector.js
lib/EntryManager/tests/entry-manager-test.js
tests/helpers.js

User Settings Permission sets: Disable editing for users with "Setting (Users): View all settings" permission
Disable 'Edit' button when user do not have permissions to edit.
**Note:** Added unit test to test new code. Refer to test result on screenshot 2 for the same. However, coverage seems to be zero. Coverage seems to be 100% locally.
behavior with diku login
behavior with another user with permission "Settings (Users): Can view permission sets" **only**
screenshot from bigtest
https://issues.folio.org/browse/STSMACOM-766

STSMACOM-766 - disable edit button when user doesn't have permission to edit

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSortQuery.js

users are not sorted by display-name
Propagate sort fields too (along with search fields and filter parameters). This will provide correct ns values to querySetter provided via props.
NOTE: Locally coverage is showing 100%. CI script is probably buggy now. I have observed the same in couple of the earlier PRs.
screencast - https://issues.folio.org/secure/attachment/64170/image-2023-07-11-12-04-56-189.png
https://issues.folio.org/browse/STSMACOM-770

STSMACOM-770 - propagate sort fields while applying filters too

---

CHANGELOG.md
lib/SearchAndSort/components/CheckboxFilter/CheckboxFilter.js

Pass `labelInfo` prop to checkboxes in `<CheckboxFilter>`. This can be used with facets that need to render facet counts
[STSMACOM-773](https://issues.folio.org/browse/STSMACOM-773)

STSMACOM-773 Pass `labelInfo` prop to checkboxes in `<CheckboxFilter>`

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml

In CI, bump NodeJS from v16 to v18.
Refs [STSMACOM-772](https://issues.folio.org/browse/STSMACOM-772)

STSMACOM-772 use NodeJS v18 in CI

---

CHANGELOG.md
lib/EditableList/EditableListForm.js
lib/EditableList/tests/EditableList-test.js

https://issues.folio.org/browse/STSMACOM-774
https://issues.folio.org/browse/UICONSET-112
The consortium manager requires the ability to handle the form's status (editing) change outside of the component to prevent some actions.
https://github.com/folio-org/stripes-smart-components/assets/88109087/7f22fded-77f2-4efb-8c69-494d43faced2

STSMACOM-774 Provide the ability to handle the status change of the `<EditableListForm>`

---

CHANGELOG.md
package.json
yarn.lock

Provide missing dependencies:
* `uuid`
Omit unused dependencies:
* `react-transition-group`
* `react-virtualized-auto-sizer`
Refs [STSMACOM-776](https://issues.folio.org/browse/STSMACOM-776)

STSMACOM-776 provide missing dependencies

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

If the advanced search option is already selected and a user clicks `Search` in the advanced search modal, then:
- filters shouldn't be reset;
- url shouldn't be changed twice.
[STSMACOM-777](https://issues.folio.org/browse/STSMACOM-777)
https://github.com/folio-org/ui-inventory/pull/2255
in the related PR

STSMACOM-777: Do not reset advanced search filters if the advanced search option is already selected.

---

lib/SearchAndSort/SearchAndSort.js

Don't reset filters after changing a search option.
[STSMACOM-777](https://issues.folio.org/browse/STSMACOM-777)
https://github.com/folio-org/ui-inventory/pull/2256
in the related PR

STSMACOM-777: Don't reset filters after changing a search option.

---

lib/SearchAndSort/SearchAndSortQuery.js
lib/SearchAndSort/tests/SearchAndSortQueryTests/SASQTestHarness.js
lib/SearchAndSort/tests/SearchAndSortQueryTests/SearchAndSortQuery-test.js

feat: Add SASQ event for search submit and all submit
Added internalSetState call for submit all and submit search, which does not change internal state itself, but fires an event that queryStateReducer can use to trigger changes from those events
refs: https://issues.folio.org/browse/STSMACOM-775

STSMACOM-775: Search And Sort Query - fire queryStateReducer events on search submit

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Add possible to pass paneTitleRef from SearchAndSort to Pane that already support paneTitleRef
https://issues.folio.org/browse/STSMACOM-779

STSMACOM-779: Add possible to pass paneTitleRef from SearchAndSort to Pane that already support paneTitleRef

---

CHANGELOG.md
lib/CustomFields/pages/EditCustomFieldsSettings/EditCustomFieldsSettings.js
lib/CustomFields/pages/EditCustomFieldsSettings/tests/EditCustomFieldsSettings-test.js
lib/CustomFields/pages/EditCustomFieldsSettings/tests/interactor.js
tests/network/config.js

Correctly save an empty custom fields list. Previously, an empty list would result in an NPE, calling `map` on a null value. Now, if the value is null, functions return an empty array.
Tests related to custom fields removal were disabled long ago because they fail for unclear reasons and I was unable to resuscitate them now.
Refs [STSMACOM-781](https://issues.folio.org/browse/STSMACOM-781)

STSMACOM-781 correctly save empty custom-fields list

---

lib/SearchAndSort/SearchAndSortQuery.js

[this commit](https://github.com/folio-org/stripes-smart-components/commit/d197a0) added some necessary event handling and `changeType`s to SASQ internals, but it did not account for leftover `changeType` that may have been depended upon by app code.
If SASQ has `setQueryOnMount = true` or an `initialSearchState` applied, a `submitAll()` is carried out when the component mounts. State is initialized with an `init.reset` changeType. Previously, the submitAll() call had no `changeType` applied, so `init.reset` remained - and thus, the expectant code was built.
This code adds the `changeType` as a default parameter for the methods that we would expect, with overridden `changeType`s applied for those situational cases where `submitAll()` and `submitSearch` are called - that is, at mount time, …

STSMACOM-785 - add default parameters to onSubmit, submitAll internal handlers

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

Make support input and textarea as an input field by adding a new inputType prop
https://github.com/folio-org/stripes-smart-components/assets/19309423/ecf9ec53-6699-4366-a1cf-eaac81167e3e
[STSMACOM-786](https://issues.folio.org/browse/STSMACOM-786)
https://github.com/folio-org/stripes-components/pull/2158
https://github.com/folio-org/ui-inventory/pull/2322
https://github.com/folio-org/stripes-components/pull/2158

STSMACOM-786  Added `inputType` prop to `<SearchAndSort>` component to support both input and textarea search boxes

---

CHANGELOG.md
lib/Notes/utils/getMetadataFormResponse.js

Show the `username` in the `last updated` accordion in the Note editing pane.
[STSMACOM-748](https://issues.folio.org/browse/STSMACOM-748)

STSMACOM-748: Show the username in the 'last updated' accordion in the Note editing pane.

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/readme.md

Added `indexRef` and `inputRef` props to `<SearchAndSort>`
[STSMACOM-788](https://issues.folio.org/browse/STSMACOM-788)
https://github.com/folio-org/ui-inventory/pull/2335
https://github.com/folio-org/stripes-components/pull/2169

STSMACOM-788 Added `indexRef` and `inputRef` props to `<SearchAndSort>`

---

CHANGELOG.md
lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js
lib/Notes/NotesSmartAccordion/tests/notes-smart-accordion-test.js
lib/Notes/components/NotesAccordion/NotesAccordion.js

[STSMACOM-789](https://issues.folio.org/browse/STSMACOM-789) -  Extend NotesAccordion and NotesSmartAccodion components to accept a prop  hideNewButton

STSMACOM-789 - Extend NotesAccordion and NotesSmartAccodion components to accept a prop  hideNewButton

---

CHANGELOG.md
lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js
lib/Notes/NotesSmartAccordion/tests/notes-smart-accordion-test.js
lib/Notes/components/NotesAccordion/NotesAccordion.js

Master branch PR reference - https://github.com/folio-org/stripes-smart-components/pull/1414

STSMACOM-789-poppy-dcb - Extend NotesAccordion and NotesSmartAccodion components to accept a prop hideNewButton

---

CHANGELOG.md
lib/Tags/Tags.js

Support `mutateEntity` callback to be able to use `react-queries`. Required by https://github.com/folio-org/ui-inventory/pull/2371/

STSMACOM-792: Extend `Tags` component to accept `mutateEntity` prop

---

CHANGELOG.md
lib/AddressFieldGroup/AddressEdit/AddressEdit.css
lib/AddressFieldGroup/AddressView/AddressView.css

https://issues.folio.org/browse/STSMACOM-791
`postcss-color-function` is a neglected dependency that we don't like anymore since it no longer emulates future CSS spec. In order to remove this, we have to migrate to native CSS functionality. Hello `color-mix()`!

STSMACOM-791 use native blending for addressEdit/addressView

---

CHANGELOG.md
lib/CustomFields/pages/EditCustomFieldsSettings/EditCustomFieldsSettings.js
lib/CustomFields/pages/EditCustomFieldsSettings/tests/EditCustomFieldsSettings-test.js

This PR is related to [FCFIELDS-44](https://issues.folio.org/browse/FCFIELDS-44) and should be merged along with [FCFIELDS PR#41](https://github.com/folio-org/folio-custom-fields/pull/41).
This PR updates the payload that `<EditCustomFieldsSettings>` is sending to Okapi when updating custom fields. This modification aligns the payload with the revised [putCustomFieldCollection.json](https://github.com/folio-org/folio-custom-fields/pull/41/files#diff-943241611b2670b400a2d4ad16b9a76dbf12925cadaac1c5c1ac91bb319c36a0) schema.
With this change the `<EditCustomFieldsSettings>` component requires at least `custom-fields 3.0`.
* This requires [FCFIELDS PR#41](https://github.com/folio-org/folio-custom-fields/pull/41) to be merged beforehand as a prerequisite.
* Needs to be merged together with …

FCFIELDS-44 Update payload used by `<EditCustomFieldsSettings>`

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
lib/ControlledVocab/tests/ControlledVocab-test.js
lib/ControlledVocab/tests/ControlledVocabErrors-test.js
lib/ControlledVocab/tests/mountComponent.js
tests/network/config.js
translations/stripes-smart-components/en.json

Show successful toast notifications for Create and Edit actions in `<ControlledVocab>`
https://github.com/folio-org/stripes-smart-components/assets/19309423/e4d5587f-7ac9-4362-979d-4291f3b5f6dc
https://github.com/folio-org/stripes-smart-components/assets/19309423/bae99c57-f4d1-47a8-a6b4-35e43045508e
[STSMACOM-796](https://issues.folio.org/browse/STSMACOM-796)

STSMACOM-796 Show successful toast notifications for Create and Edit actions in `<ControlledVocab>`

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
lib/ControlledVocab/tests/ControlledVocab-test.js
lib/ControlledVocab/tests/mountComponent.js

`<ControlledVocab>` - last updated by column - show "System" when items are created by system user
[STSMACOM-797](https://issues.folio.org/browse/STSMACOM-797)

STSMACOM-797 `<ControlledVocab>` - last updated by column - show "System" when items are created by system user

---

CHANGELOG.md
lib/CustomFields/components/CustomFieldsForm/tests/CustomFieldsForm-test.js
lib/CustomFields/components/FieldAccordion/FieldAccordion.js
lib/CustomFields/constants.js
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
lib/CustomFields/pages/EditCustomFieldsRecord/tests/EditCustomFieldsRecord-test.js
lib/CustomFields/pages/EditCustomFieldsSettings/tests/EditCustomFieldsSettings-test.js
lib/CustomFields/pages/ViewCustomFieldsRecord/ViewCustomFieldsRecord.js
lib/CustomFields/pages/ViewCustomFieldsRecord/tests/ViewCustomFieldsRecord-test.js
tests/network/config.js
translations/stripes-smart-components/en.json

See [STSMACOM-800](https://issues.folio.org/browse/STSMACOM-800).
UI work for [FCFIELDS-46](https://issues.folio.org/browse/FCFIELDS-46).
This PR introduces a new field type for custom fields, `DATE_PICKER`, designed to handle ISO 8601 date values. Custom fields UI components have been updated to utilize this new field type. To add and edit date values the `<Datepicker>` component from `stripes-components` is used. Tests have been updated and translations added.
The required backend work has been done in [folio-custom-fields PR #42](https://github.com/folio-org/folio-custom-fields/pull/42).
[screen-capture.webm](https://github.com/folio-org/stripes-smart-components/assets/25431636/021da625-655f-417e-bde4-9d28ed886e46)

STSMACOM-800 Add field type `DATE_PICKER` to custom fields components.

---

CHANGELOG.md
lib/CustomFields/pages/ViewCustomFieldsRecord/ViewCustomFieldsRecord.js

https://issues.folio.org/browse/STSMACOM-798
Proptypes no longer required: 
- expanded
- onToggle
As these can be implemented within an `AccordionStatus` component, which will provide those values from context.

STSMACOM-798 Remove required validation from 2 ViewCustomFieldRecord propTypes

---

CHANGELOG.md
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
lib/CustomFields/pages/EditCustomFieldsRecord/tests/EditCustomFieldsRecord-test.js
lib/CustomFields/readme.md

See https://issues.folio.org/browse/STSMACOM-806.
Adds a `onComponentLoad` prop to `<EditCustomFieldsRecord>` that takes a callback function.
This will allow parent components to know when the rendering of form fields is complete.
`<EditCustomFieldsRecord>` renders its `<Field>` components asynchronously after data was fetched from the `/custom-fields` API.

[STSMACOM-806] Add `onComponentLoad` prop to `<EditCustomFieldsRecord>`

---

CHANGELOG.md
lib/EditableList/EditableListFinalForm.js
lib/EditableList/EditableListForm.js
lib/EditableList/ItemEdit.js

Fix issue with resetting unsaved changes after failed update
Final-form by default uses initial values when resetting a form. We need to prevent that from happening by using `keepDirtyOnReinitialize: true`
https://github.com/folio-org/stripes-smart-components/assets/19309423/da56f7c8-6e7b-46d2-aa5c-187a47e89ddf
https://github.com/folio-org/stripes-smart-components/assets/19309423/d4d3a935-d1e7-45c8-97c6-db73c5acb893
[STSMACOM-809](https://folio-org.atlassian.net/browse/STSMACOM-809)

STSMACOM-809 Fix issue with resetting unsaved changes after failed update

---

CHANGELOG.md
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
lib/CustomFields/pages/EditCustomFieldsRecord/tests/EditCustomFieldsRecord-test.js
lib/CustomFields/readme.md

See https://issues.folio.org/browse/STSMACOM-805.
Added a default accordion label to `<EditCustomFieldsRecord>`.
Done in the same way its been done in `<ViewCustomFieldsRecord>`.

[STSMACOM-805] Set default title for Accordion in `<EditCustomFieldsRecord>`

---

lib/EditableList/EditableList.js
lib/EditableList/EditableListFinalForm.js

EditableList - keep changed values when request fails, but clear them when clicking cancel
Previously I added `keepDirtyOnReinitialize` to fix form reset when requests failed, but it caused the cancel button not resetting edited values to initial values
Turns out the root cause was constantly changing `initialValues` which in turn causes form reinitialize on each render
Now `initialValues` are memoized
https://github.com/folio-org/stripes-smart-components/assets/19309423/481e5597-da06-4ab4-9881-29c642f3899e
[STSMACOM-809](https://folio-org.atlassian.net/browse/STSMACOM-809)

STSMACOM-809 EditableList - keep changed values when request fails, but clear them when clicking cancel (follow-up)

---

lib/EditableList/ItemEdit.js

`<FieldComponent>` uses structure `{...(error && { error: error.fieldErrors[name] })}` to pass validation errors if they exist
`fieldComponents` used a different one, where `error` property would be `undefined` but still existed. I think there's a `hasOwnProperty` somewhere under the hood that checks existance of `erro` but not it's value that prevents error to be shown
Fix is to match the way `error` is passed to `fieldComponents`
##Screenshots
https://github.com/folio-org/stripes-smart-components/assets/19309423/0bead1c1-86e4-4175-b10c-e1d66435d46f
[STSMACOM-809](https://folio-org.atlassian.net/browse/STSMACOM-809)

STSMACOM-809 Pass validation error to `fieldComponents` in the same format as in `<FieldComponent>`

---

CHANGELOG.md
lib/EditableList/EditableListForm.js
lib/EditableList/readme.md

Make `confirmationMessage`  prop accept a function that will be called with deleted item id
[STSMACOM-810](https://folio-org.atlassian.net/browse/STSMACOM-810)

STSMACOM-810 `<EditableList>` - make `confirmationMessage` prop accept a function

---

CHANGELOG.md
lib/EditableList/EditableListForm.js

Don't show an error when a user clicks on the Cancel button and then again edits the item.
[STSMACOM-812](https://folio-org.atlassian.net/browse/STSMACOM-812)
https://github.com/folio-org/stripes-smart-components/assets/77053927/e0bc2170-b550-47c8-b340-8aae10a21e69

STSMACOM-812: <EditableListForm> - don't show an error after the user clicks on the edit icon.

---

CHANGELOG.md
lib/Notes/NoteViewPage/components/NoteView/NoteView.js
lib/Notes/NoteViewPage/components/NoteView/tests/interactor.js
lib/Notes/NoteViewPage/components/NoteView/tests/note-view-test.js
lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js
package.json
yarn.lock

This approach makes use of the `dompurify` library. It requires less configuration out of the box than the previously [attempted](https://github.com/folio-org/stripes-smart-components/pull/1452) `sanitize-html`

STSMACOM-816 Safely render HTML in Note template

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSortQuery.js
lib/SearchAndSort/tests/SearchAndSortQueryTests/SASQTestHarness.js
lib/SearchAndSort/tests/SearchAndSortQueryTests/SearchAndSortQuery-test.js

There is a bug in `<SearchAndSortQuery>` that resets filter state when user selects a filter value from initial values.
https://github.com/folio-org/stripes-smart-components/assets/19309423/2746e8c0-6223-4307-bd74-899011d6002e
The root cause is incorrect order of operations during component state update and a little bit of state mutation
Prevously we had this bit of code to get next state:
```
nextState.changeType = changeType;
nextState.searchChanged = !isEqual(
nextState.searchFields,
curState.default.searchFields
);
nextState.filterChanged = !isEqual(
nextState.filterFields,
curState.default.filterFields
);
nextState.sortChanged = !isEqual(nextState.sortFields, curState.default.sortFields);
return queryStateReducer(curState, nextState);
```
The issue is that in …

STSMACOM-820 Fix incorrect state calculation in <SearchAndSortQuery>

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/tests/SearchAndSort-test.js

When there is a single search result and the third pane is open, and then the user creates a new record in a different route and when the new record is created the user is redirected to the main page (with the previously opened third pane). The third pane doesn't contain the newly created record, it contains the previously opened one. [video record](https://github.com/folio-org/stripes-smart-components/assets/77053927/5528549c-b886-467d-9262-179dcc033769) 
Root cause: 
The logic for automatically opening the record’s view screen fires even if the URL already contains the record’s view screen route. The logic must only be triggered if there is no open record.
Add a check for a record ID in the URL. If it exists, then prevent the automatic opening of the record. …

STSMACOM-822: Do not trigger logic for auto-opening the record's view screen in `<SearchAndSort>` if URL already contains the record ID.

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
lib/EditableList/EditableListForm.js
lib/EditableList/readme.md
lib/EditableList/tests/EditableList-test.js

For Inventory Classification Browse we need 2 changes in <ControlledVocab>
- add PUT method options override - by default Accept header is “text/plain”, but classification browse configuration doesn’t support it
- ability to hide "+New" button
[STSMACOM-825](https://folio-org.atlassian.net/browse/STSMACOM-825)
https://github.com/folio-org/stripes-connect/pull/229
https://github.com/folio-org/ui-inventory/pull/2432

`<ControlledVocab>` - pass override headers to PUT method, new prop to hide "New" button.

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.css
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/components/ResetButton/ResetButton.js

`<SearchAndSort>` - re-position Advanced search button when search panel does not have enough space.
https://github.com/folio-org/stripes-smart-components/assets/19309423/51e26eaf-7fb4-43ac-822c-420d665c0a60
[STSMACOM-830](https://folio-org.atlassian.net/browse/STSMACOM-830)

STSMACOM-830 - `<SearchAndSort>` - re-position Advanced search button when search panel does not have enough space.

---

yarn.lock

* `undici` < 5.28.3 is vulnerable to CVE-2024-24758, CVE-2024-24758, CVE-2024-30260
* `es5-ext` < 0.10.63 is vulnerable to CVE-2024-30260
* `follow-redirects` <  1.15.6 is vulnerable to CVE-2024-28849
* `webpack-dev-middleware` < 5.3.4 is vulnerable to CVE-2024-29180
* `express` < 4.19.2 is vulnerable to CVE-2024-29041

CVE updates for April 2024

---

CHANGELOG.md
lib/Notes/NoteViewPage/components/NoteView/NoteView.js
lib/Notes/NoteViewPage/components/NoteView/tests/interactor.js
lib/Notes/NoteViewPage/components/NoteView/tests/note-view-test.js
lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js
package.json
yarn.lock

Cherry-picking changes from https://github.com/folio-org/stripes-smart-components/pull/1453
Refs [STSMACOM-816](https://folio-org.atlassian.net/browse/STSMACOM-816)

STSMACOM-816 for CSP #5 - Safely render markup in `<Notes>` components.

---

yarn.lock

`color-string` < 1.5.5 is vulnerable to CVE-2021-29060

CVE-2021-29060 require color-string >= 1.5.5

---

CHANGELOG.md
lib/SearchAndSort/advancedSearchQueryToRows.js
lib/SearchAndSort/tests/advancedSearchQueryToRows-test.js

Another improvement/fix of Advanced Search's algorithm to split a query string into array of rows
This one is to fix an issue where repeated spaces in a query value would be replaced with just one space
This was happening when splitting the string into tokens:
```
const tokens = queryValue.replace(/\s+/g, ' ').split(' ');
```
We really need to get rid of duplicate spaces when splitting the string into tokens (explanation in code comments)
But what we can do is after we've split the string and we know exactly what type each token is (boolean, search option, match option or a query) we can restore those spaces that we've lost in queries
https://github.com/folio-org/stripes-smart-components/assets/19309423/28df7ef1-13c5-4c80-ae1b-97ba62a1bd40 …

STSMACOM-837 improve AdvancedSearch parsing algorithm to keep repeated spaces in queries

---

CHANGELOG.md
lib/utils/useRemoteStorageMappings.js

[STSMACOM-778](https://folio-org.atlassian.net/browse/STSMACOM-778) - useRemoteStorageMappings doesn't validate the presence of interfaces it relies on
When "remote-storage-mappings" is not available, stripes.hasInterface returns undefined which is not being consumed by useQuery enable option as false. Hence it has to be "withRemoteStorage" has to be booleanized.
With this change, ui-inventory will not make calls to remote storage mappings API when this optional interface is not available.

STSMACOM-778 - Supply boolean value to enabled option of useQuery

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/tests/SearchAndSort-test.js

- pass an optional `isCursorAtEnd` property to `SearchField` to be able to have a cursor at the end of the entered search term;
- pass `resetSelectedItem` to `onDismissDetail` to be able to reset the row highlighting in the `onDismissDetail` callback.
[STSMACOM-841](https://folio-org.atlassian.net/browse/STSMACOM-841)

STSMACOM-841: Add an optional `isCursorAtEnd` property for `SearchField`. Pass `resetSelectedItem` to `onDismissDetail`.

---

CHANGELOG.md
lib/Tags/Tags.js

* When the `mutateEntity` prop is defined, and there is an error during adding/removing the tag, the error is not handled correctly. The response is `{ error: { response: { status: XXX } } }`.
* That's why we get **Cannot save tag data to record. Check that you have the required permissions.** error message instead of **This record cannot be saved because it is not the most recent version.**
[STSMACOM-844](https://folio-org.atlassian.net/browse/STSMACOM-844)
https://github.com/user-attachments/assets/8554e7e2-ec06-4bd7-9f6d-b5ef7555f7b6

STSMACOM-844: Add check for the error status when optimistic locking triggered by tags assignment to Instance record

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js

Add `showSortIndicator` prop to `SearchAndSort` to display sort indicator next to the column names.
[STSMACOM-849](https://folio-org.atlassian.net/browse/STSMACOM-849)
https://github.com/folio-org/stripes-components/pull/2333

STSMACOM-849: Add `showSortIndicator` prop to `SearchAndSort` to display sort indicator next to the column names.

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js

Trimming a value to validate the required field in the ControlledVocab component is needed to prevent saving white space.
https://folio-org.atlassian.net/browse/STSMACOM-850

STSMACOM-850: Trim value to validate required field in the ControlledVocab component

---

CHANGELOG.md
lib/SearchAndSort/ConnectedSource/StripesConnectedSource.js
lib/SearchAndSort/tests/StripesConnectedSource-test.js
translations/stripes-smart-components/en.json

Replace the 400 error message with "Search could not be processed for [query]. Please check your query and try again."
[STSMACOM-851](https://folio-org.atlassian.net/browse/STSMACOM-851)

STSMACOM-851: Return a specific 400 error message in `StripesConnectedSource`.

---

CHANGELOG.md
lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js
lib/SearchAndSort/components/DateRangeFilter/tests/DateRangeFilter-test.js

After [STSMACOM-838](https://folio-org.atlassian.net/browse/STSMACOM-838) validateDateRange function now accepts requiredFields argument, which should be passed to all calls
[STSMACOM-853](https://folio-org.atlassian.net/browse/STSMACOM-853)
https://github.com/folio-org/stripes-inventory-components/pull/74

STSMACOM-853 DateRangeFilter - update all calls of `validateDateRange`

---

lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js

After merging https://github.com/folio-org/stripes-smart-components/pull/1512 some of the tests started failing due to infinite calling of the `useEffect` inside the `<DateRangeFilter>` component.
The absence of explicit passing of the `requiredFields` prop causes the application of the default value, which is an array literal. Accordingly, with each render of the component, this array is created anew and the reference to this object in memory changes, which serves as an indicator for calling the `useEffect` callback.

Fix the reinitialization of useEffect dependency when the component re-renders

---

CHANGELOG.md

CHANGELOG is a little out of sync with latests releases, this PR updates it

Update CHANGELOG with latest releases

---

CHANGELOG.md
lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js
lib/SearchAndSort/components/DateRangeFilter/tests/DateRangeFilter-test.js

Fix `<DateRangeFilter>` only shows an error in one of failed inputs
https://github.com/user-attachments/assets/4c2619f6-53fd-4306-8b17-e9d281120678
[STSMACOM-857](https://folio-org.atlassian.net/browse/STSMACOM-857)

STSMACOM-857 Fix `<DateRangeFilter>` only shows an error in one of failed inputs

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js

[STSMACOM-863](https://folio-org.atlassian.net/browse/STSMACOM-863): 
Improve confirmation modal footer for `ControlledVocab` component. Need to improve the correct button alignment and spacing using existing Folio patterns via utilizing ModalFooter for the modal button.
###Current
###Expected

STSMACOM-863: Improve confirmation modal footer for `ControlledVocab` component

---

CHANGELOG.md
lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js

Add the `endDateInputRef` prop to `DateRangeFilter` to access the end date element.
[STSMACOM-859](https://folio-org.atlassian.net/browse/STSMACOM-859)

STSMACOM-859: Add the `endDateInputRef` prop to `DateRangeFilter` to access the end date element.

---

CHANGELOG.md
lib/EditableList/ItemEdit.js
lib/EditableList/ItemView.js

* Remove unnecessary `aria-rowindex` attribute in `<EditableList>` item wrappers in order to avoid accessibility errorss. It is unnecessary to add this attribute in `<EditableList>`, because `<MultiColumnList>` already adds `aria-rowindex` to a wrapper element of each row.
[STSMACOM-871](https://folio-org.atlassian.net/browse/STSMACOM-871)

STSMACOM-871: Remove unnecessary `aria-rowindex` in `ItemView` and `ItemEdit` components

---

CHANGELOG.md
lib/SearchAndSort/SearchAndSort.js
lib/SearchAndSort/tests/SearchAndSort-test.js

Avoid resetting the selected search option when the text in the search box becomes empty.
[STSMACOM-872](https://folio-org.atlassian.net/browse/STSMACOM-872)
https://github.com/user-attachments/assets/fc304968-5a12-4444-bdb8-356b965fd0f0

STSMACOM-872: Reset `qindex` once the search field is empty.

---

CHANGELOG.md
lib/Settings/Settings.js
lib/Settings/tests/Settings-test.js

At first discovery, it's obvious that the settings navigation links for apps like Data Import do not render themselves as active when they are clicked. Many apps work fine, but in the case of these instances, the module itself modifies the query string after the settings view is initially rendered. This throws off the built-in logic that determines the active status of the link (strict equals of the link's `href` against the location) and it's even worse if the pathname is modified... (Service Interaction).
Upon deeper inspection both in the history and the past solution of the issue, there was an issue with the query string not being maintained in the link - so that a second click of the link may throw off logic since initialization for the view wouldn't be re-run, which would mess up …

STSMACOM-873 - Settings link not maintaining active status/style

---

CHANGELOG.md
lib/CustomFields/components/CustomFieldsForm/components/DeleteModal/tests/DeleteModal-test.js
lib/Notes/NoteViewPage/components/NoteView/NoteView.js
lib/Notes/NotesSmartAccordion/tests/notes-smart-accordion-test.js
lib/Notes/components/NotesAccordion/NotesAccordion.js
lib/ProfilePicture/tests/ProfilePicture-test.js
package.json
yarn.lock

It seems that permission's `replaces` property doesn't work as it was expected to, so we have to check for both old and new permission names.
Use `<IfAnyPermission>` and `stripes.hasAnyPerm` to check for Notes assign/unassign perm.
[STSMACOM-875](https://folio-org.atlassian.net/browse/STSMACOM-875)

STSMACOM-875 Use `<IfAnyPermission>` and `stripes.hasAnyPerm` to check for Notes assign/unassign perm.

---

CHANGELOG.md
lib/SearchAndSort/ConnectedSource/StripesConnectedSource.js

`StripesConnectedSource` can accept either `parentResources` or `resources` and one of them can be undefined. Because of this we should use `this.resources` instead, which takes this into account
https://github.com/user-attachments/assets/ec30f55d-c9b2-4643-afd6-ca3d663eb68b
[STSMACOM-879](https://folio-org.atlassian.net/browse/STSMACOM-879)

STSMACOM-879 Use `this.resources` in `StripesConnectedSource` instead of accessing props directly.

---

CHANGELOG.md
lib/Notes/components/NoteForm/components/NoteFields/NoteFields.js

axe previously showed an a11y issue related to checkbox group labels. Latest code doesn't show this issue anymore, but applied the fix anyways.
Re-organized "Display as pop-up" checkbox group markup.
[STSMACOM-882](https://folio-org.atlassian.net/browse/STSMACOM-882)

STSMACOM-882 `<NoteFields>` improve "Display as pop-up" markup and fix label a11y issue.

---

CHANGELOG.md
lib/SearchAndSort/requestUrlLimit.js

Okapi’s URI max length was increased from 4096 to 8192 in [OKAPI-1198](https://folio-org.atlassian.net/browse/OKAPI-1198). This requires a change to the `REQUEST_URL_LIMIT` variable.
[STSMACOM-887](https://folio-org.atlassian.net/browse/STSMACOM-887)

STSMACOM-887: Change the request URL limit for `REQUEST_URL_LIMIT` due to increase to 8192.

---

CHANGELOG.md
lib/EntryManager/EntrySelector.js
lib/EntryManager/EntrySelector.test.js

Avoid an NPE when sorting lists if the requested sort-key is missing by using `id` as the key instead. Should we check for `id`? Eh, maybe, but `<EntryManager>` is a tool for handling entries retrieved from API requests so it seems like a safe assumption.
This bug was introduced in 1a8f5450b566c0cf21626760e2ef40de5e63f8c2.
Refs [STSMACOM-893](https://folio-org.atlassian.net/browse/STSMACOM-893)

STSMACOM-893 EntryManager sort by id if sort-key is absent

---

CHANGELOG.md
package.json
yarn.lock

* Update react-intl
* use stripes-cli to compile translations, eliminating the dependency on `@formatjs/cli`
Refs [STSMACOM-892](https://folio-org.atlassian.net/browse/STSMACOM-892)

STSMACOM-892 update react-intl to v7

---

CHANGELOG.md
lib/Notes/NoteViewPage/components/NoteView/NoteView.js

Replace annotations such as `@withStripes` with a [`_.flow()`](https://lodash.com/docs/4.17.15#flow)-based syntax for better compatibility with esbuild-loader >= 3.1.0.
Refs [STSMACOM-896](https://folio-org.atlassian.net/browse/STSMACOM-896)

STSMACOM-896 apply wrappers with flow()

---

lib/Notes/NoteCreatePage/NoteCreatePage.js
lib/Notes/NoteEditPage/NoteEditPage.js
lib/Notes/NoteViewPage/NoteViewPage.js
lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js

Just like PR #1568, replace annotations that don't play nice with our esbuild-loader setup. Unfortunately, I missed a bunch of annotations in the original PR.
Refs [STSMACOM-896](https://folio-org.atlassian.net/browse/STSMACOM-896)

STSMACOM-896 replace annotations with _.flow

---

CHANGELOG.md
lib/ConfigManager/ConfigManager.js
lib/ConfigManager/readme.md

`ConfigManager` - Add `userId` property to be able to retrieve user's own settings, not just tenant settings from mod-settings. This change is made specifically for https://github.com/folio-org/ui-myprofile/pull/251
[STSMACOM-902](https://folio-org.atlassian.net/browse/STSMACOM-902)

STSMACOM-902: ConfigManager - Add `userId` property to be able to retrieve user's own settings, not just tenant settings from mod-settings.

---

CHANGELOG.md
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js

https://folio-org.atlassian.net/browse/STSMACOM-903
Since the `<EditCustomFieldsRecord>` component includes an `<Accordion>`, it should support passing content as props based on the accordion’s state — `displayWhenClosed` and `displayWhenOpen`.
The prop names are consistent with those used in the `<Accordion>` component.
As per the current business requirement, this accordion might be marked as _hidden_ within the order template. This designation allows the component to be excluded from the rendering of both the PO and POL form and view. (Ref https://folio-org.atlassian.net/browse/UIOR-1394)
https://github.com/user-attachments/assets/d4986439-8008-4701-bf18-9713213e2021

STSMACOM-903 Pass props for rendering aside content for custom fields accordion

---

CHANGELOG.md
lib/Notes/components/NotesAccordion/NotesAccordion.js
lib/Notes/tests/interactors.js

Rename the "New" button to "New note" when creating a note.
[STSMACOM-906](https://folio-org.atlassian.net/browse/STSMACOM-906)

STSMACOM-906: Update button label for creating new notes in `NotesAccordion`.

---

CHANGELOG.md
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
lib/CustomFields/pages/EditCustomFieldsRecord/tests/EditCustomFieldsRecord-test.js
lib/CustomFields/pages/EditCustomFieldsSettings/EditCustomFieldsSettings.js
lib/CustomFields/pages/EditCustomFieldsSettings/tests/EditCustomFieldsSettings-test.js
lib/CustomFields/pages/ViewCustomFieldsRecord/ViewCustomFieldsRecord.js
lib/CustomFields/pages/ViewCustomFieldsRecord/tests/ViewCustomFieldsRecord-test.js
lib/CustomFields/pages/ViewCustomFieldsSettings/ViewCustomFieldsSettings.js
lib/CustomFields/pages/ViewCustomFieldsSettings/tests/ViewCustomFieldsSettings-test.js
lib/CustomFields/readme.md
lib/CustomFields/utils/useSectionTitleFetch.js
tests/network/config.js

Provided a `scope` property, which specifies that the `mod-settings` API should be used, otherwise `mod-configuration` will be used.
[STSMACOM-910](https://folio-org.atlassian.net/browse/STSMACOM-910)

STSMACOM-910: Migrate custom fields from mod-configuration to mod-settings.

---

CHANGELOG.md
lib/ControlledVocab/ControlledVocab.js
lib/ControlledVocab/tests/ControlledVocabErrors-test.js

Note Types settings requires custom error handling of create fails, which is currently not supported.
This PR adds a new `onCreateFail` prop to `<ControlledVocab>` to allow parent components to specify custom error handling.
[STSMACOM-913](https://folio-org.atlassian.net/browse/STSMACOM-913)

STSMACOM-913 `<ControlledVocab>` - added a new `onCreateFail` prop to allow parent components to specify custom error handling.

---

CHANGELOG.md
lib/CustomFields/components/FieldAccordion/FieldAccordion.js
lib/CustomFields/components/FieldAccordion/view-sections/CheckboxSection.js
lib/CustomFields/components/FieldAccordion/view-sections/RadioButtonSetSections.js
lib/CustomFields/components/FieldAccordion/view-sections/SelectDropdownSection.js
lib/CustomFields/components/FieldAccordion/view-sections/TextboxSection.js
lib/CustomFields/components/FieldAccordion/view-sections/shared-values/DisplayInAccordion.js
lib/CustomFields/components/FieldAccordion/view-sections/shared-values/HelpTextValue.js
lib/CustomFields/components/FieldAccordion/view-sections/shared-values/HiddenValue.css
lib/CustomFields/components/FieldAccordion/view-sections/shared-values/HiddenValue.js
lib/CustomFields/components/FieldAccordion/view-sections/shared-values/RequiredValue.js
lib/CustomFields/components/FieldAccordion/view-sections/shared-values/index.js
lib/CustomFields/constants.js
lib/CustomFields/pages/ViewCustomFieldsSettings/ViewCustomFieldsSettings.js
lib/CustomFields/pages/ViewCustomFieldsSettings/tests/ViewCustomFieldsSettings-test.js
lib/CustomFields/readme.md
lib/CustomFields/utils/getDisplayInAccordionOptions.js
lib/CustomFields/utils/index.js
tests/network/config.js
translations/stripes-smart-components/en.json

Settings Custom Fields View:
- added new property `hasDisplayInAccordionField` to show/hide the new `Display in accordion` field, which is designed to store the name/id of the accordion where the custom field will be placed. Currently, BE is done only for the mod-users, mod-orders, or any other module should do some extra work to use this field;
- help text field is now always displayed instead of when value is present;
- changed fields order to `Field label`, `Help text`, `Display in accordion`, `Hidden`, `Required`;
- checkbox doesn't have `Required` field;
- created new `DisplayInAccordion` component for `Display in accordion` field;
- created new `HiddenValue` component;
- added new `displayInAccordionOptions` property, it is a list of options `[{ value, label }]`, `value` is used to …

STSMACOM-914: Settings Custom Fields View - include the `Display in accordion`, `Hidden` fields, and re-order the fields.

---

CHANGELOG.md
lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
lib/CustomFields/pages/EditCustomFieldsRecord/tests/EditCustomFieldsRecord-test.js
lib/CustomFields/readme.md

Improve the handling of custom fields default values in `EditCustomFieldsRecord` component to distinguish between create and edit modes, ensuring proper form behavior:
When a **Multi-select**, **Radio button set**, or **Single select** field exists in the custom field settings:
**Create page**:
* No default option selected in the custom field -> “Save & close” **disabled**. <- **is fixed in this PR**
* Default option selected in the custom field -> “Save & close“ **disabled**.  <- **is fixed in this PR**
**Edit page**: 
* No default option selected in the custom field -> “Save & close“ **disabled**.  <- **is fixed in this PR**
* Default option selected in the custom field & custom field value is populated on existing record -> “Save & close“ **disabled**.
* Default option selected in the …

STSMACOM-922: Improve custom fields default value handling for create vs edit modes
