folio-org/stripes-smart-components

README.md
Follow rename stripes-util-notes to stripes-smart-components
=> FOLIO-854 update readme for rename

CHANGELOG.md, lib/ControlledVocab/ControlledVocab.js, lib/ControlledVocab/index.js, package.json
Fixes the stripes-smart-components part of STSMACOM-6.
=> Add <ControlledVocab>. Fixes the stripes-smart-components part of STSMACOM-6

lib/EntryManager/readme.md
=> adding EntryManager readme

lib/EntryManager/EntryForm.js, lib/EntryManager/EntryManager.js, lib/EntryManager/readme.md, package.json
Implementing @mike's very sensible suggestions on #14: 
* `location` can be obtained using React Router's `withRouter` HOC.
* `history` likewise, I think.
* `stripes` can be taken from the context, as `<IfPermission>` does.
=> simpler API. Fixes STSMACOM-13

lib/EntryManager/EntryForm.js, lib/EntryManager/EntryManager.js
pass along a function to determine whether the delete button ought to be disabled, and the title-text to use for the button if so.
=> handle disabled delete button. Refs UICIRC-22 Scenario 5

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
And some change-logging.
Fixes STRSMCOM-24.
=> <SearchAndSort> modifications to support ui-search

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
=> Remove `search` URL parameter from `<SearchAndSort>`

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
=> `<SearchAndSort>` honours the "initialPath" property

lib/SearchAndSort/SearchAndSort.js
@MikeTaylor This might look odd at first pull until we get the text-color sorted out in the MCL rows (currently undergoing CSS overhaul) - but it fixes the lint issue.
=> Stsmacom 31 react a11y lint

lib/SearchAndSort/SearchAndSort.js
=> Replace all anointed-resource properties on clear

CHANGELOG.md
Definitely worth going through PR cycle for this.
=> Change-logging

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
=> <SearchAndSort> no longer replicates URL state in component state

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
=> Store local changes to search term in component state, and render from that

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
=> Fix regression: reset-search button had stopped working

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js, lib/SearchAndSort/readme.md
=> Support the `<MultiColumnList>` property `columnWidths`

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
=> `<SearchAndSort>` passes `searchableFields` and `onChangeField` through to `<FilterPaneSearch>`

lib/SearchAndSort/SearchAndSort.js
Added callbacks to handle the filter clearing necessary for https://github.com/folio-org/stripes-components/pull/164
=> STCOM-164: Add buttons to clear filters

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
=> Fall back to rendering full record if onSelectRow function returns null

lib/SearchAndSort/SearchAndSort.js
Resolves UICHKOUT-46:
This creates a lifecycle hook `componentWillUnmount` which conditionally runs the prop method `onComponentWillUnmount` if it is present. Depends on other PRs: [ui-checkout](https://github.com/folio-org/ui-checkout/pull/55), [ui-plugin-find-user](https://github.com/folio-org/ui-plugin-find-user/pull/10), [ui-users](https://github.com/folio-org/ui-users/pull/221)
=> Uichkout 46

lib/SearchAndSort/SearchAndSort.js
This (along with a PR in stripes-components) completes [STCOM-164](https://issues.folio.org/browse/STCOM-164) by using the new SearchField component in the SearchAndSort filters pane.
=> STCOM-164: Update SearchAndSort to use new SearchField component

lib/EntryManager/EntryForm.js, lib/EntryManager/EntryManager.js, lib/SearchAndSort/SearchAndSort.js
- Added spinner on loading when searching
- Added marginBottom0 on a couple of buttons
=> Updates adding spinner to search field etc.

lib/EntryManager/EntryForm.js, lib/EntryManager/EntryManager.js, lib/SearchAndSort/SearchAndSort.js
We are re-adding the default margin on buttons. This is preparation for that.
=> Added marginBottom0 prop to buttons in a few places

CHANGELOG.md, lib/ControlledVocab/ControlledVocab.js, lib/Notes/Notes.js, lib/SearchAndSort/SearchAndSort.js
[Stsmacom-56](https://issues.folio.org/browse/STSMACOM-56)
=> Stsmacom 56 lint

lib/SearchAndSort/SearchAndSort.js
Only show the "Reset all" button when there are filters or search parameters that should be reset.
=> STCOM-164: Conditionally render SAS Reset all button

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
=> Support `searchableIndexesPlaceholder` property

CHANGELOG.md, lib/ControlledVocab/ControlledVocab.js, package.json
Refs [STSMACOM-56](https://issues.folio.org/browse/STSMACOM-56).
=> Lint. Refs STSMACOM-56

lib/SearchAndSort/SearchAndSort.css, lib/SearchAndSort/SearchAndSort.js
Removed placeholder from search field since it's already inside an Accordion with the title "Search" and adjusted left/right spacing to align with other elements in the filter pane.
=> Updated SearchField in filter pane

lib/SearchAndSort/SearchAndSort.js, package.json
=> Adding AppIcon to SearchAndSort results Pane -> PaneHeader

CHANGELOG.md, lib/ConfigManager/ConfigForm.js, package.json
Refs [UITEST-20](https://issues.folio.org/browse/UITEST-20)
=> provide HTML-id for save button for easy access in tests. Refs UITEST-20

CHANGELOG.md, lib/ConfigManager/ConfigForm.js
[https://issues.folio.org/browse/UIORG-53](https://issues.folio.org/browse/UIORG-53)
=> Do not destroy form on unmount. Refs UIORG-53.

CHANGELOG.md, lib/SearchAndSort/ResourcesAnalyzer.js, lib/SearchAndSort/SearchAndSort.js
=> Change ResourcesAnalyzer API so that constructor takes top-level props

CHANGELOG.md, lib/SearchAndSort/ResourcesAnalyzer.js, lib/SearchAndSort/SearchAndSort.js
=> Switch ResourcesAnalyzer API to use a factory method

CHANGELOG.md, lib/SearchAndSort/ResourcesAnalyzer.js
=> Extend ResourcesAnalyzer to work for GraphQL-provided resources. Mutations not yet supported

lib/ConfigManager/ConfigManager.js, lib/ConfigManager/readme.md
[https://issues.folio.org/browse/STSMACOM-71](https://issues.folio.org/browse/STSMACOM-71)
=> Add onBeforeSave to ConfigManager. Fixes STSMACOM-71

.gitignore, CHANGELOG.md, index.js, lib/ProxyManager/ProxyForm.css, lib/ProxyManager/ProxyForm.js, lib/ProxyManager/ProxyManager.js, lib/ProxyManager/ProxyModal.js, lib/ProxyManager/index.js, lib/ProxyManager/proxyUtil.js
[https://issues.folio.org/browse/STSMACOM-58](https://issues.folio.org/browse/STSMACOM-58)
=> Extract proxy modal into ProxyManager. Fixes STSMACOM-58.

lib/UserName/UserName.js
Added handling for users who only have the mandatory lastName set.
=> UserName: Removed comma when firstName doesn't exist

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js, package.json
Fixes [STSMACOM-75](https://issues.folio.org/browse/STSMACOM-75)
=> guarantee stripes object is available to new-record components. Fixes STSMACOM-75

lib/EntryManager/EntryForm.js, lib/EntryManager/EntryManager.js
Update EntryManager to use translations instead of hardcoded strings.
=> STSMACOM-76

lib/ProxyManager/ProxyForm.js, lib/ProxyManager/ProxyManager.js, lib/ProxyManager/proxyUtil.js
https://issues.folio.org/browse/UICHKOUT-52
=> Fix proxy/sponsor expiration status. Refs UICHKOUT-52.

lib/ControlledVocab/ControlledVocab.js, translations/en.json
Added translations for ControlledVocab using the new `<SafeHTMLMessage>` component
=> ControlledVocab i18n

CHANGELOG.md, lib/LocationLookup/LocationForm.js, lib/LocationLookup/LocationLookup.js, lib/LocationLookup/LocationModal.js, lib/LocationLookup/index.js, lib/LocationLookup/readme.md, package.json, translations/en.json
https://issues.folio.org/browse/STSMACOM-79
=> Add Location Lookup Pop-up. Fixes STSMACOM-79.

CHANGELOG.md, lib/LocationSelection/LocationInput.js, lib/LocationSelection/LocationSelection.js, lib/LocationSelection/index.js, lib/LocationSelection/readme.md, package.json, translations/en.json
https://issues.folio.org/browse/STSMACOM-82
=> Introduce a new LocationSelection component. Fixes STSMACOM-82.

lib/LocationSelection/LocationInput.js, lib/LocationSelection/LocationSelection.js, lib/LocationSelection/readme.md, lib/LocationSelection/util.js
https://issues.folio.org/browse/STSMACOM-82
=> Cleanup. Part of STSMACOM-82

lib/ControlledVocab/ControlledVocab.js, translations/en.json
One more translation needed here. Found while examining UIU-469.
=> UIU-469 ControlledVocab: Added translation for updated-by column

CHANGELOG.md, lib/ViewMetaData/ViewMetaData.js, lib/ViewMetaData/index.js
https://issues.folio.org/browse/STSMACOM-84
=> Move ViewMetaData to stripes-smart-components. Fixes STSMACOM-84.

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js, lib/SearchAndSort/components/NoResultsMessage/NoResultsMessage.js
=> Enable correct error-handling when using GraphQL

lib/SearchAndSort/SearchAndSort.js
See STCOM-257. At present, this prop is ignored, but it will give the
new code in MCL something to work with.
=> Pass new totalCount prop into MCL

lib/LocationLookup/LocationForm.js
https://issues.folio.org/browse/STSMACOM-79
=> Fix location selection. Part of STSMACOM-79

CHANGELOG.md, lib/SearchAndSort/ResourcesAnalyzer.js, lib/SearchAndSort/SearchAndSort.js
=> Move the stripes-connect pagination code into the ResourcesAnalyzer

CHANGELOG.md, lib/SearchAndSort/ConnectedSource/ApolloConnectedSource.js, lib/SearchAndSort/ConnectedSource/ConnectedSource.js, lib/SearchAndSort/ConnectedSource/StripesConnectedSource.js, lib/SearchAndSort/ConnectedSource/index.js, lib/SearchAndSort/SearchAndSort.js
=> Break ConnectedSource into multiple source files

CHANGELOG.md, lib/ProxyManager/ProxyForm.css, lib/ProxyManager/ProxyForm.js, lib/ProxyManager/ProxyManager.js, lib/ProxyManager/proxyUtil.js, translations/en.json
https://issues.folio.org/browse/STSMACOM-101
=> Add extra validation for users not allowed to request. Fixes STSMACOM-101

CHANGELOG.md, lib/ProxyManager/proxyUtil.js
Fixes https://issues.folio.org/browse/STSMACOM-105
=>  Update ProxyManager to use new proxy structure. Fixes STSMACOM-105

CHANGELOG.md, lib/EntryManager/EntryForm.js, lib/SearchAndSort/SearchAndSort.js
Refs [STCOM-277](https://issues.folio.org/browse/STCOM-277)
=> update paths for relocated components

lib/ChangeDueDateDialog/ChangeDueDate.js, lib/ChangeDueDateDialog/ChangeDueDateDialog.js, lib/ConfigManager/ConfigManager.js, lib/ControlledVocab/ControlledVocab.js, lib/EntryManager/EntryForm.js, lib/EntryManager/EntryManager.js, lib/LocationLookup/LocationForm.js, lib/LocationLookup/LocationLookup.js, lib/LocationLookup/LocationModal.js, lib/LocationSelection/LocationInput.js, lib/LocationSelection/LocationSelection.js, lib/Notes/NoteCreator.js, lib/Notes/NoteRenderer.js, lib/Notes/Notes.js, lib/ProxyManager/ProxyForm.js, lib/ProxyManager/ProxyManager.js, lib/SearchAndSort/SearchAndSort.js, lib/UserName/UserName.js
This is the output of running the sort-comp codemod (with the changes in reactjs/react-codemod/pull/208).
Some extra noise from alpha-sorting the components but I'll take it.
=> sort-comp codemod

lib/ChangeDueDateDialog/ChangeDueDate.js
=> UIU-497 CDD: Made datepicker value default to empty

CHANGELOG.md, lib/LocationLookup/LocationModal.js
https://issues.folio.org/browse/STSMACOM-109
=> Turn off enforceFocus on LocationModal. Fixes STSMACOM-109.

CHANGELOG.md, lib/EntryManager/EntryManager.js
https://issues.folio.org/browse/STSMACOM-110
=> Add extra check to EntryManager to recognize add/edit mode. Fixes STSMACOM-110.

CHANGELOG.md, lib/LocationLookup/LocationForm.js, lib/LocationSelection/LocationInput.js, package.json
https://issues.folio.org/browse/UIIN-198
=> Allow for choosing empty value in LocationSelection and LocationLookup. Refs UIIN-198.

CHANGELOG.md, lib/EntryManager/EntryManager.js, lib/EntryManager/EntryWrapper.js, lib/SearchAndSort/SearchAndSort.js
https://issues.folio.org/browse/STCOR-231
=> Refactor EntryManager to support anointed resource. Fixes STCOR-231.

CHANGELOG.md, lib/LocationSelection/LocationInput.js, package.json
"You know something? You know something, if you had told us one year ago
we were going to get 10 records back from Okapi we would've given
anything for that. And you know something, you know something? Not only
are we getting 10 records back from Okapi, Tom Harkin, we're getting 11
records back, 12 records back, 13 records back! We're going to get 20,
30, 40, 50 records back! And then we're going to Washington DC to get
100 records and take back the White House! Hoooeeaaaggggherrrrrrrah!"
-- Folio Fan and former VT Governor Howard Dean
=> retrieve more locations

lib/SearchAndSort/SearchAndSort.js, lib/Tags/Tag.js, lib/Tags/Tags.css, lib/Tags/Tags.js, lib/Tags/TagsForm.js, lib/Tags/TagsList.js, lib/Tags/index.js, lib/Tags/withTags.js, translations/stripes-smart-components/en.json
https://issues.folio.org/browse/STSMACOM-113
=> Add support for tags on individual records. Part of STSMACOM-113.

CHANGELOG.md, package.json
Update react-intl-safe-html to latest ^1.0.2 patch release to resolve STRIPES-545
=> STRIPES-545 Update react-intl-safe-html version

lib/EntryManager/EntryWrapper.js
Add `id` to add button for testing
=> Introduce baseId to entry wrapper. Part of UITEST-46

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js, lib/SearchAndSort/components/NoResultsMessage/NoResultsMessage.js, lib/SearchAndSort/readme.md, package.json
Fixes STSMACOM-116.
Available from v1.4.29.
=> New optional notLoadedMessage prop for <SearchAndSort>

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js, package.json
https://issues.folio.org/browse/STSMACOM-119
=> Fix initial query string to keep searchField updated. Fixes STSMACOM-119

CHANGELOG.md, lib/PasswordStrength/PasswordStrength.js, lib/PasswordStrength/index.js, lib/PasswordStrength/readme.md, package.json, translations/stripes-smart-components/en.json
Added Password Strength component with readme.md
Added translations for EN
Added password strength plugin to package.json
Changelog updated correspondingly
=> UIU-516 Spike: Select a Password Strength Meter

lib/LocationLookup/LocationForm.js, package.json
https://issues.folio.org/browse/UIIN-270
=> Fix location lookup. Part of UIIN-270

lib/LocationLookup/LocationForm.js, lib/LocationLookup/LocationModal.js
https://issues.folio.org/browse/UIORG-103
=> Fix disable condition for location lookup. Part of UIORG-103

CHANGELOG.md, lib/Tags/Tags.js, lib/Tags/TagsForm.js, package.json
https://issues.folio.org/browse/STSMACOM-113
=> Refactor to MultiSelection component. Part of STSMACOM-113

lib/Tags/Tags.js, lib/Tags/TagsForm.js
https://issues.folio.org/browse/STSMACOM-113
=> More fixes to tags. Part of STSMACOM-113

CHANGELOG.md, lib/Tags/Tags.js, lib/Tags/TagsForm.js, package.json, translations/stripes-smart-components/en.json
https://issues.folio.org/browse/STSMACOM-113
=> Fix sorting of filtered items. Introduce Callout. Part of STSMACOM-113.

translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20180913T150458

index.js
Exports everything from `index.js`.
=> Fill in export gaps

CHANGELOG.md, lib/Tags/TagsForm.js, package.json
https://issues.folio.org/browse/STSMACOM-123
=> Fix tags autosuggest subsort. Fixes STSMACOM-123.

CHANGELOG.md, package.json
https://issues.folio.org/browse/STRIPES-557
=> Move stripes-core to peerDependencies. Part of STRIPES-557

lib/LocationLookup/LocationForm.js, lib/LocationLookup/LocationLookup.js, lib/LocationSelection/LocationSelection.js, lib/SearchAndSort/SearchAndSort.js, lib/Settings/Settings.js, lib/Tags/Tag.js
Import from the root instead of digging into the directory structure. Follow-up to https://github.com/folio-org/stripes-smart-components/pull/271
=> Simplify stripes-core imports

index.js
Related to https://github.com/folio-org/ui-users/pull/518
=> Export AddressEditList

translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20180924T185314

package.json
Follow-up to https://github.com/folio-org/eslint-config-stripes/pull/39
=> Remove webpack dependency

CHANGELOG.md, package.json
https://issues.folio.org/browse/STRIPES-561
=> STRIPES-561 Release v1.9.0

index.js
Umbrella PR for catching additional exports/updates for using stripes v1.0.0
* LocationSelection
=> Export updates for stripes v1.0.0 integration.

lib/Settings/Settings.css
Corresponding css variable casing with recent update to stripes-components...
=> Switch media query to kebab-case

CHANGELOG.md, package.json
Changes:
* Export `LocationSelection` and `makeQueryFunction`
* Move `craftLayerURL()` here (into search and sort)
* Update CSS variables to use kebab-case.
=> Release v1.10.0

CHANGELOG.md, lib/EntryManager/EntryWrapper.js
https://issues.folio.org/browse/STSMACOM-134
=> Add clone option to EntryManager. Fixes STSMACOM-134.

lib/SearchAndSort/SearchAndSort.js
Adds full-width "Search" button, requires submit action to start searching, and removes dismiss icon from Search & Filter pane.
Fixes https://issues.folio.org/browse/STCOM-354 and https://issues.folio.org/browse/STSMACOM-132
=> STCOM-354 Improve SearchAndSort behavior

CHANGELOG.md, lib/EntryManager/EntryWrapper.js, lib/EntryManager/readme.md
https://issues.folio.org/browse/STSMACOM-136
=> Add ability to pass custom add menu component to EntryManager. Fixes STSMACOM-136

CHANGELOG.md, lib/Tags/withTags.js
https://issues.folio.org/browse/UITAG-8
=> Enable tags by default. Part of (UITAG-8

CHANGELOG.md, lib/EntryManager/EntryWrapper.js
https://issues.folio.org/browse/STSMACOM-140
=> Show details view of the newly created record after duplication. Fixes STSMACOM-140

CHANGELOG.md, lib/EntryManager/EntryWrapper.js
https://issues.folio.org/browse/STSMACOM-141
=> Open details screen after new record is created. Fixes STSMACOM-141.

lib/SearchAndSort/components/ResetButton/ResetButton.js
This adds proper spacing between the label and icon.
=> Moved label inside of <Icon> in <ResetButton>

lib/EntryManager/EntryForm.js
Make the id attributes for save/delete buttons more consistent with
those used elsewhere.
=> use more consistent id attributes

translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20181110T181812

translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20181112T160917

lib/ControlledVocab/ControlledVocab.js, lib/EditableList/ItemEdit.js, lib/EditableList/ItemView.js
We don't have much infrastructure to hang our tests off. These
additional attributes provide a few more hooks that make it easier to
write more specfic tests.
=> provide additional attributes useful in tests

lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js, lib/AddressFieldGroup/AddressList/AddressList.js, lib/ChangeDueDateDialog/ChangeDueDate.js, lib/ChangeDueDateDialog/ChangeDueDateDialog.js, lib/ChangeDueDateDialog/ChangeDueDateSuccess.js, lib/EditableList/EditableListForm.js, lib/Notes/NoteRenderer.js, lib/SearchAndSort/components/NoResultsMessage/NoResultsMessage.js, lib/SearchAndSort/components/ResetButton/ResetButton.js, lib/Settings/Settings.js, lib/Tags/Tag.js, package.json, yarn.lock
See https://github.com/folio-org/stripes-components/pull/743
=> Update deprecated icon names

CHANGELOG.md, lib/ProxyManager/ProxyManager.js, package.json
This PR fixes a fetching / data bug described in STSMACOM-154.
https://issues.folio.org/browse/STSMACOM-154
=>  Refactor proxy fetching in ProxyManager. Fixes STSMACOM-154

index.js
Related PR: https://github.com/folio-org/ui-users/pull/622;
Override modal window uses DueDatePicker component.
=> UIU-683: Add DueDatePicker export

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
The search term will be only updated after the search is executed.
https://issues.folio.org/browse/STSMACOM-155
=> Fix no results found message. Fixes STSMACOM-155

lib/SearchAndSort/SearchAndSort.js
**Ticket:** https://issues.folio.org/browse/STCOM-405
=> STCOM-405: Completely removed actionMenuItems-prop

lib/Settings/Settings.css, lib/Settings/Settings.js, package.json, yarn.lock
Uses new `<PaneBackLink>` for responsive behavior in settings Paneset: https://github.com/folio-org/stripes-components/pull/772
Requires `stripes-components` `v5.0.0`.
=> Use PaneBackLink in Settings

CHANGELOG.md, package.json, yarn.lock
* Require `stripes-connect` `4.x` and `stripes-form` `2.x`
=> Release v2.0.1

lib/EntryManager/EntrySelector.js
Add ability to remove item from view mode
https://issues.folio.org/browse/UICIRC-109
=> UICIRC-109 - added confirmation modal for removing item in view mode

translations/stripes-smart-components/it_IT.json
=> Update translation strings as of 20190213T024543

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190225T222207

CHANGELOG.md, lib/ConfigManager/ConfigManager.js, translations/stripes-smart-components/en.json
Refs [STSMACOM-175](https://issues.folio.org/browse/STSMACOM-175)
=> extract static strings for translation

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190227T140407

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190312T123958

index.js, lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js, lib/AddressFieldGroup/readme.md, translations/stripes-smart-components/en.json
With a few additional modifications, this could be a handy component for entry of any address in the system.
=> Export `<EmbeddedAddressForm>`

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190327T174151

lib/SearchAndSort/SearchAndSortQuery.js
Initializing from a url with filters etc only includes search terms.
Change `cDM` to use `onSubmitAll` method rather than `onSubmitSearch`
=> use onSubmitAll on mount rather than onSubmitSearch

lib/Notes/NotesAccordion/NotesAccordion.css, lib/Notes/NotesAccordion/NotesAccordion.js, lib/Notes/NotesAccordion/components/NotesList/NotesList.js, lib/Notes/NotesAccordion/components/NotesList/index.js, lib/Notes/NotesAccordion/components/index.js, package.json, translations/stripes-smart-components/en.json
https://issues.folio.org/browse/STSMACOM-185
Create basic accordion for notes with MCL table,  "Add" and New"  buttons, which will be used to manage work with notes inside the UI module where notes used. It's the beginning part of the whole component. Next step is to add embed modal with possibility to search and attach notes.
- Create Accordion
- Create NotesList component
- Add translations
- Add modal component for attaching notes
=> STSMACOM-185: Add notes accordion

index.js, lib/SearchAndSort/components/DateRangeFilter/DateRange.css, lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js, lib/SearchAndSort/components/DateRangeFilter/date-types.js, lib/SearchAndSort/components/DateRangeFilter/date-validations.js, lib/SearchAndSort/components/DateRangeFilter/index.js, lib/SearchAndSort/components/DateRangeFilter/tests/DateRangeFilter-test.js, lib/SearchAndSort/components/DateRangeFilter/tests/interactor.js, translations/stripes-smart-components/en.json
This is a component for filtering records by a date range.
It has almost the same interface as CheckboxFilter and MultiSelectionFilter have. Unlike other filter components, this one does not require a `dataOptions` prop to be provided since the dates are manually entered by users and cannot be predefined. 
Another difference is that a `makeFilterString` function should be provided. When a user enters a date range, this function receives entered start and end dates and returns a string which will be used in the request parameters. Probably it can be given a better name.
Here is an example of using the component (inspired by ui-search):
```javascript
export default class Filters extends React.Component {
static propTypes = {
activeFilters: PropTypes.objectOf(PropTypes.array),
onChange: …
```
=> STCOM-451: Create date range filter

lib/LocationLookup/LocationForm.js, lib/LocationLookup/LocationLookup.js, lib/LocationLookup/LocationModal.js, lib/LocationLookup/tests/LocationLookup-test.js, lib/LocationLookup/tests/interactor.js
An option's value must be a string, not a `<FormattedMessage>`.
=> pass strings, not objects, to Select elements

translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20190501T184815

index.js, lib/Notes/NotesAccordion/NotesAccordion.css, lib/Notes/NotesAccordion/NotesAccordion.js, lib/Notes/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.css, lib/Notes/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js, lib/Notes/NotesAccordion/components/NotesAssigningModal/constants.js, lib/Notes/NotesAccordion/components/NotesAssigningModal/index.js, lib/Notes/NotesAccordion/components/NotesList/NotesList.js, lib/Notes/NotesAccordion/components/index.js, lib/Notes/NotesAccordion/constants.js, lib/Notes/NotesAccordion/index.js, lib/Notes/index.js, translations/stripes-smart-components/en.json
https://issues.folio.org/browse/STSMACOM-196
- Add a modal for assigning/unassigning notes.
- Create notes popup component
- Add translations
=> STSMACOM-196: Add notes pop-up

lib/Notes/NotesAccordion/NotesAccordion.js, lib/Notes/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js, lib/Notes/NotesAccordion/components/NotesList/NotesList.js, lib/Notes/NotesAccordion/constants.js, lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js, lib/Notes/NotesSmartAccordion/index.js, lib/Notes/NotesSmartAccordion/readme.md, lib/Notes/NotesSmartAccordion/utils.js, lib/Notes/constants.js, lib/Notes/index.js
https://issues.folio.org/browse/STSMACOM-201
This is a connected Notes Accordion component with binding to `mod-notes`. It's responsible for 
displaying assigned notes, assigning/unassigning notes to an entity(e.g. package in eholdings).
The component's API looks like:
```
<NotesSmartAccordion
domainName="eholdings"
entityName="A Biographical Dictionary of Later Han"
entityType="package"
entityId="350-1207861"
pathToNoteCreate="/eholdings/notes/new"
pathToNoteDetails="/eholdings/notes"
/>
```
=> STSMACOM-201: Add notes smart accordion

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190517T183537

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190528T121921

index.js, lib/Notes/ReferredRecord/ReferredRecord.css, lib/Notes/index.js
In this PR I removed global interactor import and also made note-related imports consistent with other imports
=> STSMACOM-209: fix notes imports

lib/ChangeDueDateDialog/ChangeDueDate.js, lib/ChangeDueDateDialog/ChangeDueDateDialog.js, lib/ChangeDueDateDialog/LoanList.js
In this PR, I Object.freezed all manifests for consistency
=> Freeze all manifests

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20190529T122422

lib/Notes/NoteEditPage/NoteEditPage.js, lib/Notes/NoteForm/NoteForm.js, lib/Notes/NoteForm/NoteView.js, lib/Notes/NoteForm/noteShapes.js, lib/Notes/NoteViewPage/NoteViewPage.js
This PR fixes referrer data on the note-view page in case when we navigate directly to the note and not referrer record data is present
=> Notes: Fixed referrer data and it's shape

lib/ChangeDueDateDialog/ChangeDueDateDialog.js
**Ticket:** https://issues.folio.org/browse/STSMACOM-152
=> Added 'user' in the propTypes for ChangeDueDateDialog

translations/stripes-smart-components/en_US.json
=> Update translation strings as of 20190606T155546

lib/Notes/NoteCreatePage/NoteCreatePage.js, lib/Notes/NoteEditPage/NoteEditPage.js, lib/Notes/NoteViewPage/NoteViewPage.js, lib/Notes/NoteViewPage/components/NoteView/NoteView.js, lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js, lib/Notes/components/NotesAccordion/NotesAccordion.js
In this PR,  I apply notes permissions, defined in [this PR](https://github.com/folio-org/ui-notes/pull/19).
* Notes - get individual note from storage
* Notes - create note
* Notes - modify note
* Notes - delete note
* Note links - update note links
**Related stories:**
[UINOTES-23](https://issues.folio.org/browse/UINOTES-24), [UINOTES-23](https://issues.folio.org/browse/UINOTES-24), [UINOTES-25](https://issues.folio.org/browse/UINOTES-25), [UINOTES-26](https://issues.folio.org/browse/UINOTES-26), [UINOTES-27](https://issues.folio.org/browse/UINOTES-27)
=> Apply notes permissions

lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js, lib/Notes/NotesSmartAccordion/utils.js, lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js, lib/Notes/components/NotesAccordion/components/NotesAssigningModal/constants.js, lib/Notes/constants.js
Replace old notes endpoint for new one(note-links). It gives a possibility to do sort by note assigning status.
=> Apply note-links endpoint for doing sort by status

lib/ControlledVocab/ControlledVocab.js
No functional changes, just some tidying up.
=> ESLint controlled vocab

lib/Notes/NoteViewPage/NoteViewPage.js, lib/Notes/NoteViewPage/components/NoteView/NoteView.js, lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js, lib/Notes/components/ReferredRecord/ReferredRecord.js
In this PR, I added some element attributes to be able to interact with the page in tests.
=> UIEH-717: prepare Notes feature for testing

lib/Notes/components/AssignmentsList/AssignmentsList.css, lib/Notes/components/AssignmentsList/AssignmentsList.js
Per https://issues.folio.org/browse/STSMACOM-221, we want to fix the style so the list items do not appear as links.
=> STSMACOM-221: Update color of text in links

lib/Notes/NoteViewPage/NoteViewPage.js, translations/stripes-smart-components/en.json
Per https://issues.folio.org/browse/STSMACOM-219 and https://issues.folio.org/browse/STSMACOM-220, we are supposed to bold note title and assignment status.
=> STSMACOM-219 & STSMACOM-220: Bold note title

translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190625T144718

translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20190627T152539

lib/AddressFieldGroup/AddressEdit/AddressEdit.js, lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js, lib/AddressFieldGroup/tests/AddressEdit-test.js, lib/AddressFieldGroup/tests/interactor.js, translations/stripes-smart-components/en.json, translations/stripes-smart-components/en_US.json
The AddressFieldGroup component contains hard-coded strings.
=> STSMACOM-170: Add translations.

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190709T154346

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190711T172340

translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190718T220243

lib/SearchAndSort/SearchAndSort.js
The previous attempt to fix this (#585) broke the back button so trying another approach here to address  STSMACOM-232.
=> Another take on STSMACOM-232

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
https://issues.folio.org/browse/STCOM-549
=> Reset results when search field is cleared out manually. Fixes STCOM-549

translations/stripes-smart-components/ar.json
=> Update translation strings as of 20190807T131714

lib/Notes/NoteViewPage/NoteViewPage.js, translations/stripes-smart-components/en.json
https://issues.folio.org/browse/STSMACOM-240
=> STSMACOM-240: Delete resources list from note delete modal

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20190815T130307

translations/stripes-smart-components/en.json
Pluralize translation in note delete modal
=> STSMACOM-241: Add pluralize translation

CHANGELOG.md, lib/ControlledVocab/tests/ControlledVocab-test.js, lib/ControlledVocab/tests/interactor.js, lib/EditableList/EditableListForm.js
"New" button should be disabled for adding a new row.
**Screen Shot**
=> STCOM-539: Disable New button when editing row

lib/SearchAndSort/SearchAndSortQuery.js, lib/SearchAndSort/SearchAndSortQuery.md
To be able disable sorting for columns
https://github.com/folio-org/stripes-smart-components/pull/538
=> UIOR-292 port fix from SearchAndSort to S&SQuery

lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js
> react-dom.development.js:506 Warning: Received `false` for a non-boolean attribute `error`.
> 
> If you want to write it to the DOM, pass a string instead: error="false" or error={value.toString()}.
> 
> If you used to conditionally omit it with error={condition && value}, pass error={condition ? value : undefined} instead.
>     in input (created by TextField)
>     in div (created by TextField)
>     in div (created by TextField)
>     in TextField (created by ForwardRef(FormField(TextField)))
>     in ForwardRef(FormField(TextField)) (created by DateRangeFilter)
>     in DateRangeFilter (created by O)
>     in div (created by Accordion)
>     in section (created by Accordion)
>     in Accordion (created by Context.Consumer)
>     in WrappedAccordion (created by O)
>     in O (created …
=> remove warning from the console

lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js, lib/Notes/components/NotesAccordion/NotesAccordion.js, lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js, translations/stripes-smart-components/en.json
https://issues.folio.org/browse/STSMACOM-252
Remove "Updated by" column and add "Type" column to a list of the notes. Reduce date column width.
Before
After
=> STSMACOM-252: Add note type column to note list accordion

translations/stripes-smart-components/zh_CN.json
=> Update translation strings as of 20191022T162142

lib/Tags/TagsForm.js, translations/stripes-smart-components/en.json
https://issues.folio.org/browse/STSMACOM-257
Assuming we want to continue supporting regex searches for this, we should ensure we don't throw up on invalid regex expressions. I tried to balance showing enough info but not _too_ much here.
=> STSMACOM-257 TagsForm: Fixed crash from invalid regex

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20191023T131908

lib/Notes/components/NoteForm/NoteForm.js, lib/Notes/components/NoteForm/components/NoteFields/NoteFields.js
[UINOTES-59](https://issues.folio.org/browse/UINOTES-59)
=> UINOTES-59: display note types in alphabetical order

lib/SearchAndSort/tests/record-count-test.js
It seems like this setup fixes the broken tests.
=> Handle flaky tests regarding S&S

CHANGELOG.md, lib/ChangeDueDateDialog/ChangeDueDateDialog.js
Add ellipsis in the change due date modal while loans are loading. [Story](https://issues.folio.org/browse/UIU-1379).
**Demo**
*Before*
*After*
=> UIU-1379: Add ellipsis in the change due date modal

lib/AddressFieldGroup/AddressEdit/AddressEditList.js, lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js
This PR is needed for interaction with address buttons during testing of request preferences section in ui-users https://github.com/folio-org/ui-users/pull/1067.
=> UIU-1328: Add data test attrs for add and delete address buttons

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/it_IT.json
=> Update translation strings as of 20191127T181804

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20191202T021928

translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json
=> Update translation strings as of 20191204T162855

translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/fr_FR.json
=> Update translation strings as of 20191209T142332

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.js
https://issues.folio.org/browse/STSMACOM-271
=> STSMACOM-271: Keep search term around after browser refresh

lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js
https://issues.folio.org/browse/STSMACOM-272
##Purpose
Increase limit of the notes to be fetched from 20 to 100000
=> STSMACOM-272: Increase limit for fetching notes

translations/stripes-smart-components/fr_FR.json
=> Update translation strings as of 20200117T173544

translations/stripes-smart-components/it_IT.json
=> Update translation strings as of 20200127T144839

lib/Tags/TagsForm.js
https://issues.folio.org/browse/STCOM-579
To prevent creation of empty tags I think it's a good idea to trim input value before POST
=> STCOM-579 trim tag value so no empty tags and extra spaces

lib/ControlledVocab/ControlledVocab.js
https://issues.folio.org/browse/UITEN-71
=> UITEN-71 Tenant / Addresses: Last updated by - Username not displayed

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200220T141728

CHANGELOG.md, lib/ChangeDueDateDialog/ChangeDueDate.js, lib/ChangeDueDateDialog/ChangeDueDateDialog.js, translations/stripes-smart-components/en.json
See https://issues.folio.org/browse/UIU-1207
=> Modify ChangeDueDate to handle 'declared lost' items

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200224T151433

lib/Notes/NoteViewPage/components/NoteView/NoteView.js
Due to the changes of Action dropdown in this PR https://github.com/folio-org/stripes-components/pull/1112 the edit button on notes view page should be moved to actions dropdown
=> STSMACOM-313: View Note Record: Remove the Edit button

lib/LocationLookup/LocationLookup.js
To align with mockups in ui-receiving https://issues.folio.org/browse/UIREC-53 we need to be able to disable bottom margin for Location Lookup button
https://issues.folio.org/secure/attachment/24840/2-receive-multiples.png
=> add no bottom margin prop

lib/CustomFields/components/FieldAccordion/FieldAccordion.js, lib/CustomFields/components/FieldAccordion/view-sections/TextboxSection.js, lib/CustomFields/pages/EditCustomFieldsSettings/EditCustomFieldsSettings.js, package.json
- Improve code formatting in TextboxSection component
=> STSMACOM-301: Create an Input Type = Text area (Code formatting)

lib/CustomFields/components/FieldAccordion/FieldAccordion.js, lib/CustomFields/components/FieldAccordion/edit-fields/CheckboxFields.js, lib/CustomFields/components/FieldAccordion/edit-fields/TextboxFields.js, lib/CustomFields/components/FieldAccordion/edit-fields/index.js, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/HelpTextField.js, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/HiddenField.js, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/NameField.js, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/RequiredField.js, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/index.js, lib/CustomFields/constants.js, lib/EditableList/EditableListForm.js, translations/stripes-smart-components/en.json
- add a possibility to create custom fields with type Checkbox
https://issues.folio.org/browse/STSMACOM-314
=> STSMACOM-314: Create an Input Type = Checkbox

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200309T000645

translations/stripes-smart-components/ru.json
=> Update translation strings as of 20200314T132532

translations/stripes-smart-components/fr_FR.json
=> Update translation strings as of 20200316T134017

package.json
I botched PR #739 and updated the stripes stuff below this package but
didn't actually update this package's version number. WHOOPS.
=> actually bump package minor to v3.1.0

lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js, lib/CustomFields/pages/ViewCustomFieldsRecord/ViewCustomFieldsRecord.js
Fix bug with wrong displaying rows where some of the fields is hidden
=> UIU-1279: fix bug with hidden fields

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/fr_FR.json
=> Update translation strings as of 20200323T195201

translations/stripes-smart-components/ur.json
=> Update translation strings as of 20200406T162815

lib/ConfigManager/ConfigForm.js, lib/ConfigManager/ConfigManager.css
purpose: according to style guide save action should be placed in the footer
https://issues.folio.org/browse/UITEN-85
=> UITEN-85 move save action to the footer

lib/EntryManager/EntrySelector.js
https://issues.folio.org/browse/UITEN-86
=> UITEN-86 EntryManager - replace edit icon with button

index.js, lib/SearchAndSort/building-filters.md, lib/SearchAndSort/parseFilters.js, lib/SearchAndSort/readme.md
=> Add new document on building filters, and accompanying utility functions

translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20200409T134057

translations/stripes-smart-components/es_ES.json
=> Update translation strings as of 20200416T202404

translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200423T142657

CHANGELOG.md, lib/CustomFields/constants.js, lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
- Add support for Single select dropdown Custom Field type in User record
[UIU-1565](https://issues.folio.org/browse/UIU-1565)
Coverage for Custom Fields will be done in scope of [STSMACOM-331](https://issues.folio.org/browse/STSMACOM-331)
EditCustomFieldsRecord
=> UIU-1565: Create/Edit/View User record | Custom Field | Single select dropdown

CHANGELOG.md, lib/Notes/components/NoteForm/components/NoteFields/NoteFields.js
- Marked Note Title field as required to show red asterisk next to label
=> STSMACOM-323 Marked Note title field as required

CHANGELOG.md, package.json, tests/IntlHarness.js
[STRIPES-672](https://issues.folio.org/browse/STRIPES-672)
=> STRIPES-672 react-intl 4.5

lib/ProxyManager/ProxyForm.js
Provide additional `data-test-` attributes to facilitate testing.
=> additional data-test- attributes

lib/Notes/components/NotesAccordion/NotesAccordion.js
Missed this one.
See https://github.com/folio-org/stripes-smart-components/pull/807 for further explanation
=> NotesAccordion onToggle should be optional

translations/stripes-smart-components/fr_FR.json
=> Update translation strings as of 20200526T141248

CHANGELOG.md, lib/ChangeDueDateDialog/ChangeDueDate.js, lib/ChangeDueDateDialog/ChangeDueDateDialog.js, lib/ChangeDueDateDialog/utils.js, translations/stripes-smart-components/en.json
Add functionality to the `ChangeDueDate` component to handle 'declared lost' items.
Story [UIU-1260](https://issues.folio.org/browse/UIU-1260).
=> UIU-1260: Modify ChangeDueDate to handle 'claimed returned' items

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200602T151309

lib/CustomFields/components/CustomFieldsForm/CustomFieldsForm.js, lib/CustomFields/components/CustomFieldsForm/components/AddButton/AddButton.js, lib/CustomFields/components/CustomFieldsForm/components/AddButton/tests/AddButton-test.js, lib/CustomFields/components/CustomFieldsForm/tests/CustomFieldsForm-test.js, lib/CustomFields/components/CustomFieldsForm/tests/interactor.js, lib/CustomFields/constants.js
Show Custom Field options in "Add custom fields" dropdown in alphabetical order
=> STSMACOM-394: Custom Fields: Display input types dropdown list in alpha

CHANGELOG.md, lib/CustomFields/components/CustomFieldsForm/CustomFieldsForm.js
- Fix issue with editing custom fields after adding them
=> STSMACOM-352: Custom Fields | Unable to create additional custom fields

CHANGELOG.md, lib/AddressFieldGroup/AddressEdit/AddressEdit.js, lib/ChangeDueDateDialog/ChangeDueDate.js, lib/CustomFields/components/CustomFieldsForm/components/AddButton/tests/AddButton-test.js, lib/CustomFields/components/CustomFieldsForm/components/CustomFieldsAccordions/CustomFieldsAccordions.js, lib/CustomFields/components/FieldAccordion/FieldAccordion.js, lib/CustomFields/components/FieldAccordion/edit-fields/RadioButtonSetFields.js, lib/CustomFields/components/FieldAccordion/edit-fields/SelectDropdownFields.js, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/HelpTextField/HelpTextField.js, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/HiddenField/HiddenField.js, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/OptionsField/OptionsField.js, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/OptionsField/tests/OptionsField-test.js, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/OptionsField/tests/interactor.js, lib/CustomFields/components/FieldAccordion/view-sections/shared-values/Options.js, lib/CustomFields/constants.js, lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js, lib/CustomFields/pages/EditCustomFieldsRecord/tests/EditCustomFieldsRecord-test.js, lib/CustomFields/pages/EditCustomFieldsSettings/EditCustomFieldsSettings.js, lib/EntryManager/tests/entry-manager-test.js, lib/Notes/NotesSmartAccordion/tests/interactors/notes-accordion.js, lib/Notes/components/NavigationModal/navigation-modal.js, lib/Notes/components/NoteForm/noteShapes.js, lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js, lib/ProxyManager/ProxyModal.js, lib/SearchAndSort/components/CheckboxFilter/tests/CheckboxFilter-test.js, lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js, lib/SearchAndSort/makeQueryFunction.js, lib/ViewMetaData/tests/interactor.js, package.json, tests/network/config.js
- Update Custom Fields to support unique ids for options
=> STSMACOM-339: Support unique id for custom fields options

lib/CustomFields/pages/EditCustomFieldsSettings/EditCustomFieldsSettings.js
- Fix issue when Custom Field values on User records are reset after editing Custom Fields in Settings
=> Add custom field id to edit custom fields request

lib/EntryManager/EntryWrapper.js
Add onBeforeSave hook in order to integrate EntryManager with ReactFinalForm
https://issues.folio.org/browse/STSMACOM-310
=> STSMACOM-310 - Make EntryManager able to work with stripes-final-form

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200618T161121

CHANGELOG.md, lib/ChangeDueDateDialog/ChangeDueDate.js
https://issues.folio.org/browse/STSMACOM-375
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help …
=> STSMACOM-375 Loan Details > Change due date| Error message is not read by screenreader

CHANGELOG.md, lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
- Fix not unique radio button ids and names
=> STSMACOM-373: Create/Edit User record: Unable to select a radio button option when multiple Custom Field radio button sets are created

CHANGELOG.md, lib/ChangeDueDateDialog/ChangeDueDateSuccess.js
https://issues.folio.org/browse/STSMACOM-376
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help …
=> STSMACOM-376 Loan Details > Successfully change due date is not read by a screenreader

CHANGELOG.md, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/OptionsField/OptionsField.js, translations/stripes-smart-components/en.json
- Fix bug with drag and drop when user try to drag radio button group 
- Add translation for [STSMACOM-355](https://issues.folio.org/browse/STSMACOM-355)
[STSMACOM-367](https://issues.folio.org/browse/STSMACOM-367)
=> STSMACOM-367: Fix bug with drag and drop for radio button group

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200624T130324

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ru.json
=> Update translation strings as of 20200624T182544

translations/stripes-smart-components/ru.json
=> Update translation strings as of 20200701T150841

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200707T213422

CHANGELOG.md, lib/Notes/NoteViewPage/NoteViewPage.js, lib/Notes/NoteViewPage/components/NoteView/tests/interactor.js, lib/Notes/NoteViewPage/tests/NoteViewPage-test.js, lib/Notes/NoteViewPage/tests/interactor.js, tests/network/config.js, tests/network/scenarios/note-view-page.js
If a Note was created and never updated then show username of the user who has created the note
=> STSMACOM-386: Incorrect Last updated Source for Notes that were never updated

translations/stripes-smart-components/ru.json
=> Update translation strings as of 20200709T123052

translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20200710T132222

translations/stripes-smart-components/fr_FR.json
=> Update translation strings as of 20200716T140311

CHANGELOG.md, lib/Notes/components/NoteForm/NoteForm.js, lib/Notes/constants.js
- Remove Note details field character limit
=> STSMACOM-383: Extend Note details character limit to (unlimited) 

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200721T202356

lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js
- Fix incorrect handling of empty Note details
=> STSMACOM-353: Fix substring of undefined content error

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200723T031126

CHANGELOG.md, lib/LocationLookup/LocationModal.js
https://issues.folio.org/browse/UIOR-591
Set record limit for libraries in `<LocationLookup>`
=> UIOR-591 Set record limit for libraries

translations/stripes-smart-components/de.json, translations/stripes-smart-components/fr_FR.json
=> Update translation strings as of 20200728T124214

translations/stripes-smart-components/ru.json
=> Update translation strings as of 20200728T221039

CHANGELOG.md, lib/Notes/NotesSmartAccordion/NotesSmartAccordion.js, lib/Notes/NotesSmartAccordion/tests/interactors/notes-accordion.js, lib/Notes/NotesSmartAccordion/tests/notes-smart-accordion-test.js, lib/Notes/components/NotesAccordion/NotesAccordion.js, lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js, lib/Notes/constants.js, tests/network/config.js, tests/network/scenarios/create-notes-with-note-types.js
Make Notes list column headings sortable. Fix accessibility for Notes List
[STSMACOM-328](https://issues.folio.org/browse/STSMACOM-328)
=> STSMACOM-328: Make Notes list column headings sortable

CHANGELOG.md, lib/CustomFields/components/FieldAccordion/edit-fields/shared-fields/OptionsField/OptionsField.js
- Fix Custom Fields elements to have unique IDs
[STSMACOM-410](https://issues.folio.org/browse/STSMACOM-410)
=> STSMACOM-410: Custom Fields Settings: Document has multiple static elements with the same ID attribute

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200811T193833

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200813T135432

CHANGELOG.md, lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js, lib/Notes/utils/getHTMLSubstring.js, lib/Notes/utils/index.js, lib/Notes/utils/tests/getHTMLSubstring-test.js
Create function for getting HTML substring without tags
[STSMACOM-411](https://issues.folio.org/browse/STSMACOM-411)
=> STSMACOM-411: Show correct number of characters in NoteList details

translations/stripes-smart-components/ar.json
=> Update translation strings as of 20200817T131718

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200827T215834

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20200901T173106

CHANGELOG.md, package.json
Refs [STSMACOM-433](https://issues.folio.org/browse/STSMACOM-433)
=> STSMACOM-433 increment react-intl to v5

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hi_IN.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/ko.json, translations/stripes-smart-components/pl.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20200928T202231

lib/ChangeDueDateDialog/ChangeDueDate.js
https://issues.folio.org/browse/UIU-1495
This is a minor adjustment to the earlier work done to handle Aged to lost items in `<ChangeDueDateDialog>`. I had to revert to the previous way of trapping errors so that they can be handled by the UI.
=> UIU-1495: Fix bug in processing of CDD errors

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ca.json, translations/stripes-smart-components/da.json, translations/stripes-smart-components/de.json, translations/stripes-smart-components/en_GB.json, translations/stripes-smart-components/en_SE.json, translations/stripes-smart-components/en_US.json, translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json, translations/stripes-smart-components/fr.json, translations/stripes-smart-components/fr_FR.json, translations/stripes-smart-components/he.json, translations/stripes-smart-components/hi_IN.json, translations/stripes-smart-components/hu.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/ja.json, translations/stripes-smart-components/ko.json, translations/stripes-smart-components/pl.json, translations/stripes-smart-components/pt_BR.json, translations/stripes-smart-components/pt_PT.json, translations/stripes-smart-components/ru.json, translations/stripes-smart-components/ur.json, translations/stripes-smart-components/zh_CN.json, translations/stripes-smart-components/zh_TW.json
=> Update translation strings as of 20201007T133333

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/it_IT.json, translations/stripes-smart-components/pt_BR.json
=> Update translation strings as of 20201008T220807

translations/stripes-smart-components/it_IT.json
=> Update translation strings as of 20201013T203429

translations/stripes-smart-components/es.json, translations/stripes-smart-components/es_419.json, translations/stripes-smart-components/es_ES.json
=> Update translation strings as of 20201016T144229

translations/stripes-smart-components/de.json
=> Update translation strings as of 20201020T221939

CHANGELOG.md, lib/CustomFields/pages/EditCustomFieldsSettings/tests/DeleteCustomFieldsOptions-test.js, lib/Notes/NoteEditPage/NoteEditPage.js
* Increase received Note types per request on Note Edit page
[STSMACOM-449](https://issues.folio.org/browse/STSMACOM-449)
=> STSMACOM-449 Increase Note types limit on Note Edit page

translations/stripes-smart-components/de.json
=> Update translation strings as of 20201102T140138

translations/stripes-smart-components/ar.json, translations/stripes-smart-components/ja.json
=> Update translation strings as of 20201105T151643

translations/stripes-smart-components/ja.json
=> Update translation strings as of 20201124T212804

CHANGELOG.md, lib/Tags/TagsAccordion.js
Add `closedByDefault` prop to `<TagsAccordion />` for managing open/close accordion status by default
=> UUIN-308 Add closedByDefault prop to TagsAccordion

CHANGELOG.md, lib/AddressFieldGroup/AddressView/AddressView.js, translations/stripes-smart-components/en.json
https://issues.folio.org/browse/UIORGS-220
=> UIORGS-220 AddressView headers are not translated

CHANGELOG.md, lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js
Allow submitting of Assign/Unassign Notes modal form by pressing Enter
[STSMACOM-471](https://issues.folio.org/browse/STSMACOM-471)
=> STSMACOM-471: Assign/Unassign modal: Hit enter key in search box does not initiate a search

lib/CustomFields/components/FieldAccordion/FieldAccordion.js, lib/EditableList/EditableListForm.js, lib/EntryManager/EntryForm.js, lib/EntryManager/EntrySelector.js, lib/EntryManager/EntryWrapper.js, lib/LocationSelection/LocationSelection.js, lib/Notes/NoteCreatePage/NoteCreatePage.js, lib/Notes/NoteEditPage/NoteEditPage.js, lib/Notes/NoteViewPage/NoteViewPage.js, lib/Notes/NoteViewPage/components/NoteView/NoteView.js, lib/Notes/components/NoteForm/NoteForm.js, lib/Notes/components/NoteForm/components/NoteFields/NoteFields.js, lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js, lib/Notes/components/NotesAccordion/components/NotesList/NotesList.js, lib/SearchAndSort/SearchAndSort.js, lib/SearchAndSort/components/ExpandFilterPaneButton/ExpandFilterPaneButton.js, lib/Tags/TagsForm.js, lib/utils/index.js
https://issues.folio.org/browse/STSMACOM-485
Most or the errors are wrong usage of `<FormattedMessage>` with function as a child
https://formatjs.io/docs/react-intl/components/#function-as-the-child
=> STSMACOM-485 fix JS console errors

CHANGELOG.md, lib/RemoteStorageTag/RemoteStorageTag.js, lib/utils/useRemoteStorageMappings.js, package.json
https://issues.folio.org/browse/STSMACOM-486
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help …
=> STSMACOM-486 Guard appearance of remote-storage field with `hasInterface()

CHANGELOG.md, translations/stripes-smart-components/en.json
purpose: https://issues.folio.org/browse/STSMACOM-497
=> STSMACOM-497 Organizations alternate address label in org view not showing correctly

package.json
https://issues.folio.org/browse/STSMACOM-510
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help …
=> STSMACOM-510 Update "remote-storage-mappings" interface

package.json
https://issues.folio.org/browse/STSMACOM-510
The only that changed from 1.0 to 2.0 was adding a new endpoint and SSC doesn't touch that part of the surface
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
=>  STMACOM-510 Use two versions of "remote-storage-mappings" interface

CHANGELOG.md, lib/Notes/components/NoteForm/NoteForm.js
Fixed NoteForm to take the screen width. This change is required for [UICR-126](https://issues.folio.org/browse/UICR-126).
Issue: [STSMACOM-524](https://issues.folio.org/browse/STSMACOM-5240)
=> STSMACOM-524: Fix NoteForm to take the screen width

CHANGELOG.md, lib/CustomFields/pages/EditCustomFieldsSettings/tests/DeleteCustomFieldsOptions-test.js, lib/CustomFields/pages/EditCustomFieldsSettings/tests/interactor.js, lib/LocationLookup/LocationModal.js
Sort institutions, campuses and libraries in alphabetical order.
https://issues.folio.org/browse/STSMACOM-530
=> STSMACOM-530: Sort institutions, campuses and libraries

lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js
https://issues.folio.org/browse/STSMACOM-493
List of major changes:
- The component was rewritten in a functional style, which reduced the code by 80+ lines
- Text fields have been replaced with Datepickers
=> STSMACOM-493 DateRangeFilter: Use Datepicker

lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js
Adding logic to apply a filter when the enter key is pressed
[STSMACOM-494](https://issues.folio.org/browse/STSMACOM-494 )
=> STSMACOM-494 DateRangeFilter should submit on Enter key

lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js
DatePicker component goes off the page
in some places the datepicker was cut off by the screen
[STSMACOM-534](https://issues.folio.org/browse/STSMACOM-534)
=> STSMACOM-534 DatePicker component goes off the page

CHANGELOG.md, lib/EditableList/EditableListForm.js, lib/SearchAndSort/components/MultiSelectionFilter/tests/MultiSelectionFilter-test.js
purpose: https://issues.folio.org/browse/STSMACOM-548
=> STSMACOM-548 Apply baseline keyboard shortcuts for controlled vocabulary

lib/EditableList/EditableListForm.js
https://issues.folio.org/browse/STSMACOM-548
=> STSMACOM-548 fix rerender after entity creation in EditableList

CHANGELOG.md, lib/AddressFieldGroup/tests/AddressEdit-test.js, lib/SearchAndSort/SearchAndSortQuery.js
Update internal state in SASQ when sort changes.
https://issues.folio.org/browse/STSMACOM-614
=> STSMACOM-614: Update internal state in SASQ when sort changes

CHANGELOG.md, lib/CustomFields/pages/ViewCustomFieldsSettings/ViewCustomFieldsSettings.js, lib/LocationLookup/LocationLookup.js, lib/Notes/NotePopupModal/NotePopupModal.js, lib/SearchAndSort/components/DateRangeFilter/DateRangeFilter.js, lib/SearchAndSort/tests/SearchAndSort-test.js
Lint all the things that keep showing up as noise on other PRs.
=> Linty mclintface

lib/PasswordValidationField/tests/interactor.js, lib/UserName/tests/UserName-test.js, lib/UserName/tests/interactor.js
- Added `UserName` interactor and tests.
- Small spelling correction to `PasswordValidationFieldInteractor`
Refs [STSMACOM-610](https://issues.folio.org/browse/STSMACOM-610)
=> STSMACOM-610 UserName interactor

lib/ControlledVocab/tests/ControlledVocab-test.js, lib/EditableList/tests/EditableList-test.js
requires a merge of https://github.com/folio-org/stripes-testing/pull/165
=> STSMACOM-607 Editable list tests/new interactor

lib/SearchAndSort/SearchAndSort.js
Humbly cleaning up a miss-resolve.
=> Remove duplicate SearchAndSort props

CHANGELOG.md, lib/ConfigManager/ConfigForm.js, lib/ControlledVocab/ControlledVocab.js, lib/EntryManager/EntrySelector.js, lib/Settings/Settings.js
purpose: https://issues.folio.org/browse/STSMACOM-631 and connected to focus for settings stories
approach: Pane onMount + title ref
=> STSMACOM-631 Change focus on ConfigManager mount

CHANGELOG.md, lib/ChangeDueDateDialog/LoanList.js
Purpose: https://issues.folio.org/browse/STSMACOM-630
Approach: update column names to be unique
=> STSMACOM-630 Accessibility: the same ID attribute

CHANGELOG.md, lib/ControlledVocab/ControlledVocab.js, lib/EntryManager/EntrySelector.js, lib/Settings/Settings.js
Purpose: 
https://issues.folio.org/browse/STSMACOM-628?focusedCommentId=122916&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-122916
=> STSMACOM-628 Settings : Move focus to second pane

CHANGELOG.md, lib/ControlledVocab/ControlledVocab.js, lib/Settings/Settings.js
https://issues.folio.org/browse/STSMACOM-652
=> Add pane id to ControlledVocab, Settings components

lib/SearchAndSort/SearchAndSort.js, lib/SearchAndSort/makeQueryFunction.js, lib/Settings/Settings.js, package.json
Clean up, clean up, everybody clean up!
Refs [STSMACOM-656](https://issues.folio.org/browse/STSMACOM-656)
=> STSMACOM-656 import via stripes-components public exports

CHANGELOG.md, lib/EditableList/constants.js, lib/EditableList/processBadResponse.js, translations/stripes-smart-components/en.json
Purpose
https://issues.folio.org/browse/STSMACOM-668
Display appropriate error message for optimistic locking
=> STSMACOM-668 ControlledVocab - optimistic locking

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, lib/Notes/NotePopupModal/NotePopupModal.js, lib/Notes/NotePopupModal/tests/NotePopupModal-test.js, lib/Notes/NotesSmartAccordion/tests/notes-smart-accordion-test.js, tests/network/scenarios/create-notes-with-note-types.js
Issue: All notes on a user record set to pop up should pop up, not just the first
https://issues.folio.org/browse/STSMACOM-667
=> STSMACOM-667 - All notes on a user record set to pop up should pop up, not just the first

CHANGELOG.md, lib/Notes/NotePopupModal/NotePopupModal.js
Issue: [STSMACOM-694](https://issues.folio.org/browse/STSMACOM-694)
=> STSMACOM-694 - Pop-up Note > Display MetaSection component

package.json, yarn.lock
=> STSMACOM-721 Remove resolutions. 

lib/ConfigManager/ConfigManager.js
Additional nullish coalescing fix for `<ConfigManager>`
[STSMACOM-720](https://issues.folio.org/browse/STSMACOM-720)
https://github.com/folio-org/stripes-smart-components/pull/1313
=> STSMACOM-720 Further fix of ConfigManager nullish coalescing

CHANGELOG.md, lib/SearchAndSort/makeQueryFunction.js
https://issues.folio.org/browse/STSMACOM-745
This should be merged after https://github.com/folio-org/stripes-connect/pull/200 is merged
=> STSMACOM-745: Fix import to stripes-connect

CHANGELOG.md, lib/SearchAndSort/makeQueryFunction.js
This reverts commit b425402d615b9a986588771ff8ef6780dfc3764c.
=> Revert "STSMACOM-745: Fix import to stripes-connect (#1343)"

CHANGELOG.md, lib/CustomFields/pages/EditCustomFieldsRecord/EditCustomFieldsRecord.js
=> STSMACOM-750 Removed 'isRequired' check on 'expanded' prop-type. EditCustomFieldsRecord.js

lib/SearchAndSort/SearchAndSort.js
To save last open Instance record for each segment we need to be able to update SAS `selectedItem` via props
[STSMACOM-758](https://issues.folio.org/browse/STSMACOM-758)
=> STSMACOM-758: Update SearchAndSort `selectedItem` when `initiallySelectedRecord` changes

CHANGELOG.md, lib/SearchAndSort/SearchAndSort.css, lib/SearchAndSort/SearchAndSort.js, lib/SearchAndSort/readme.md, lib/SearchAndSort/tests/SASTestHarness.js, lib/SearchAndSort/tests/SearchAndSort-test.js, translations/stripes-smart-components/en.json
Added Advanced Search to `<SearchAndSort>` component.
https://github.com/folio-org/stripes-smart-components/assets/19309423/1ee34391-9795-4330-8d96-c1bca78ef84a
[STSMACOM-767](https://issues.folio.org/browse/STSMACOM-767)
https://github.com/folio-org/ui-inventory/pull/2197
https://github.com/folio-org/stripes-components/pull/2091
=> STSMACOM-767 Add Advanced Search modal to SearchAndSort

lib/SearchAndSort/SearchAndSort.js
Automatically perform search when clicking on Advanced Search's Submit button
[STSMACOM-767](https://issues.folio.org/browse/STSMACOM-767)
=> STSMACOM-767 Automatically search after using advanced search

CHANGELOG.md, lib/ControlledVocab/ControlledVocab.js, lib/ControlledVocab/tests/ControlledVocab-test.js, lib/ControlledVocab/tests/mountComponent.js
* There are no information about user in metadata in profiles which were created by system.
[STSMACOM-858](https://folio-org.atlassian.net/browse/STSMACOM-858)
=> STSMACOM-858: Display "System" user when there is no "updatedByUserId" field in metadata

CHANGELOG.md, package.json
=> STSMACOM-861 Upgrade `notes` to `v4.0`

.github/workflows/ui.yml
Update to the current workflow version (1.5) and avoid repeating the same steps when a single action (i.e. creating a PR) sends multiple events.
Refs [STSMACOM-862](https://folio-org.atlassian.net/browse/STSMACOM-862)
=> STSMACOM-862 avoid repeat GA actions

CHANGELOG.md, lib/Notes/NoteViewPage/components/NoteView/NoteView.js, lib/Notes/components/NotesAccordion/NotesAccordion.js
Reverts folio-org/stripes-smart-components#1532
=> Revert "STSMACOM-870: Rename the `ui-notes.item.assign-unassign` permission."

lib/CustomFields/components/CustomFieldsForm/components/DeleteModal/tests/DeleteModal-test.js
Remove `.only` in tests so that all tests can run
=> STSMACOM-875 remove .only in tests (follow-up)

.github/CODEOWNERS
Refs [STSMACOM-881](https://folio-org.atlassian.net/browse/STSMACOM-881)
=> STSMACOM-881 implement CODEOWNERS

lib/ChangeDueDateDialog/LoanList.js
PR #1556 fixed the import but introduced a bug :facepalm: by changing from a default import (from the path, which was wrong) to a named import (which was wrong) from the public exports. Whoops.
Refs [STSMACOM-884](https://folio-org.atlassian.net/issues/STSMACOM-884)
=> STSMACOM-884 correctly call imports from public paths

.gitignore, package.json
* remove engines.node; this is a browser project
* ignore compiled translations
Refs [STSMACOM-894](https://folio-org.atlassian.net/browse/STSMACOM-894)
=> STSMACOM-894 package.json cleanup
